### ISSUE TITLE
Update Checker > 1.4.11 download > installer > crashed on OSX and XP Bootcamp

### ISSUE THREAD

**Issue by teamplayerinstress** [crystalidea/macs-fan-control#101]
ATTENTION: All Issue reports should please contain a screenshot and the system Diagnostics text, as described [here](https://github.com/crystalidea/macs-fan-control/blob/master/.github/CONTRIBUTING.md)

hi,
i use macs fan control on the imac 2009 with bootcamp.

windows XP.

after a restart the software reminds me for an update.

macs fan control 1.4.9 is installed.

the download of 1.4.10 and 1.4.11 is ok.

…but the installer / exe shuts down while the process.

on OSX el capitan and windows XP

is it possible to deaktivate the update info.

cause 1.4.9 works fine.

greetings

**Comment by teamplayerinstress** [comment]
This morning:
Someone startet our mac on the reception.
Then she has to go away and the imac startet alone...

So far so bad...

In the evening in came in and saw the overheated & crashed imac. Totally damaged, cause the fans run wild when the update reminder window will not be closed & the imac starts to overheat.

This is a free software, but this software killed our imac and whole system.

I lost a lot of money...

I wrote a lot of mails to crystal idea... but no response. 

I am angry, more than the silly birds !

**Comment by kleuter** [comment]
The mac crashed because you replaced the original HDD with a 3rd party hdd.
The app helped to cool down the mac but an OK button must have been pressed in the update reminder dialog. We removed this update dialog due to number of complains, I'm sorry for your loss.

The [download](https://www.crystalidea.com/macs-fan-control/download) page (and the About dialog in the program) states:

> This program is for advanced users who know how to use it without doing harm to their macs. The authors are not liable for data loss, damages, profit loss or any other types of losses connected with the use or misuse of the program.
