### ISSUE TITLE
program checks for update even if option is unchecked

### ISSUE THREAD

**Issue by mcringbearer** [crystalidea/macs-fan-control#104]
1) the 'Check for updates automatically is unchecked', yet program does check and report an update is available.  This confuses my familiy and friends to whom I have recommended the program; they get prompted EVERY time the system reboots to 'Continue' or 'Exit'.

2) the 'Check for updates automatically' option is located on the Check for updates dialog; this is NOT user friendly.  In order to turn it OFF, you have to first check for an update in order to get the dialog to pop up.  The option should be on the PReferences window.

Version 1.4.10

**Comment by kleuter** [comment]
1. FIxed in 1.4.11
2. Thanks, marked as enhancement 
https://github.com/crystalidea/macs-fan-control/issues/105
