### ISSUE TITLE
Can not change the fan speed

### ISSUE THREAD

**Issue by Wizzel1** [crystalidea/macs-fan-control#106]
For some reason i can't change the fanspeed. When i first installed it, it worked fine but after i restarted the mac, it does not work and it only runs on automatic speed it seems. I tried reinstalling fancontrol and then a window poped up telling me something like "read only mode" because some file was missing or something.

**Comment by os4834** [comment]
trey to reset the NVRAM(PRAM) https://support.apple.com/en-us/HT204063 what mac you have? what model? did you try to reset the SMC?

**Comment by Wizzel1** [comment]
I have a 15" 2011 macbook pro. So i just tried to update the programm and it told me : (translated from german) Read only mode. A filesystem was found, that is not an apple filesystem.(nullfs)

I am new to apple and i dont have a clue what that means. 

Thanks for your help !

**Comment by kleuter** [comment]
@Wizzel1 just move the app to Applications
