### ISSUE TITLE
after update to 1.4.12 , the fans current speed is always 0

### ISSUE THREAD

**Issue by Molly2Molly** [crystalidea/macs-fan-control#108]
![macfans](https://user-images.githubusercontent.com/3402948/45853881-6ef4d900-bd7a-11e8-9416-9847b543ff9b.png)

Macs Fan Control 1.4.12
MacBookPro13,1
CPU: Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz [100]
GPU: Intel Iris Graphics 540
macOS 10.13.6

Fans:
Exhaust-min{1200}curr{0}max{7200}mode{2,TC1C,55,65}

TempSensors:
TA0V () - 25.3672, 25.3672
TB0T (Battery Max) - 39.0977, 39.0977
TB1T (Battery Sensor 1) - 39.0977, 39.0977
TB2T (Battery Sensor 2) - 37.7969, 37.7969
TBXT () - 39.0977, 39.0977
TC0E () - 69.1758, 69.1758
TC0F () - 71.2812, 71.2812
TC0P (CPU Proximity) - 60.75, 60.75
TC1C (CPU Core 2) - 64, 64
TC2C (CPU Core 3) - 66, 66
TCGC (GPU PECI) - 64, 64
TCMX () - 66.4375, 66.4375
TCMc () - 0, 0
TCSA () - 65, 65
TCXC (CPU PECI) - 66.4375, 66.4375
TH0A () - 49, 49
TH0B () - 129, 129
TH0C () - 129, 129
TH0F () - 219.988, 219.988
TH0R () - 220, 220
TH0V () - 49.3008, 49.3008
TM0P (Memory Proximity) - 54.8125, 54.8125
TPCD (Platform Controller Hub Die) - 60, 60
TULD () - 128, 128
TULP () - 128, 128
TW0P () - 128, 128
TaLC () - 48.5625, 48.5625
Th1H (Heatsink Proximity) - 53.25, 53.25
Tm0P () - 128, 128
Ts0P (Palm Rest) - 36.875, 36.875
Ts0S () - 43.3789, 43.3789
Ts1P () - 35.3125, 35.3125
Ts1S () - 42.2969, 42.2969

Disk drives:

**Comment by kleuter** [comment]
0 means that the fan is currently OFF (the macbook is cool enough not to turn it on)

**Comment by Molly2Molly** [comment]
the truth is , my macbook pro fan is broken,  sad  :-(

**Comment by kleuter** [comment]
how do you know that? If the CPU temp is low enough, the fan will be always off.

**Comment by Molly2Molly** [comment]
I went to Apple Store, and the genius checked the hardware, make sure that the fan was broken.
