### ISSUE TITLE
Changing temperature presets

### ISSUE THREAD

**Issue by cmarquardt** [crystalidea/macs-fan-control#111]
While trying different temperatures sensors for controlling fan speed, I noticed that the presets depend on which one I tried before - sometimes the previous values are just used with the new sensor, sometimes they are replaced by some other values, but they rarely reflect the values I had set them to before. For example:

Starting with CPU PECI:

![screen shot 2018-09-23 at 15 36 23](https://user-images.githubusercontent.com/1011533/45928623-c8a9fe80-bf46-11e8-9c7b-a55cd737b770.png)

and switching to CPU Proximity:

![screen shot 2018-09-23 at 15 37 06](https://user-images.githubusercontent.com/1011533/45928625-d52e5700-bf46-11e8-9ad5-4ebe185c0f24.png)

...then to the system's SSD:

![screen shot 2018-09-23 at 15 37 28](https://user-images.githubusercontent.com/1011533/45928627-e0818280-bf46-11e8-952d-f23eb2650ce3.png)

...and finally to back to CPU Proximity:

![screen shot 2018-09-23 at 15 37 52](https://user-images.githubusercontent.com/1011533/45928639-132b7b00-bf47-11e8-82b6-3a882625c8a7.png)

Note that in each step, I simply accepted the offered values with the OK button.

In this particular example, both CPU Proximity temperature boundaries only got reduced by 1 degree, but I have seen much larger changes - up to 10 degrees or so for individual values.

I understand from your response to #20 that you do not consider the presets as some kind of recommendation, and that's fair enough. Nevertheless, I would expect that whatever has been configured with the last press of the OK button remains unmodified until it is actively changed again by the user - rather then being modified by the app without even warning that the respective modification has occurred. 

Technical info:

```
Macs Fan Control 1.4.12
iMac14,2
CPU: Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz [100]
GPU: Intel Iris Pro [active], NVIDIA GeForce GTX 775M
macOS 10.13.6

Fans:
Main-min{1200}curr{1657}max{2640}mode{2,TC0p,37,50}

TempSensors:
TA0P () - 12.125, 12.125
TA0V () - 22.8438, 22.8438
TA0p (Ambient) - 32.125, 32.125
TC0E () - 201.062, 201.062
TC0F () - 203.207, 203.207
TC0J () - 2.14453, 2.14453
TC0P () - 42.375, 42.375
TC0T () - 0.015625, 0.015625
TC0c (CPU Core 1) - 45, 45
TC0p (CPU Proximity) - 42.375, 42.375
TC1c (CPU Core 2) - 43, 43
TC2c (CPU Core 3) - 45, 45
TC3c (CPU Core 4) - 43, 43
TCGc (GPU PECI) - 44, 44
TCSc () - 42, 42
TCXR () - 201.312, 201.312
TCXc (CPU PECI) - 45.3125, 45.3125
TCXr () - 201.312, 201.312
TG0D () - 49, 49
TG0E () - 49.1172, 49.1172
TG0F () - 49.9062, 49.9062
TG0J () - 0.789062, 0.789062
TG0P () - 39.25, 39.25
TG0T () - 255.977, 255.977
TG0d (GPU Diode) - 40, 40
TG0p (GPU Proximity) - 39.25, 39.25
TH0A () - 129, 129
TH0B () - 129, 129
TH0C () - 129, 129
TH0F () - 129, 129
TH0O () - 9, 9
TH0P () - 129, 129
TH0R () - 129, 129
TH0a () - 129, 129
TH0b () - 129, 129
TH0c () - 129, 129
TH0e () - 1, 1
TH1A () - 42.875, 42.875
TH1B () - 34.75, 34.75
TH1C () - 129, 129
TH1F () - 215.633, 215.633
TH1O () - 9, 9
TH1P () - 129, 129
TH1R () - 215.75, 215.75
TH1a () - 42.875, 42.875
TH1b () - 34.75, 34.75
TH1c () - 129, 129
TL0P () - 37.375, 37.375
TL0V () - 35.8789, 35.8789
TL0p (LCD proximity) - 37.375, 37.375
TL1P () - 38.3125, 38.3125
TL1V () - 33.6914, 33.6914
TL1p (LCD Proximity 2) - 38.3125, 38.3125
TL1v () - 33.6953, 33.6953
TM0P () - 36.25, 36.25
TM0V () - 43.25, 43.25
TM0p (DIMM Module 1 Proximity) - 36.25, 36.25
TM1P () - 31.875, 31.875
TM1a () - 50.8633, 50.8633
TM1p (DIMM Module 2 Proximity) - 31.875, 31.875
TM2P () - 34.5, 34.5
TM2a () - 47.3477, 47.3477
TM2b () - 50.3477, 50.3477
TM2c () - 47.3477, 47.3477
TM2d () - 50.3477, 50.3477
TM2p (DIMM Module 3 Proximity) - 34.5, 34.5
TM3P () - 34.875, 34.875
TM3a () - 44.3477, 44.3477
TM3b () - 42.3477, 42.3477
TM3c () - 43.4219, 43.4219
TM3d () - 44.3477, 44.3477
TM3p (DIMM Module 4 Proximity) - 34.875, 34.875
TM4a () - 43.25, 43.25
TMXP () - 36.25, 36.25
TPCD (Platform Controller Hub Die) - 40, 40
TS0V () - 32.4531, 32.4531
Tb0P () - 43.5, 43.5
Tb0p () - 43.5, 43.5
Tm0P () - 36.75, 36.75
Tm0p () - 36.75, 36.75
Tm1P () - 37.5, 37.5
Tm1p () - 37.5, 37.5
Tm2P () - 40.125, 40.125
Tm2p () - 40.125, 40.125
Tp2F () - 35.1172, 35.1172
Tp2H () - 35.125, 35.125
Tp2h () - 35.125, 35.125

Disk drives:
APPLE SSD SD0128F - 42.875
WDC WD6001FZWX-00A2VA0 - 44
```

**Comment by kleuter** [comment]
Implemented in v1.5
