### ISSUE TITLE
Menubar text doesn't get grayed out when switching between monitors

### ISSUE THREAD

**Issue by advicepyro** [crystalidea/macs-fan-control#112]
Previously in High Sierra, when there's more than one monitor, the fan speed text properly dims on the menu bar when focus is not on that screen.

On Mojave this is no longer the case:

<img width="248" alt="screen shot 2018-09-24 at 11 00 02 pm" src="https://user-images.githubusercontent.com/6377466/45990371-eca43780-c04d-11e8-88e9-40b7100542fa.png">

**Comment by kleuter** [comment]
I confirm the issue, though still have no idea why it happens

**Comment by uu1t** [comment]
This is the case with menubar icon.

Light mode:
<img width="155" alt="light_inactive" src="https://user-images.githubusercontent.com/35105763/47093474-3a364d80-d264-11e8-86df-e8eec3692da1.png">

Dark mode:
<img width="162" alt="dark_inactive" src="https://user-images.githubusercontent.com/35105763/47093507-4a4e2d00-d264-11e8-85f4-fa1d54a3bffd.png">

**Comment by kleuter** [comment]
I just wonder why....

**Comment by riquack** [comment]
Any updates on this issue?

**Comment by kleuter** [comment]
Could you please try the latest update? 1.5

**Comment by advicepyro** [comment]
@kleuter issue remains with the latest 1.5 release. macOS 10.14.6

**Comment by kleuter** [comment]
Please test again with the [latest beta](https://github.com/crystalidea/macs-fan-control/issues/218)

**Comment by kleuter** [comment]
Fixed in 1.5.1
