### ISSUE TITLE
CPU Core X temperature missing

### ISSUE THREAD

**Issue by levon-gevorgyan** [crystalidea/macs-fan-control#113]
For CPU Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz CPU Core 5 & CPU Core 6 temperatures are missing.
![screen shot 2018-09-25 at 3 25 03 pm](https://user-images.githubusercontent.com/16690828/46011681-ad222d80-c0d7-11e8-9d16-cd64810488f9.png)

**Comment by kleuter** [comment]
Will be fixed soon, thanks.

**Comment by kleuter** [comment]
Please try the [1.5 beta version](https://www.crystalidea.com/downloads/macsfancontrol_beta.zip)

**Comment by levon-gevorgyan** [comment]
Thanks @kleuter now I can see
![screen shot 2018-09-29 at 5 40 41 pm](https://user-images.githubusercontent.com/16690828/46246460-13c48580-c40f-11e8-8089-c4dcff43e9e1.png)
