### ISSUE TITLE
read-only: non-Apple fine sistem detected(nulfs)

### ISSUE THREAD

**Issue by firemob** [crystalidea/macs-fan-control#114]
a few days ago this started to appear on High Sierra and in Mojave also.
MacBook pro 9`2 it runs 2000  rpm and that is it no controls 

read-only: non-Apple fine sistem detected(nulfs). Please move the app to ´\ Applications 
![screen shot 2018-09-27 at 10 38 51 am](https://user-images.githubusercontent.com/43635857/46133967-132ac400-c242-11e8-9d72-8275e56ad612.png)

**Comment by kleuter** [comment]
> Please move the app to '/Applications'
