### ISSUE TITLE
Unistall MAC FAN CONTROLLER 

### ISSUE THREAD

**Issue by ozy1ozy** [crystalidea/macs-fan-control#115]
It concerns me that uninstalling the Mac Fan Controller does not actually remove all the debris. The best solution I've found so far is to go through the Library and delete any references to it. Surely you should have a proper uninstaller?

**Comment by kleuter** [comment]
MFC consists of two items
- /Applications/Macs Fan Control.app
- ~/Library/Preferences/com.crystalidea.macsfancontrol.plist

**Comment by ozy1ozy** [comment]
As I say, this is not the way to manage an app (in my view). First I had to search on the internet for instructions and then go through the Library folders to delete any references. Perhaps you should add a readme to the zip explaining this?.
