### ISSUE TITLE
1.5 beta

### ISSUE THREAD

**Issue by kleuter** [crystalidea/macs-fan-control#116]
- New helper tool that must improve **CPU usage** and **stability** 
- Fixed detection and displaying of CPU cores on different machines
- If a user doesn't want to override fan control, he can skip checking admin privilege on startup by checking "Don't show this message again" #77
- New option in preferences to disable reading and displaying of connected S.M.A.R.T. drives temperatures. Most people also don't want to display temperatures of connected USB/Thunderbolt drives. What is more: modern macs internal PCIe based SSD drives often don't support S.M.A.R.T (the app automatically detects such hardware and turns this setting off by default). 
- Better support of Macmini & MacBookAir 2018
- Dark mode support in macOS Mojave 
- New improved Preferences dialog
- Improved user interface thanks to more recent Qt framework (5.12)
- Supports macOS **10.12 Sierra and later**. macOS 10.7, 10.8, 10.9, 10.10 and 10.11 will be also supported in a separate download
- [Windows] Compiled with Visual C++ 2017

[macOS](https://www.crystalidea.com/downloads/macsfancontrol_beta.zip), [Windows](https://www.crystalidea.com/downloads/macsfancontrol_setup_beta.exe)

**Comment by kleuter** [comment]
- [Mac] If a user doesn't want to override fan control, he can skip checking admin privilege on startup by checking "Don't show this message again" #77

**Comment by kleuter** [comment]
New beta is available
- New helper tool that must improve **CPU usage** and **stability** 
- New improved Preferences dialog
- Dark mode in macOS Mojave support

**Comment by vdroid711** [comment]
@kleuter thank you for the beta!

I was experiencing plenty of slowdowns since upgrading to Mojave but could never get down to the core issue why. During custom modes the mac would just hang there whilst opening an app via Spotlight. From issue #151 - it seems to clock the processor to its lowest state to ensure adequate cooling as if MacOS could not detect the fans. 

This is normally solved by reseting the fan speed back to auto. 

The cause of this maybe purely due to the new privacy/access rights from Mojave via "Accessibility" and "Full Disk Access". Since adding MFC to a higher access rights I have not had any slowdowns since!

Hope this helps!

A thankful leech

**Comment by jconley** [comment]
still using a cumulatively large amount of cpu time with the 1.5.0 beta...
Mojave 10.14.4

<img width="300" alt="Screen Shot 2019-04-29 at 9 18 10 AM" src="https://user-images.githubusercontent.com/22428/56903625-2ded4180-6a8c-11e9-8ec7-5bb245800d8f.png">

**Comment by kleuter** [comment]
@jconley please post the screenshot of the app when it takes lots of cpu %

**Comment by jconley** [comment]
@kleuter the screenshot i posted shows _cumulative_ time relative some key system processes like kernel, windowserver, etc which do a lot of common work... it was using more cpu than i would expect, almost 11 hours total. e.g. constantly sipping a few percent of cpu, and at times spiking to 10+ percent.  perhaps it's unavoidable for the task at hand...

**Comment by jconley** [comment]
@kleuter i also just tried setting the app to "Auto" for both fans. my menu bar icon just shows the app icon only and no data.  i would think this means the app is effectively doing nothing, but it still continued to take 1.3-3% cpu at all times.
after that i set it back to "Custom" and restarted the app... and now it only takes 0.1-0.2% cpu.  perhaps something is happening after it runs for long periods that increases the cpu usage... (could even be a glitch in a mac library you're using)  i'll keep an eye on it for the next few days.

**Comment by jconley** [comment]
@kleuter following up, i sent some detailed info to support@crystalidea... hopefully that info made it to you.

**Comment by kleuter** [comment]
I believe it must be improved in the next beta, it's going to be soon

**Comment by devinrhode2** [comment]
Hey @kleuter could we get a status update on the 1.5 official release or the next beta? Catalina is around the corner and I'm still on High Sierra. Macs Fan Control is probably the only thing that I need to work well on mojave before I upgrade. Soon we won't be able to upgrade to mojave unless we've already downloaded the "Install Mojave" package from app store.

**Comment by devinrhode2** [comment]
Macs Fan Control is like the greatest. And so I just paid 15 dollars to help @kleuter find time for it. Everyone reading this - if you haven't paid you should pay here to help get the official 1.5 release out: https://www.crystalidea.com/macs-fan-control/buy

**Comment by kleuter** [comment]
1.5 Final will be released 23-24.09.2019

**Comment by devinrhode2** [comment]
https://github.com/crystalidea/macs-fan-control/releases/tag/v1.5

**Comment by devinrhode2** [comment]
thank you @kleuter 
I will test when i upgrade to mojave

**Comment by devinrhode2** [comment]
@kleuter what mac modals+os versions do you know this should be working for? (presumably all modals and all os versions, but I'm more curious about which mac models+os versions you got to actually test this release on. I'm assuming you don't own a basement full of every modal macbook you intend to support lol)

**Comment by kleuter** [comment]
(10.14 and 10.15)
https://www.crystalidea.com/downloads/macsfancontrol.zip

(10.7 to 10.13)
https://www.crystalidea.com/downloads/legacy/macsfancontrol.zip

https://www.crystalidea.com/macs-fan-control/supported-models
