### ISSUE TITLE
macOS Mojave: better dark mode support 

### ISSUE THREAD

**Issue by kleuter** [crystalidea/macs-fan-control#117]
Currently the app only partially supports the dark mode.

**Comment by JohnD0406** [comment]
Partially?  I'd call it "not at all" - every part of the window is bright white/gray.  Eventually all apps will (hopefully) support Mojave's dark mode, but that will take time and is low priority, with major issues looming (like random app quitting).

**Comment by kleuter** [comment]
The next version will support the dark theme (just a teaser)
<img width="729" alt="2018-10-18 21 27 10" src="https://user-images.githubusercontent.com/2600624/47179259-e720d100-d31d-11e8-8eb4-ab6e8578a7eb.png">

**Comment by kleuter** [comment]
Implemented in 1.5 final
