### ISSUE TITLE
Problem with fans on MacBook Pro 2018 15,2

### ISSUE THREAD

**Issue by shal** [crystalidea/macs-fan-control#118]
Machine: MacBook Pro 2018 with T2 processor
System: MacOS Mojave 10.14 

I got an issue with fans on my mac. 

There is something strange happening with my mac, when use your application. Few days ago everything worked pretty good, by now I afraid there is an issue with fans.

I wanted to run fans on 6500 speed, but it workes for one second, then stop, and again and again.

I updated from Hight Sierra to Mojave and issue persist. 

<img width="698" alt="screen shot 2018-10-03 at 01 57 59" src="https://user-images.githubusercontent.com/15674738/46381802-7daf8a00-c6b0-11e8-9c4f-e3cc0c327825.png">
<img width="933" alt="screen shot 2018-10-03 at 02 00 51" src="https://user-images.githubusercontent.com/15674738/46381803-7daf8a00-c6b0-11e8-9c15-6b1834100593.png">
<img width="933" alt="screen shot 2018-10-03 at 02 00 56" src="https://user-images.githubusercontent.com/15674738/46381804-7daf8a00-c6b0-11e8-9b4f-ef790350f1d6.png">
<img width="933" alt="screen shot 2018-10-03 at 02 01 01" src="https://user-images.githubusercontent.com/15674738/46381805-7daf8a00-c6b0-11e8-9a6d-a42c75f132c9.png">
<img width="933" alt="screen shot 2018-10-03 at 02 01 06" src="https://user-images.githubusercontent.com/15674738/46381806-7e482080-c6b0-11e8-979c-9b42b03f4ac6.png">
<img width="933" alt="screen shot 2018-10-03 at 02 01 08" src="https://user-images.githubusercontent.com/15674738/46381807-7e482080-c6b0-11e8-88eb-8d7b80659250.png">
<img width="933" alt="screen shot 2018-10-03 at 02 01 09" src="https://user-images.githubusercontent.com/15674738/46381808-7e482080-c6b0-11e8-9ec0-b8318b7e0d84.png">
<img width="933" alt="screen shot 2018-10-03 at 02 01 11" src="https://user-images.githubusercontent.com/15674738/46381809-7e482080-c6b0-11e8-9033-a2d7ef1bfd6b.png">

**Comment by kleuter** [comment]
1. Please try to reset SMC.
2. If it doesn't help, please set 6500 RPM and run this tool in Terminal:
https://www.crystalidea.com/downloads/smc.zip

```./smc -l > smc.txt```

Please the smc.txt file here.

**Comment by shal** [comment]
Hello @kleuter, thanks for answer.

Here is this file.`
[smc.txt](https://github.com/crystalidea/macs-fan-control/files/2487256/smc.txt)
`

**Comment by kleuter** [comment]
I see both fans are set to Auto (system controlled)
F0Md  [ui8 ]  0 (bytes 00)
F1Md  [ui8 ]  0 (bytes 00)

Must be 1 (not zero). Do you have any other app that controls fan speed?

**Comment by kleuter** [comment]
F1Ac  [flt ]  (bytes 00 00 00 00)

The current speed is also 0 for the Right side fan

**Comment by shal** [comment]
@kleuter  I see, I didn't install any other app for fans controll.

**Comment by shal** [comment]
@kleuter maybe there is a way how to see logs, who stopped fan?

**Comment by shal** [comment]
@kleuter solved, I deleted few strange programs, reinstalled "Macs Fan Control", now it works.

**Comment by kleuter** [comment]
Which strange programs? 😄

**Comment by shal** [comment]
Actually there were:
- Clean my mac X
- XQuartz
- VisualRouteLite
