### ISSUE TITLE
Fan control broken on bootcamp if macs fan control used.

### ISSUE THREAD

**Issue by MacDragon** [crystalidea/macs-fan-control#119]
It appears that if macs fan control is used with custom fan control on mac os on T2 equipped 2018 model that on a reboot into bootcamp windows fan control is completely broken, with fans always remaining on lowest 2000 rpm speed. Setting back to auto fan control before reboot resumes normal behavious.

Workaround would presumably be to reset fan control to automatic on shutdown if possible?

**Comment by kleuter** [comment]
https://github.com/crystalidea/macs-fan-control/issues/80
