### ISSUE TITLE
Upgrade alert can damage systems

### ISSUE THREAD

**Issue by richthegeek** [crystalidea/macs-fan-control#121]
The "new version is available, please update" window as currently designed prevents the app from starting automatically and may be missed by the user. As a result of this, the system can run fanless until it overheats, causing unneccesary wear and potentially damage to components.

Recommend a change of behavior to simply start the application normally and then display an update chime, return fan control to the system, or at least start fans under Automatic Control mode if an update is available.

Current behavior seems like it is in the interest of selling the application than actual concern for the user.

**Comment by kleuter** [comment]
It's already fixed in 1.4.12, no upgrade alert is there. 
https://www.crystalidea.com/macs-fan-control/release-notes
