### ISSUE TITLE
Randomly quitting since Mojave update

### ISSUE THREAD

**Issue by tenko23** [crystalidea/macs-fan-control#122]
Copy of error log below... has been randomly quitting daily since the upgrade to Mojave ;o .  I don't remember seeing errors in the log after the previous random quit, but I could be wrong ;o .  A little frustrating ;p ~

![screen shot 2018-10-08 at 12 32 54 pm](https://user-images.githubusercontent.com/34230416/46625439-a1802f00-caf9-11e8-86a1-abbeafab55bb.jpg)

[specs.txt](https://github.com/crystalidea/macs-fan-control/files/2457069/specs.txt)

[crash log.zip](https://github.com/crystalidea/macs-fan-control/files/2457156/crash.log.zip)

**Comment by kleuter** [comment]
Does restarting of the app help?

**Comment by kleuter** [comment]
Can you please also find the crash log in the Console (Utilities->Console) app?

**Comment by tenko23** [comment]
Well, when it crashes, I have to start it back up again... so I can't technically say that I've restarted it, since it quits on it's own ;o (I just start it back up ;p ).  In the past, it's run 24/7 just fine.

Anywho, here's the crash log from Console - one of quite a few (many):

[crash log.txt](https://github.com/crystalidea/macs-fan-control/files/2457461/crash.log.txt)

**Comment by JohnD0406** [comment]
I'm having the same issue, which is making me nervous.  Macs Fan Control v1.4.12, Mohave (release).  Seems to just quit randomly, about daily.  Fans continue running at the speed they were running when the app quit.  I can re-launch the app with no problems, and all fans adjust speed accordingly.

**Comment by kleuter** [comment]
@JohnD0406 can also post a crash report, please?

**Comment by JohnD0406** [comment]
I assume you're looking for the crash reports from console (~/Library/Logs/DiagnosticReports) - there's a report for every crash.  I'll attach the latest one.

[MacsFanControl_2018-10-16-092944_Johns-Mac-Pro.crash.zip](https://github.com/crystalidea/macs-fan-control/files/2488336/MacsFanControl_2018-10-16-092944_Johns-Mac-Pro.crash.zip)

Let me know if you need anything from MacsFanControl.log - it's too big to paste here (got the funny "Yowza, that's a big file" error).

**Comment by JohnD0406** [comment]
Any progress in figuring out the daily crashing issue on Mojave?  Need more crash logs?  I have quite a few by now - pretty much once every day.

**Comment by tenko23** [comment]
Agreed with the above question also - I need this software to keep my processor-upgraded Mac Pro cooled ;o ~

**Comment by kleuter** [comment]
Sorry, guys, not yet. The next beta version must have improvements on that. I'll keep you notified

**Comment by Tenzian** [comment]
Some more crash logs for the same issue, if it helps:

[Crash Logs.zip](https://github.com/crystalidea/macs-fan-control/files/2559012/Crash.Logs.zip)

**Comment by Careless** [comment]
Getting the same problem since Mojave update. I'll see if I can get a crash log too, but I usually notice the fan sound is different when I wake up because the app closed sometime during my slumber.

**Comment by kleuter** [comment]
Guys, please try the new version 1.5 beta which has lots of improvements, I hope this crash if fixed.
https://github.com/crystalidea/macs-fan-control/issues/116

**Comment by tenko23** [comment]
Been running great on my Mac Pro as well!

**Comment by kleuter** [comment]
Happy to hear that!

**Comment by arekm** [comment]
Will the fix get backported to 1.4? I'm getting crashes here (1.4.12).

**Comment by alexharries** [comment]
Same problem for me on latest stable Mac build on Mojave - have installed the Beta which fingers crossed will solve the issue. Thanks for all your work on this project, Kleuter :)

**Comment by kleuter** [comment]
> Will the fix get backported to 1.4? I'm getting crashes here (1.4.12).
Sorry no, have to wait for 1.5 official release

**Comment by JohnD0406** [comment]
Happy to report that since installing 1.5 beta, not a single crash! However, there *may* be a memory leak - my only recent observation was the app using 3.5GB of RAM. I have 96GB, and rarely reboot, so could be a slow leak. After I watch this more closely, I'll relay findings in a new post.

**Comment by paul-bv** [comment]
The issue is still there on MBP 2018. any idea when is the 1.5 version going to be released? Thanks!

**Comment by kleuter** [comment]
Couple of days
