### ISSUE TITLE
Macs fan control

### ISSUE THREAD

**Issue by dguest16** [crystalidea/macs-fan-control#124]
Macs fan control doesn't seem to be able to find any fans.  It is a hackintosh.. Not sure what else I can provide.
Macs Fan Control 1.4.12
iMac14,2
CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz [100]
GPU: NVIDIA GeForce GTX 960
macOS 10.12.6

Fans:

TempSensors:

Disk drives:
SanDisk SDSSDA240G - 40
ST2000DM001-1CH164 - 36
WDC WD40EFRX-68WT0N0 - 45
ST4000DM000-2AE166 - 37

**Comment by Murmur2k** [comment]
I got it working under Mojave.. what motherboard do you have? Have you installed the below kext to expose the sensors/fans?

FakeSMC_ACPISensors.kext
FakeSMC_CPUSensors.kext
FakeSMC_GPUSensors.kext
FakeSMC_LPCSensors.kext
FakeSMC_SMMSensors.kext
FakeSMC.kext

**Comment by kleuter** [comment]
The app is not currently compatible with hackinstosh.
https://github.com/crystalidea/macs-fan-control/issues/49
