### ISSUE TITLE
[MacPro5,1] Dual CPU Mac Pro BoostB not showing.

### ISSUE THREAD

**Issue by reservoirdogs617** [crystalidea/macs-fan-control#13]
I have a 2009 Mac Pro dual socket running 5,1 firmware with dual 6 core Xeons. In MFC only "BoostA" shows up as being able to set fan speed. "BoostB" is not shown anywhere. When I look with something like iStat Menus both "Boost 1" and "Boost 2" show up and detect fan speed. Boost 1 is showing the speed I requested in MFC, but Boost 2 is showing default fan speed. 
I've tried deleting and reinstalling MFC, but the issue remains. Is there something I can do to fix this?
Thanks,

**Comment by kleuter** [comment]
Please run this [tool](https://www.crystalidea.com/downloads/smc.zip) in your Terminal.

`$./smc -l > smc_dump.txt`

and send us the resulting __smc_dump.txt__ file.

**Comment by reservoirdogs617** [comment]
Thanks!
Running that first script in the terminal, then restarting the computer cleared my control setting but brought both BoostA and BoostB into the "available fans:" screen. All seems to be working now. Thanks again.

**Comment by interzone826** [comment]
I'd like to know where the "BoostA" fan is located, if anyone can help with that. Running 2012 Mac Pro tower.
