### ISSUE TITLE
Cannot control fan speed with macOS installed on external HDD(SDD)

### ISSUE THREAD

**Issue by sgamsterdam** [crystalidea/macs-fan-control#130]
Late 2012 21.5inch iMac, 2.9 GHz intel core i5. macOS Mojave. OS installed on external SDD (Angelbird SSD2Go 512GB, connected via USB).

Macs Fan Control has never worked, neither with previous macOS. I tried both set constant speed, and sensor based (ambient, CPU cores, etc). Periodically the fan speed goes up to about 5000, and then returns to normal speed. No clear trigger discernible. 

I have googled for many hours and tried several apps but nothing worked. SMC reset. Please help I would love to get rid of this issue :)

![screenshot 2018-10-20 at 12 53 31 pm](https://user-images.githubusercontent.com/44316668/47254813-345c8a00-d467-11e8-80a3-71236809c2c6.png)
![screenshot 2018-10-20 at 12 54 38 pm](https://user-images.githubusercontent.com/44316668/47254824-535b1c00-d467-11e8-9721-68adbe440963.png)

Macs Fan Control 1.4.12
iMac13,1
CPU: Intel(R) Core(TM) i5-3470S CPU @ 2.90GHz [100]
GPU: Intel HD Graphics 4000 [active], NVIDIA GeForce GT 650M
macOS 10.14.0

Fans:
Main-min{1400}curr{4878}max{2800}mode{2,TA0p,25,33}

TempSensors:
TA0P () - 3.625, 3.625
TA0V () - 20.0078, 20.0078
TA0p (Ambient) - 23.625, 23.625
TC0E () - 192.332, 192.332
TC0F () - 194.004, 194.004
TC0J () - 1.67188, 1.67188
TC0P () - 34.125, 34.125
TC0T () - 255.984, 255.984
TC0c (CPU Core 1) - 36, 36
TC0p (CPU Proximity) - 34.125, 34.125
TC1c (CPU Core 2) - 31, 31
TC2c (CPU Core 3) - 42, 42
TC3c (CPU Core 4) - 30, 30
TCGc (GPU PECI) - 42, 42
TCSc () - 32, 32
TCXR () - 194.359, 194.359
TCXc (CPU PECI) - 41.3594, 41.3594
TCXr () - 194.359, 194.359
TG0D () - 33, 33
TG0E () - 33.4414, 33.4414
TG0F () - 34.0898, 34.0898
TG0J () - 0.648438, 0.648438
TG0T () - 255.973, 255.973
TG0d (GPU Diode) - 27, 27
TG0p (GPU Proximity) - 30, 30
TH0A () - 129, 129
TH0B () - 129, 129
TH0C () - 129, 129
TH0F () - 129, 129
TH0O () - 249, 249
TH0P () - 249, 249
TH0R () - 129, 129
TH0a () - 129, 129
TH0b () - 129, 129
TH0c () - 129, 129
TH1A () - 129, 129
TH1B () - 129, 129
TH1C () - 129, 129
TH1F () - 129, 129
TH1O () - 9, 9
TH1P () - 129, 129
TH1R () - 129, 129
TH1a () - 129, 129
TH1b () - 129, 129
TH1c () - 129, 129
TL0P () - 13.7266, 13.7266
TL0p (LCD proximity) - 29.8125, 29.8125
TL1P () - 30.375, 30.375
TL1V () - 28.6211, 28.6211
TL1p (LCD Proximity 2) - 30.375, 30.375
TL1v () - 28.625, 28.625
TM0P () - 30.625, 30.625
TM0V () - 34.5, 34.5
TM0p (Memory Proximity) - 30.625, 30.625
TMXP () - 30.625, 30.625
TPCD (Platform Controller Hub Die) - 46, 46
TS0V () - 26.707, 26.707
Tb0P () - 36.625, 36.625
Tb0p () - 36.625, 36.625
Tm0P () - 31.125, 31.125
Tm0p () - 31.125, 31.125
Tp2F () - 29.5938, 29.5938
Tp2H () - 29.625, 29.625
Tp2h () - 29.625, 29.625

Disk drives:
APPLE HDD HTS541010A9E662 - 27
 - 45

**Comment by kleuter** [comment]
Please try the beta version, it has an option in Preferences to disable polling external drives
https://github.com/crystalidea/macs-fan-control/issues/116

**Comment by sgamsterdam** [comment]
Thank you, where could I find the beta version?

**Comment by kleuter** [comment]
https://github.com/crystalidea/macs-fan-control/issues/116
https://www.crystalidea.com/downloads/macsfancontrol_beta.zip
