### ISSUE TITLE
do not use flags for languages

### ISSUE THREAD

**Issue by wbolster** [crystalidea/macs-fan-control#134]
hi, thanks for this tool!

that said, please stop using flags for language selection. i find it mildly annoying to have to choose a flag for a country i am not affiliated with only to have a tool show up in my preferred language.  (also, why not just use the system language and remove the configuration?)

flags are for geographical/geopolitical entities, not for human languages. see for more info:

http://www.flagsarenotlanguages.com/blog/why-flags-do-not-represent-language/

**Comment by kleuter** [comment]
I understand. The app chooses system language on the first start. I'll consider this as improvement if it gets enough response, it will be implemented.

**Comment by wbolster** [comment]
thanks! i guess just removing the flag icons is enough (and the easiest change).

**Comment by kleuter** [comment]
No more flags in 1.5.3

**Comment by wbolster** [comment]
thank you!
