### ISSUE TITLE
Read-only mode: non-Apple file system detected (nullfs).  Please move...

### ISSUE THREAD

**Issue by NEMadman** [crystalidea/macs-fan-control#135]
Recently when I run Macs Fan Control on my Mac Pro running High Sierra I'm getting a dialog telling me to move Macs Fan Control to /Applications but it is in /Applications.  I searched github and the old Forum and didn't really find any solution to this issue, so I'm opening another.  Please find attached a screen shot.

Here is the "technical info" from the Diagnostics tab:

Macs Fan Control 1.4.12
MacPro5,1
CPU: Intel(R) Xeon(R) CPU X5690 @ 3.47GHz [100]
GPU: NVIDIA GeForce GTX 980 TI
macOS 10.13.6

Fans:
PCI-min{800}curr{904}max{4500}mode{0}
PS-min{600}curr{599}max{2800}mode{0}
EXHAUST-min{600}curr{599}max{2800}mode{0}
INTAKE-min{600}curr{599}max{2800}mode{0}
BOOSTA-min{800}curr{1113}max{5200}mode{0}
BOOSTB-min{800}curr{1114}max{5200}mode{0}

TempSensors:
TA0P (Ambient) - 30.6875, 30.6875
TCAC (CPU A core from PCECI) - 55.6562, 44.3438
TCAD (CPU A Diode) - 53.875, 53.875
TCAG () - 80, 80
TCAH (CPU A HeatSink) - 49.875, 49.875
TCAS () - 49.875, 49.875
TCBC (CPU B core from PCECI) - 42.0156, 57.9844
TCBD (CPU B Diode) - 45, 45
TCBG () - 80, 80
TCBH (CPU B HeatSink) - 40.5, 40.5
TCBS () - 40.5, 40.5
TH1F () - 32.375, 32.375
TH1P (Drive Bay 0) - 32.375, 32.375
TH1V () - 36.6211, 36.6211
TH2F () - 34.5508, 34.5508
TH2P (Drive Bay 1) - 34.5, 34.5
TH2V () - 32.707, 32.707
TH3F () - 34.2539, 34.2539
TH3P (Drive Bay 2) - 34.25, 34.25
TH3V () - 33.9648, 33.9648
TH4F () - 35.7969, 35.7969
TH4P (Drive Bay 3) - 35.875, 35.875
TH4V () - 39.9648, 39.9648
THPS () - 39.9648, 39.9648
THTG () - 58, 58
TM1P (DIMM Proximity 1) - 41.625, 41.625
TM2P (DIMM Proximity 2) - 43.625, 43.625
TM3P (DIMM Proximity 3) - 46.125, 46.125
TM4P (DIMM Proximity 4) - 46, 46
TM5P (DIMM Proximity 5) - 45.375, 45.375
TM6P (DIMM Proximity 6) - 48.5, 48.5
TM7P (DIMM Proximity 7) - 41.75, 41.75
TM8P (DIMM Proximity 8) - 33, 33
TMA1 () - 46.25, 46.25
TMA2 () - 48.75, 48.75
TMA3 () - 50.25, 50.25
TMA4 () - 51.4375, 51.4375
TMB1 () - 39.5, 39.5
TMB2 () - 41.0625, 41.0625
TMB3 () - 40.75, 40.75
TMB4 () - 39.5, 39.5
TMHS () - 51.4375, 51.4375
TMLS () - 39.5, 39.5
TMPS () - 51.4375, 51.4375
TMPV () - 46.7539, 46.7539
TMTG () - 75, 75
TN0D (IOH Diode) - 74.625, 74.625
TN0H (IOH HeatSink) - 60.875, 60.875
TNTG () - 65, 65
Te1F () - 129, 129
Te1P (PCIE Ambient) - 38.875, 38.875
Te1S () - 129, 129
Te2F () - 129, 129
Te2S () - 129, 129
Te3F () - 129, 129
Te3S () - 129, 129
Te4F () - 129, 129
Te4S () - 129, 129
Te5F () - 129, 129
Te5S () - 129, 129
TeGG () - 85, 85
TeGP () - 0, 0
TeRG () - 60, 60
TeRP () - 0, 0
Tp0C (PSMI Supply AC/DC Supply 1) - 50.2812, 50.2812
Tp1C (PSMI Supply AC/DC Supply 2) - 48.4219, 48.4219
TpPS () - 50.2812, 50.2812
TpTG () - 90, 90

Disk drives:
Crucial_CT1050MX300SSD1 - 26
WDC WD1001FALS-41K1B0 - 42
ST3000NM0033-9ZM178 - 40
Hitachi HDS721010CLA332 - 37

This is the output from diskutil list for the OS installation drive:

/dev/disk2 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +1.1 TB     disk2
                                 Physical Store disk1s2
   1:                APFS Volume HSSSD                   148.7 GB   disk2s1
   2:                APFS Volume Preboot                 74.9 MB    disk2s2
   3:                APFS Volume Recovery                1.5 GB     disk2s3
   4:                APFS Volume VM                      20.5 KB    disk2s4

![screen shot 2018-11-05 at 7 55 17 pm](https://user-images.githubusercontent.com/23486168/48036323-ce922280-e135-11e8-8aa9-eba58854beb6.png)

**Comment by kleuter** [comment]
@NEMadman

This is strange. Please try the beta version
https://github.com/crystalidea/macs-fan-control/issues/116

**Comment by dardo82** [comment]
I’m having that same problem,any new fix for that?

**Comment by kleuter** [comment]
Please try the beta version
#116

**Comment by dardo82** [comment]
Where I download it? 🤔

**Comment by kleuter** [comment]
https://www.crystalidea.com/downloads/macsfancontrol_beta.zip
