### ISSUE TITLE
*Minimum* Fan Speed Rather than Constant Fan Speed

### ISSUE THREAD

**Issue by skhub1** [crystalidea/macs-fan-control#136]
When using Macs Fan Control and the ambient temperature gets hot (like it did where I live today ... 40 degrees celsius plus), I would like the fan speed to automatically rise to take into account the higher ambient temperature, and return to the constant speed I set when things cool down.

 SMC Fan Control use do to this ... it was it's best feature!

I would like to set both fans on my 2018 MBP Core i9 to 3000RPM, but have the system raise that amount when it needs to - to protect the computer. If it can't the MacBook gets extremely hot, and if I'm not working at it, I'm not likely to notice. This would certainly result in damage ... may even melt the keys!!

**Comment by STGitUser** [comment]
Agreed, having MFC provide this kind of "adaptive" control over the normal Apple thermal scheme would be great.  The Apple thermal controls are like most things Apple, they aren't designed to be the best possible thermal approach they are designed to be the least audible - form over function.  If MFC could simply limit the lower end of the Apple control scheme it would result in an overall thermal improvement without having to worry about a constant speed being inadequate for high ambient or high load situations.

**Comment by STGitUser** [comment]
Okay, forget that suggestion.  Just use the "Sensor-based" control option in MFC using something like the CPU Diode as the sensor.  I have mine tuned to start increasing fan speed 60 C with a max temp of 85 C.  This results in a much more aggressive cooling profile than the normal Mac OS approach but it's still nice and quiet at low temps.  Works great!

**Comment by Gakkienl** [comment]
I would like to have a minimum speed as well. My new mini defaults to a very low RPM and I would like to be able to say set it's default RPM to 2800 and then set the two thresholds for when the fan will increase (from that min value) and for the max temperature!

Thanks for an otherwise awesome app!

**Comment by donluca** [comment]
Same here, I'd like to set a minimum value to the fans and then let SMC handle it normally.

I used SMC fan control but it does kind of funny things from time to time and I'd prefer a more trusty software.

**Comment by kleuter** [comment]
https://github.com/crystalidea/macs-fan-control/issues/1
