### ISSUE TITLE
Audio Dropouts, pops and clicks on Focusrite Audio Interface with MFC running

### ISSUE THREAD

**Issue by Goose7** [crystalidea/macs-fan-control#140]
![screen shot 2018-11-22 at 5 44 41 pm](https://user-images.githubusercontent.com/9331773/48926117-d238df80-ee7f-11e8-8d44-90607f6c5f36.png)

It took me over a week of testing to narrow this down, but it looks like MFC is the cause of significant audio dropouts and other pops and clicks when it is running alongside my pro audio hardware/software.

I am using a brand new 2018 Mac Mini with the top of the line i7 8700b CPU and 32GB of RAM to run Logic Pro X and a few related apps in my recording studio.  When MFC is running and monitoring the CPU PECI the audio is majorly impacted with these random drop outs, Pops and Clicks.  We confirmed the issue using TWO brand new Focusrite Clarett 2Pre interfaces.  

These are $500.00 PRO units designed to run on Thunderbolt 3.  Focusrite was kind enough to supply an additional brand new unit to rule out their hardware as the cause.

MFC does a wonderful job of keeping the 8700b CPU cool when running all of my various software.  Without it running, temps are hovering around 85C.  With it on and responding to the CPU PECI sensor, the fan is ramped up to 4000 RPM and CPU temps are way down in the mid 50C range.

Do you have any suggestions on what can be done?  I would prefer to keep using MFC, but at the moment it is impossible due to the major impacts the app is wreaking on the audio channel of both the Mac Mini and the Focusrite Clarett 2Pre.

Thanks in advance.

**Comment by kleuter** [comment]
@Goose7

Can you please try to use the beta version, it has an option to disable polling of external USB drives:
https://github.com/crystalidea/macs-fan-control/issues/116

**Comment by Goose7** [comment]
Sure!

I will give this one a try and get back to you later today.

Thanks for the help/info!

Cheers.

[]Rick.
_____________________
Goldengoose7
goldengoose7@gmail.com

On Nov 26, 2018, at 6:56 AM, Kleuter <notifications@github.com> wrote:

@Goose7 <https://github.com/Goose7>
Can you please try to use the beta version, it has an option to disable polling of external USB drives:
#116 <https://github.com/crystalidea/macs-fan-control/issues/116>

**Comment by Goose7** [comment]
I can’t seem to get the BETA version to run.  ??

When I download it and then click on the App after unzipping it, I am not prompted to move MFC to my user/applications folder like the release version does.  If I move it there manually while also adding it to my Login Items, nothing happens after restart.

When the system comes back up the speed and temp is not being displayed in the menu bar, and as such no apparent way to access the application’s settings.  If I click on the app directly from inside the Applications folder nothing happens.

If I go back to the release version and repeat all the above steps, everything works as before.

What am I missing here?

Thanks in advance.

**Comment by kleuter** [comment]
You must replace the release version with the beta.

**Comment by Goose7** [comment]
That is what I did first thing.  When I did that, I get prompted by the OS to replace the existing file, which I do, but that’s where it ends.

The app never shows up on the menu bar and I am never prompted to enter my password like you always are with the release version.  When I click on the actual app from inside my user/Applications folder I see the open animation but nothing else.

The app doesn’t open, nor does it ever appear on the menu bar.  I tried a restart and even a full shutdown restart but it never works.

If I go back to the release version, it all plays out normally and when I click on the app I am prompted to enter my password, and after that the app pops up and it also gets added to the menu bar.

I have tried this process 5 times now and the results are always the same.  The Beta refuses to run on my system. Yet when I drop in the release version everything works.

Any other suggestions?

**Comment by kleuter** [comment]
Yes it crashes on Mojave, I'll make a new fixed build soon. Sorry for that

**Comment by Goose7** [comment]
That would be great.  I will look forward to having access to that.  :o)

Sorry for not getting back to you.  The beta was obviously not working on my system, and I saw no point in beating a dead horse.

Glad you were able to test it and cofirm that it indeed does not run on Mojave.
_____________________
Goldengoose7
goldengoose7@gmail.com

On Nov 30, 2018, at 12:12 PM, Kleuter <notifications@github.com> wrote:

Yes it crashes on Mojave, I'll make a new fixed build soon. Sorry for that

**Comment by kleuter** [comment]
The new beta is here, must be working fine:
https://www.crystalidea.com/downloads/macsfancontrol_beta.zip

**Comment by someofthem98** [comment]
Dear @kleuter ,
I have the same issue with a Mac mini 2018 with same specs of @Goose7 .
I have a Focusrite Forte with USB 2.0.
I tried the latest beta release, without success.
Any help would be so appreciated.
Thanks

**Comment by solariz9** [comment]
I have Yamaha AG06 with USB 2.0 and last MFC beta on my MacBook Pro 2018.
I have sound problems like drop outs, pops and clicks.

**Comment by kleuter** [comment]
New version 1.5 has an option in preferences to disable polling of hard drives, it must help you
