### ISSUE TITLE
Can i just stop the fan

### ISSUE THREAD

**Issue by marisa777** [crystalidea/macs-fan-control#141]
I use macs-fans-control in bootcamp,
my computer is imac.
i set the fan to min RPM the1200,
but it is still noisy.
i find that i need to stop the fan, set the RPM to 0.  it will be OK my cpu is always below 40℃
Please help, can you allow me set the RPM to 0? thanks.

**Comment by kleuter** [comment]
No, it's not possible and could be very dangerous.
