### ISSUE TITLE
Cannot enter Constant Fan Speed without pressing arrow keys

### ISSUE THREAD

**Issue by Careless** [crystalidea/macs-fan-control#143]
For some reason, when entering the constant fan speed of any fan circuit I choose, I have to press the arrow-right key after each number. 

For example, if I want a fan to hold 900 rpm, If I type 9 , 0 , 0 every new number key I press rewrites the previous number entered. It looks like the input field is highlighting the numbers after they are input, so any subsequent number pressed on the keyboard will overwrite the previous one.

The only way I've managed to set fan speed was to press 9 , right-arrow , 0 , right-arrow , 0 , enter.
The action of pressing the right-arrow key is to deselect the number that was input so that it's not overwritten.

I don't change the speed much, but it is an annoyance. As far as I know, It's got nothing to do with my keyboard settings or numlock or whatever.

**Comment by kleuter** [comment]
This is very strange and it's actually the first complain that we had for years. Just checked on my mac, works fine when entering fan speed using keyboard.
