### ISSUE TITLE
Fan min and max speeds incorrect

### ISSUE THREAD

**Issue by fcollingwood** [crystalidea/macs-fan-control#149]
The MBP8,3 has a minimum fan speed of 2000 and a maximum of 6200. MFC has a min of 5500 and a max of 5800.

This results in a machine that is too noisy all of the time. 

My reason for trying this out is that the default temp/speed curve for my machine results in it hitting temps of over 80C at times, and I would like the fans to ramp up earlier when required, and be quiet when the temps are OK. However, the machine is too noisy all of the time, so I don't consider MFC to be a viable solution

![screen shot 2019-01-16 at 1 43 14 pm](https://user-images.githubusercontent.com/37040349/51219363-7a0cee00-1995-11e9-9bd9-e9aff6481b37.png)

**Comment by kleuter** [comment]
Min/max speeds can be different and controlled by SMC
