### ISSUE TITLE
Custom mode of Macs Fan makes CPU run in low speed

### ISSUE THREAD

**Issue by tailevn** [crystalidea/macs-fan-control#151]
Hi Macs Fan Team,

I found that the Custom mode of Macs Fan makes CPU run in low speed. The CPU speed will drop down to minimum speed after few minutes run in heavy duty (render videos). Please check again and fix this one soon.
I am using Macs Fan Control 1.4.11 Build 563
Macbook pro early 2013
OS: Window 10 64bit.

Thank you!

**Comment by kleuter** [comment]
It's normal for modern CPUs to drop its frequencies when not under load. Not related to fan control
