### ISSUE TITLE
No fans detected

### ISSUE THREAD

**Issue by florisaegidius** [crystalidea/macs-fan-control#153]
This is on a Macbook Pro mid 2012 2,3 i7 Mojave 10.14.3
[MacsFanControl.log](https://github.com/crystalidea/macs-fan-control/files/2864891/MacsFanControl.log)
<img width="889" alt="screenshot 2019-02-14 at 12 50 48" src="https://user-images.githubusercontent.com/47631726/52786088-32dc5080-305a-11e9-87e7-c7dd03bd939c.png">

thanks

**Comment by kleuter** [comment]
https://github.com/crystalidea/macs-fan-control/issues/15
