### ISSUE TITLE
Menubar Icon position

### ISSUE THREAD

**Issue by MichaelHolmesAus** [crystalidea/macs-fan-control#159]
When starting Mac OS "Macs-Fan-Control" menubar icon always moves to end despite manually rearranging it every time.
I'm not sure why it's only Macs-Fan-Control that has this behaviour? all my other menubar icons automatically adjust to where I last positioned them.

I just wish I could make Macs-Fan-Control menubar icon automatically position where I last left it.

**Comment by Marcos-marpin** [comment]
Same is happening to me. Did you find any solution?

**Comment by kleuter** [comment]
Do you experience the same issue with 1.5.1?

**Comment by kleuter** [comment]
No longer and issue
