### ISSUE TITLE
If I click on "preferences" your program is entering in a loop

### ISSUE THREAD

**Issue by courtox** [crystalidea/macs-fan-control#16]
Hi,
thank you for your work, without your program my old Macbookpro middle 2010 is entering a GPU kernel panic, each time an application is using the extend graphic unit. So I need your program working fine.
I've mad the last update of your code ' Fan Control 1.4.9  Macbook Pro 6.2'
My system is: 
 OS/X El Capitan 10.11.6 (15G18013)
MacBook Pro (15 pouces, mi-2010)
Processor 2,66 GHz Intel Core i7
Memory 8 Go 1067 MHz DDR3
GPU Intel HD Graphics 288 Mo

Your program start well, then start controlling the Fan, but doesn't work. If the temperature is increasing the FAn doesn't change the speed. If I try to click the "prefernces" button, no answer, the mouse cursor turns into a colorful spinning disc, you program is in a loop and refuse to stop. I have to power off then on my Mac.

![cap 2018-01-18 a 14 28 28](https://user-images.githubusercontent.com/8945546/35100846-908f4912-fc5d-11e7-92e5-48d820f0ce85.png)

**Comment by courtox** [comment]
![cap 2018-01-18 a 14 42 04](https://user-images.githubusercontent.com/8945546/35100946-f8b2a20a-fc5d-11e7-9bb6-ca97abacef73.png)
If I ask to get 
![cap 2018-01-18 a 14 42 04](https://user-images.githubusercontent.com/8945546/35100940-ef20186c-fc5d-11e7-8e03-a970a9e35377.png)
the list of working tasks, then your program is in red with the nota: "Doesn't respond"

**Comment by courtox** [comment]
Program is using between 1.3 to 1.8  % CPU
![cap 2018-01-18 a 14 44 37](https://user-images.githubusercontent.com/8945546/35101012-43d42ac4-fc5e-11e7-83ee-47e6005ed3f9.png)

**Comment by kleuter** [comment]
Did you app work before? Were you able to open the Preferences?

Please try the following in the Terminal:

```
#!/bin/bash

killall MacsFanControl
rm ~/Library/Preferences/com.crystalidea.macsfancontrol.plist
killall -u `id -u -n` cfprefsd
```

**Comment by courtox** [comment]
Yes I use the application since 3 years, no trouble until this week

The killall is working fine
kill -9 752
was working also, the PID of the program was 752 as you can see on the sreen shots

**Comment by courtox** [comment]
After my kill )9 752, the application doesn't accept to start because it is da
![cap 2018-01-18 a 14 56 09](https://user-images.githubusercontent.com/8945546/35101437-d7b357d2-fc5f-11e7-849e-af4cde28ac14.png)
maged

**Comment by kleuter** [comment]
Remove all instances of the app from your /Applications folder and reinstall it.

**Comment by courtox** [comment]
After remove and install all is clean and clear. Working fine
Thank you so much for this famous tool
