### ISSUE TITLE
Seems like MacFanControl causes Kernel Panic

### ISSUE THREAD

**Issue by Thor-x86** [crystalidea/macs-fan-control#160]
> 26. | BSD process name corresponding to current thread: MacsFanControl

Hi there, my mac just got Kernel Panic. After rebooting, it prompts a message with kernel log ([this link](https://pastebin.com/EvidWhkX)). I suspect why on earth MacFanControl trying to modify the memory 🤔 Thank you!

**Comment by kleuter** [comment]
> BSD process name corresponding to current thread: MacsFanControl
It  doesn't mean that it tryes to modify the memory. 

There's no evidence of the claim that MFC causes kernel panic. Actually it can't do it.
