### ISSUE TITLE
Constant disk write while the app runs

### ISSUE THREAD

**Issue by passatgt** [crystalidea/macs-fan-control#161]
If the Macs Fan Control app is running, i can hear my HDD working constantly, like a clock ticking. If i close the app the noise is gone. I'm guessing it's writing something constantly to the disk? It's in sync with the RPM and temperature values updating in the app. Tried to record a video but my phone can't pick it up properly the sound. 

![image](https://user-images.githubusercontent.com/43415/55267081-6aa4fd80-5280-11e9-96b5-131d70c196e7.png)

Macs Fan Control 1.4.12
iMac12,2
CPU: Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz [100]
GPU: Intel HD Graphics 3000 [active], NVIDIA GeForce GTX 780M
macOS 10.14.2

Fans:
ODD-min{1150}curr{1149}max{2500}mode{0}
HDD-min{1100}curr{1117}max{5500}mode{0}
CPU-min{940}curr{939}max{2100}mode{0}

TempSensors:
TA0P () - 23.4219, 23.4219
TA0V () - 23.5938, 23.5938
TA0p (Ambient) - 28.75, 28.75
TC0H () - 37.875, 37.875
TC0P () - 41.25, 41.25
TC0c (CPU Core 1) - 41, 41
TC0h (CPU Heatsink) - 37.875, 37.875
TC0p (CPU Proximity) - 41.25, 41.25
TC1c (CPU Core 2) - 40, 40
TC2c (CPU Core 3) - 42, 42
TC3c (CPU Core 4) - 41, 41
TCGc (GPU PECI) - 42, 42
TCSc () - 32, 32
TCXc (CPU PECI) - 42.8594, 42.8594
TG0D () - 129, 129
TG0H () - 43.375, 43.375
TG0d () - 129, 129
TG0h (GPU Heatsink) - 43.375, 43.375
TG0p () - 129, 129
TH0O () - 249, 249
TH1O () - 249, 249
TL0P () - 37.1641, 37.1641
TL0V () - 39.0195, 39.0195
TL0p (LCD proximity) - 50.3125, 50.3125
TL1P () - 43.25, 43.25
TL1V () - 36.7734, 36.7734
TL1p (LCD Proximity 2) - 43.25, 43.25
TL1v () - 36.832, 36.832
TL2V () - 42.6836, 42.6836
TLAV () - 42.6836, 42.6836
TLBV () - 39.2422, 39.2422
TLCV () - 39.0195, 39.0195
TO0P () - 39.125, 39.125
TO0p (Optical Drive) - 40.125, 40.125
TPCD (Platform Controller Hub Die) - 51, 51
TS0P () - 38, 38
TS0V () - 32.4766, 32.4766
TS0p () - 38, 38
TS2P () - 39.125, 39.125
TS2V () - 36.375, 36.375
TS2p () - 39.125, 39.125
Tm0P () - 41.75, 41.75
Tm0p () - 41.75, 41.75
Tp1P () - 51.875, 51.875
Tp1p () - 51.875, 51.875
Tp2H () - 58.875, 58.875
Tp2h () - 58.875, 58.875
Tp3H () - 51.125, 51.125
Tp3h (PSU Primary) - 51.125, 51.125

Disk drives:
ST31000528AS - 43
Samsung SSD 850 EVO 250GB - 38

**Comment by kleuter** [comment]
https://github.com/crystalidea/macs-fan-control/issues/116

**Comment by passatgt** [comment]
Hi! Thanks, I just installed the beta but i experience the same issue.

**Comment by kleuter** [comment]
Did you disable displaying of disk drives?
