### ISSUE TITLE
Increase menu bar font size

### ISSUE THREAD

**Issue by big610** [crystalidea/macs-fan-control#163]
Feature Request: Menu Bar Color & Size

Can you consider increasing the size of the Temperature Digit Font when added in Menubar display, equal to the size of your icon? It's hard to distinguish as the MFC Icon is larger than Temperature being displayed. If you need space, drop the C or F. We already know what we have chosen being either C or F.

Can you consider adding color to the Temperature Digit Font when added in the Menubar display? Example CPU Proximity,  Display Menu Bar Color: 65* C and below Green, 66* C above above Red?

**Comment by kleuter** [comment]
fixed in 1.5.1
