### ISSUE TITLE
macmini8,1 missing CPU cores and temperatures

### ISSUE THREAD

**Issue by trevoz** [crystalidea/macs-fan-control#165]
Apple Mac Mini 8,1 - i7 (6 cores)
macOS 10.14.4 (Mojave)

Temperatures for Core 1 and Cores 5 and 6 are missing. The missing Core 1 seems a definite bug, but the missing Cores 5 and 6 may be due to the base model being a four core i3. Note the i5 and i7 are both six core CPUs.

Attached: appshot, diagnostics text

![Screen Shot 2019-04-17 at 22 37 29](https://user-images.githubusercontent.com/13196674/56288161-7e49d280-6161-11e9-9394-7c0bb6c6e52b.png)

[macmini8,1.txt](https://github.com/crystalidea/macs-fan-control/files/3089592/macmini8.1.txt)

**Comment by kleuter** [comment]
It must be fixed in the 1.5 beta version
https://github.com/crystalidea/macs-fan-control/issues/116
