### ISSUE TITLE
No Fans Detected On This Computer

### ISSUE THREAD

**Issue by alecgaro** [crystalidea/macs-fan-control#167]
Hello I have downloaded the new version of Macs Fan Control, on my Macbook Pro 2018 running Bootcamp Windows 10. It is telling me no fans detected on this computer. Here are the 3 screenshots needed and also a text log of the diagnostics tab.

Macs Fan Control 1.4.12
MacBookPro15,3
CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz [100]
GPU: Radeon Pro Vega 20
Windows 10 x64

Fans:

TempSensors:

Disk drives:
APPLE SSD AP1024M

![capture1](https://user-images.githubusercontent.com/49883545/56527604-c28ef700-6502-11e9-8909-22b7e9cb8606.PNG)
![Capture2](https://user-images.githubusercontent.com/49883545/56527605-c3278d80-6502-11e9-9922-7d2e8a18ce47.PNG)
![Capture3](https://user-images.githubusercontent.com/49883545/56527608-c3c02400-6502-11e9-8c10-75b640887942.PNG)

**Comment by kleuter** [comment]
https://www.crystalidea.com/macs-fan-control/supported-models
