### ISSUE TITLE
Autostart keeps re enabling on windows

### ISSUE THREAD

**Issue by ditchcord** [crystalidea/macs-fan-control#169]
Whenever I disable auto-start minimized with system in preferences on the windows version (Boot camp) when I restart the application it re enables auto start for no reason

Macs Fan Control 1.4.12
MacBookPro12,1
CPU: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz [100]
GPU: Intel(R) Iris(TM) Graphics 6100
Windows 10 x64

Fans:
Right Side-min{1299}curr{3965}max{6199}mode{1,3910}

TempSensors:
TA0P (Ambient) - 43.375, 43.375
TB0T (Battery Max) - 39.0977, 39.0977
TB1T (Battery Sensor 1) - 39.0977, 39.0977
TB2T (Battery Sensor 2) - 36.6992, 36.6992
TBXT () - 39.0977, 39.0977
TC0C (CPU Core 1) - 70, 70
TC0E () - 67.2656, 67.2656
TC0F () - 68.4883, 68.4883
TC0P (CPU Proximity) - 57.875, 57.875
TC1C (CPU Core 2) - 69, 69
TCGC (GPU PECI) - 64, 64
TCSA () - 64, 64
TCXC (CPU PECI) - 63.9375, 63.9375
TH0A () - 41.625, 41.625
TH0B () - 41.625, 41.625
TH0C () - 42.625, 42.625
TH0F () - 214.625, 214.625
TH0R () - 214.625, 214.625
TH0V () - 42.8125, 42.8125
TH0a () - 41.625, 41.625
TH0b () - 41.625, 41.625
TH0c () - 42.625, 42.625
TH0x () - 42.625, 42.625
THSP () - 129, 129
TM0P (Memory Proximity) - 50.25, 50.25
TMLB () - 129, 129
TPCD (Platform Controller Hub Die) - 58, 58
TW0P () - 129, 129
Th1H (Heatsink Proximity) - 46.625, 46.625
Ts0P (Palm Rest) - 36, 36
Ts0S () - 43.1875, 43.1875
Ts1P () - 35.5, 35.5
Ts1S () - 42.9141, 42.9141
![Untitled](https://user-images.githubusercontent.com/50102243/56888964-df4da080-6aa7-11e9-8319-bd669bf514dd.png)

Ts2S () - 40.168, 40.168

Disk drives:
APPLE SSD SM0256G - 41.625

**Comment by kleuter** [comment]
Thanks, it's will be fixed in the next 1.5 update
