### ISSUE TITLE
Changing max fan speed

### ISSUE THREAD

**Issue by 20015jjw** [crystalidea/macs-fan-control#17]
My main reason for using this app is to limit the mac's fan speed during meeting so my laptop doesn't blow up during compiling when others are trying to focus. A feature like "allowing mac to keep it's old profile but we just cap the fan speed at a level so it doesn't get too loud". This way the fan speed can go down when there's no need to run at say 4000 rpm, but it only runs at 4000 rpm no matter how hot it gets. Thanks in advance.

**Comment by kleuter** [comment]
Looks like this feature request is overlapsed with https://github.com/crystalidea/macs-fan-control/issues/5
