### ISSUE TITLE
Administrator password required for MacFansControl 1.4.12 on iMac12,1

### ISSUE THREAD

**Issue by svanlancker** [crystalidea/macs-fan-control#170]
Administrator password required for MacFansControl 1.4.12 on iMac12,1
<img width="405" alt="Screen Shot 2019-05-04 at 6 29 36 PM" src="https://user-images.githubusercontent.com/50271997/57182053-4f3e9b00-6e9b-11e9-9db1-730a86c2ed78.png">

**Comment by kleuter** [comment]
Yes, the app currently works only with administrator privileges.
