### ISSUE TITLE
release a new version

### ISSUE THREAD

**Issue by irvin** [crystalidea/macs-fan-control#171]
It has been 9 months since the latest release and the diff had already contains [several new patches](https://github.com/crystalidea/macs-fan-control/compare/v1.4.12...master) that user can be benefit. Please consider release a new version to the latest feature.

**Comment by pandalion98** [comment]
@kleuter Maybe consider open-sourcing it instead of letting the software stagnate and die?

**Comment by kleuter** [comment]
https://github.com/crystalidea/macs-fan-control/issues/116
