### ISSUE TITLE
Deleting old versions of Macs Fan Control

### ISSUE THREAD

**Issue by sydmanz** [crystalidea/macs-fan-control#172]
![Macs Fan Screen shot](https://user-images.githubusercontent.com/50278290/57272041-e7c85b80-70e5-11e9-8149-d7b2854725c3.png)
![Macs Fan Preference Screen shot](https://user-images.githubusercontent.com/50278290/57272043-edbe3c80-70e5-11e9-8add-2ac5045894ef.png) 
![Macs Fan Control Error Message](https://user-images.githubusercontent.com/50278290/57272059-03336680-70e6-11e9-809b-a2d985a7ae01.png)

I upgraded my computer from MacBook Pro (10.6.8) to iMac (10.12) and the software was migrated via Migration Assistant. My old Mac Fan did not work on the new computer. The error message reads "This legacy version of Macs Fan Control is for 10.6 only. Please download the latest version for newer systems."

So I did and saw the above error warning (again) as per the attached screenshot. I complied. I got the same error warning, so I searched and found an old Macs Fan Control and deleted it.

Yet I still get this error message. Clearly there is another older version of the application lurking on my computer somewhere, but I cannot find it.

Could someone please advise me as to where this might be and what it might be named?

I have searched high and low for

**Comment by sydmanz** [comment]
Hi all,
I have found the other application. I attach a screenshot of both of them side by side.
Could someone please advise me as to which of these two is the wrong one for my system?

I am on an iMac, 10.12.6

I can see that one window suggests it is the "right" one, but the other looks so significantly different and also much more sophisticated in design that I am loath to delete one or the other before getting a more experienced piece of advice.

![Screen Shot 2019-05-08 at 12 36 47 PM](https://user-images.githubusercontent.com/50278290/57341537-eacb5680-718e-11e9-99e9-bbdf803760e6.png)

**Comment by kleuter** [comment]
https://www.crystalidea.com/blog/solving-imac-fan-noise-issue-after-hdd-replacement
