### ISSUE TITLE
Feature Request: Presets

### ISSUE THREAD

**Issue by aloysiu3** [crystalidea/macs-fan-control#176]
It would be great to have presets selectable from the status bar icon to set the fanspeed to a specific value or range!

**Comment by useamuse** [comment]
The only thing I really miss as well.

An app like this without presets is Amateur Hour.

To the dev: are you using your own product? If yes, are you not missing presets?

Thanks for all the work so far tho. XO

**Comment by kleuter** [comment]
Implemented in v1.5
