### ISSUE TITLE
crashes with illegal instruction on Mac Pro 5,1

### ISSUE THREAD

**Issue by proessner** [crystalidea/macs-fan-control#177]
MacsFanControl crashes suddenly with illegal instruction on Mac Pro 5,1 running Mojave. The crash report is attached
[MacsFanControl_2019-06-02-190722_Peters-Mac-Pro-4.txt](https://github.com/crystalidea/macs-fan-control/files/3247763/MacsFanControl_2019-06-02-190722_Peters-Mac-Pro-4.txt)

**Comment by kleuter** [comment]
Please try the beta version #116
