### ISSUE TITLE
Temperature Sensors List

### ISSUE THREAD

**Issue by yatooka** [crystalidea/macs-fan-control#179]
I apologize but I did not know where to start in getting this question answered.  If there is a different route I should take for such questions please let me know.

I have an 8-core Mac Pro 3,1. I would like to see an updated Temperature Sensors glossary. I like this application A LOT and it would be nice for example to know what "FBDIMM Riser A Regulator Area" is. Also, the CPU sensors that
![Screen Shot 2019-06-12 at 11 05 24 PM](https://user-images.githubusercontent.com/46953283/59400938-0e258a80-8d67-11e9-91b3-91a8ff86d2a6.png)
![Screen Shot 2019-06-12 at 11 05 33 PM](https://user-images.githubusercontent.com/46953283/59400939-0e258a80-8d67-11e9-8c99-2cca67f89c3d.png)

 it reports (A and B) each show a Core 0 and a Core 1 but not a Core 2 and Core 3 (like I assumed would appear; maybe I'm wrong).  Attached are few screenshots from the app showing some names that currently may not be on your Sensors glossary page.  Thank you.

**Comment by kleuter** [comment]
Unfortunately, SMC reports only first 2 cores.
