### ISSUE TITLE
Can't access to the auxiliary tool to custom fan speed

### ISSUE THREAD

**Issue by olivier3172** [crystalidea/macs-fan-control#182]
I installed MFC on my 2 differents Mac (Mac Mini 6,2 & Macbook Air 7,2) both on El Capitan and at startup it asked for my admin password to activate the custom fan speed but the answer is :
"Couldn't find the auxiliary tool"
![Capture d’écran 2019-06-24 à 12 56 10](https://user-images.githubusercontent.com/52159862/60013829-c44e7580-967f-11e9-92bd-d40c8653d77f.png)
What's wrong ?

**Comment by kleuter** [comment]
Improved and fixed in the latest update (1.5)
