### ISSUE TITLE
Accessing external RAID QuadX about once a second, loud audible sound each time. 

### ISSUE THREAD

**Issue by Digitalclips** [crystalidea/macs-fan-control#183]
Accessing external RAID QuadX about once a second, loud audible sound each time. Quit the Mac App the sound stops.  Is there a way to exclude it reading the RAID?

![Screen Shot 2019-06-24 at 9 57 54 AM](https://user-images.githubusercontent.com/15971887/60024848-8b55d700-9666-11e9-8899-1c34fec45156.png)

**Comment by kleuter** [comment]
New version 1.5 has an option in preferences to disable polling of hard drives, it must help you
