### ISSUE TITLE
Feature request: Battery mode vs Plug-in mode

### ISSUE THREAD

**Issue by zweedao** [crystalidea/macs-fan-control#187]
### Why do we need this
When my Mac is plugged-in, I want to maximize the fan speed to stay cool during high-performance work. However, when on battery, I want to lower the fan speed to save battery life. Right now I need to manually reset to automatic fan control whenever I switch to battery mode. That extends the battery life up to 3 hours more compared to keeping Macs Fan Control running! 

### What do we need
It will be awesome if I can preset a few fan speed profiles. Then Macs Fan Control can automatically switch to low-speed profile (or automatic control) in Battery Mode, vs. switching to high-speed profile in Plug-in Mode.

**Comment by kleuter** [comment]
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/50
