### ISSUE TITLE
Catalina: automatic menubar light and dark mode switching

### ISSUE THREAD

**Issue by Jarvis01Data** [crystalidea/macs-fan-control#189]
Using MacOS Catalina Beta 3, if switching from light to dark mode or vice versa, the icon will correctly go from black to white, yet this behaviour does not follow if the mode is changed automatically, such as the feature where at sunset the Mac will go from light to dark, the menubar icon will stay in the light theme. You can recreate this issue by during day time when auto mode will switch the theme to light, putting on dark mode and then switching back to auto which will make it light. Or during the night or evening by going on light mode and switching back to auto.

<img width="501" alt="Screenshot 2019-07-08 at 08 48 54" src="https://user-images.githubusercontent.com/12760963/60788531-3d100000-a15d-11e9-99c7-9cad88e38dfd.png">

**Comment by kleuter** [comment]
@Jarvis01Data @zhkong

can you please test the latest [beta](https://github.com/crystalidea/macs-fan-control/issues/218)?

**Comment by kleuter** [comment]
Please test with the [latest beta](https://github.com/crystalidea/macs-fan-control/issues/218)

**Comment by kleuter** [comment]
fixed in 1.5.1
