### ISSUE TITLE
Some items are missing in the language file.

### ISSUE THREAD

**Issue by AlaricGilbert** [crystalidea/macs-fan-control#191]
Hey, I'm going to contribute to make this translation better, but I found some items are missing in the language file.
For example, under Preferences - General
![image](https://user-images.githubusercontent.com/36405110/61133748-a2af1400-a4f0-11e9-8d0c-fc73682db09c.png)
is not listed in the language file. And in tray menu bar, 
![image](https://user-images.githubusercontent.com/36405110/61133886-e7d34600-a4f0-11e9-9747-6b8c377864ca.png)
And this I'm not sure wether it's a string can be localized or read from your computer:
![image](https://user-images.githubusercontent.com/36405110/61133960-16512100-a4f1-11e9-85ff-52676f3f66dd.png)

**Comment by kleuter** [comment]
https://www.crystalidea.com/macs-fan-control/translation
