### ISSUE TITLE
MacBook Pro 2019 “No fans detected on this computer"

### ISSUE THREAD

**Issue by DJY719254882** [crystalidea/macs-fan-control#193]
Macs Fan Control 1.4.12
MacBookPro15,3
CPU: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz [100]
GPU: Radeon Pro Vega 20
Windows 10 x64

Fans:

TempSensors:

Disk drives:
APPLE SSD AP1024M

**Comment by kleuter** [comment]
https://www.crystalidea.com/macs-fan-control/supported-models
https://www.crystalidea.com/blog/fan-control-on-apple-computers-with-t2-chip-on-windows-boot-camp
