### ISSUE TITLE
Hide on start up flag

### ISSUE THREAD

**Issue by traisjames** [crystalidea/macs-fan-control#194]
With MacFan crashing sometimes under Mojave I have created a lauchagent to autostart MacFan at boot and then restart the app when it crashes.  The code is
```plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>RunAtLoad</key>  
        <true/>  
        <key>KeepAlive</key>
        <true/>
        <key>Label</key>
        <string>MacFan.restart</string>
        <key>ProgramArguments</key>
        <array>
                <string>/Applications/Macs Fan Control.app/Contents/MacOS/MacsFanControl</string>
        </array>
</dict>
</plist>
```

Now after the line <string>/Applications/Macs Fan Control.app/Contents/MacOS/MacsFanControl</string>, I can add another string which are arguments passed to MacFan when launched.  Is there an argument I can run that which forces MacFan to start hidden to the system tray?  I have tried to find the config file that launches MacFan on startup but cannot find it.

**Comment by kleuter** [comment]
https://www.crystalidea.com/macs-fan-control/command-line
