### ISSUE TITLE
Battery Stopped Charging

### ISSUE THREAD

**Issue by BevInTX** [crystalidea/macs-fan-control#195]
I started using MFC a few days ago.  Today I used my MacBook Pro on battery and discovered that it was no longer charging.  I reset SMC and it is charging again.  Since fan control is also related to the SMC, I'm wondering whether MFC affects other SMC related hardware?  Or was this just a coincidence?

I don't want to use it again until I understand what is going on.

MFC 1.4.12
MacBookPro6,1
macOS High Sierra 10.13.6 (17G7024)

![07-19-2019](https://user-images.githubusercontent.com/9881946/61570378-cbd02700-aa51-11e9-89c3-5b174717caf3.png)

**Comment by kleuter** [comment]
It can't be related
