### ISSUE TITLE
no fans detected

### ISSUE THREAD

**Issue by regiscoutant** [crystalidea/macs-fan-control#196]
ATTENTION: All Issue reports should please contain a screenshot and the system Diagnostics text, as described [here](https://github.com/crystalidea/macs-fan-control/blob/master/.github/CONTRIBUTING.md)

**Comment by regiscoutant** [comment]
no fans detected on my macbook pro late 2011 (model 8,2)...
osx 10.11 = El Capitan
HD changed by an SSD.

latest mac fan control version: 1.4.12

![image](https://user-images.githubusercontent.com/53473949/62125819-7c4dee80-b2ce-11e9-833e-14c833e907a0.png)

![image](https://user-images.githubusercontent.com/53473949/62125872-a6071580-b2ce-11e9-9a67-5faa8fe9904c.png)

**Comment by regiscoutant** [comment]
i supposed no-one would treat if I close the issue ??

**Comment by kleuter** [comment]
SMC reset
