### ISSUE TITLE
Fan rpm raise up when I open Xcode 

### ISSUE THREAD

**Issue by escapeanaemia** [crystalidea/macs-fan-control#198]
<img width="819" alt="스크린샷 2019-08-05 오후 10 54 32" src="https://user-images.githubusercontent.com/19788090/62469841-141e7180-b7d4-11e9-8695-e73b5cf80937.png">
when I open the Xcode, suddenly fan spinning and rpm raise to the max. after 5 seconds it stops.
when I quit Macs Fan Control and open Xcode, it would not happen

**Comment by kleuter** [comment]
I don't see your fan settings, looks like they are pretty aggressive. Change them or revert to auto.
