### ISSUE TITLE
differing default temperatures for sensors

### ISSUE THREAD

**Issue by mauricev** [crystalidea/macs-fan-control#20]
I have two of the same Macs. The CPU PECI sensor on each Mac has different temperature ranges. How can that be?
![two macs two different sensor settings](https://user-images.githubusercontent.com/417110/35521139-fc2cff70-04e6-11e8-94ad-37e04f26227e.png)

**Comment by mauricev** [comment]
The differing settings seem to apply to every sensor not just the CPU PECI.

**Comment by kleuter** [comment]
It's OK, they are just proposed values (based on current values), don't count on them.
