### ISSUE TITLE
Settings not saved between app launches

### ISSUE THREAD

**Issue by AndreasAPOEL** [crystalidea/macs-fan-control#201]
If I use custom settings (such as sensor-based fan control) and then revert to "Auto" settings before closing the app, the custom settings selected are reset. Preferences selected are not being reset. 
<img width="871" alt="Screen Shot 2019-08-10 at 20 37 07" src="https://user-images.githubusercontent.com/53978756/62825135-99789c00-bbaf-11e9-8434-75a9d4b50103.png">
[MacsFanControl.txt](https://github.com/crystalidea/macs-fan-control/files/3489167/MacsFanControl.txt)

**Comment by kleuter** [comment]
Hi,

Are you running as administrator or limited account?

**Comment by AndreasAPOEL** [comment]
> Hi,
> 
> Are you running as administrator or limited account?

I'm using an admin user/account, I've not touched any settings/permissions. (I have read & write privileges)

Just to make sure the issue is clear:

- If I use custom sensor-based control & exit the app, next time I open it the settings previously selected will be saved. Only when I revert to Auto before exiting the app they'll be reset. 
- If I select some custom sensor-based values, then revert to Auto and then back to custom control (without exiting the app in between) the values previously selected will be saved and I'll only have to click "Ok" to re-enable them.

**Comment by kleuter** [comment]
It's basically a planned behavior:
https://www.crystalidea.com/blog/macs-fan-control-pro
