### ISSUE TITLE
Fans not reporting in MacPro 

### ISSUE THREAD

**Issue by garrettperea** [crystalidea/macs-fan-control#202]
Technical info:
Macs Fan Control 1.4.12
MacPro5,1
CPU: Intel(R) Xeon(R) CPU E5520 @ 2.27GHz [100]
GPU: ATI Radeon HD 5770
macOS 10.11.6

Fans:
PCI-min{800}curr{952}max{4500}mode{1,900}
PS-min{600}curr{0}max{2800}mode{1,750}
EXHAUST-min{600}curr{0}max{2800}mode{1,900}
INTAKE-min{600}curr{0}max{2800}mode{1,952}
BOOSTA-min{800}curr{1124}max{5200}mode{1,950}
BOOSTB-min{800}curr{950}max{5200}mode{1,950}

TempSensors:
TA0P (Ambient) - 29.4375, 29.4375
TCAC (CPU A core from PCECI) - 46.8906, 53.1094
TCAD (CPU A Diode) - 36.25, 36.25
TCAG () - 80, 80
TCAH (CPU A HeatSink) - 33.875, 33.875
TCAS () - 33.875, 33.875
TCBC (CPU B core from PCECI) - 41.9219, 58.0781
TCBD (CPU B Diode) - 35.125, 35.125
TCBG () - 80, 80
TCBH (CPU B HeatSink) - 31.625, 31.625
TCBS () - 31.625, 31.625
TH1F () - 29.8477, 29.8477
TH1P (Drive Bay 0) - 29.875, 29.875
TH1V () - 33.8398, 33.8398
TH2F () - 30.418, 30.418
TH2P (Drive Bay 1) - 30.375, 30.375
TH2V () - 32.2344, 32.2344
TH3F () - 30.2109, 30.2109
TH3P (Drive Bay 2) - 30.125, 30.125
TH3V () - 32.8008, 32.8008
TH4F () - 30.2617, 30.2617
TH4P (Drive Bay 3) - 30.25, 30.25
TH4V () - 35.1055, 35.1055
THPS () - 35.1055, 35.1055
THTG () - 58, 58
TM1P (DIMM Proximity 1) - 32.25, 32.25
TM2P (DIMM Proximity 2) - 32.5, 32.5
TM3P (DIMM Proximity 3) - 35.125, 35.125
TM4P (DIMM Proximity 4) - 34.625, 34.625
TM5P (DIMM Proximity 5) - 35.125, 35.125
TM6P (DIMM Proximity 6) - 36, 36
TM7P (DIMM Proximity 7) - 34.625, 34.625
TM8P (DIMM Proximity 8) - 29.875, 29.875
TMA1 () - 34.5625, 34.5625
TMA2 () - 35.5, 35.5
TMA3 () - 35.625, 35.625
TMA4 () - 35.0625, 35.0625
TMB1 () - 129, 129
TMB2 () - 129, 129
TMB3 () - 129, 129
TMB4 () - 129, 129
TMHS () - 35.625, 35.625
TMLS () - 34.5625, 34.5625
TMPS () - 35.625, 35.625
TMPV () - 33.8984, 33.8984
TMTG () - 75, 75
TN0D (IOH Diode) - 51.125, 51.125
TN0H (IOH HeatSink) - 37.625, 37.625
TNTG () - 65, 65
Te1F () - 129, 129
Te1P (PCIE Ambient) - 30.125, 30.125
Te1S (PCIE slot 1) - 70, 70
Te2F () - 129, 129
Te2S () - 129, 129
Te3F () - 129, 129
Te3S () - 129, 129
Te4F () - 129, 129
Te4S (PCIE slot 4) - 61.75, 61.75
Te5F () - 36.7812, 36.7812
Te5S (PCIe RAID card) - 36.875, 36.875
TeGG () - 85, 85
TeGP () - 0, 0
TeRG () - 60, 60
TeRP () - 36.7812, 36.7812
Tp0C (PSMI Supply AC/DC Supply 1) - 27.6094, 27.6094
Tp1C (PSMI Supply AC/DC Supply 2) - 28.3438, 28.3438
TpPS () - 28.3438, 28.3438
TpTG () - 90, 90

Disk drives:

![Screen Shot 2019-08-17 at 6 13 04 PM](https://user-images.githubusercontent.com/29288776/63218888-d5b17c80-c11a-11e9-8b9b-56bde86f6258.png)

**Comment by garrettperea** [comment]
Fans are running on high, recently installed a new CPU tray when this started.  Installed MFC to regulate the max fans issue.

**Comment by kleuter** [comment]
https://forums.macrumors.com/threads/mac-pro-5-1-upgrade-smc-conflict-fan-control.2062360/
