### ISSUE TITLE
FEATURE REQUEST: set max rpm value instead of constant one

### ISSUE THREAD

**Issue by sgoendoer** [crystalidea/macs-fan-control#204]
Allow setting of the MAX RPM value for the fans, maybe also a min value. It's nice and cool to be able to set a constant value - but I dont want the fan to be running 24/7 in case it wouldnt be needed.

**Comment by kleuter** [comment]
Will be available soon, (couple of days) as presets
https://github.com/crystalidea/macs-fan-control/issues/176
