### ISSUE TITLE
Feature request: "low power mode"

### ISSUE THREAD

**Issue by tsvetiligo** [crystalidea/macs-fan-control#206]
First of all - thanx for great app!
Recently I start monitor "Energy" tab in Activity Monitor and notice significant impact of MacsFanControl. I assume that this is due to the frequent request for temperature from the system. I would be happy even if the application began to respond to temperature changes twice as slow, but it reduce resource use.

**Comment by kleuter** [comment]
It's improved in the latest version 1.5

**Comment by tsvetiligo** [comment]
Great, but version 1.5 require macOs 10.14 and it is sad for me and my MacBook Pro 2011 with macOs 10.13 :(

**Comment by kleuter** [comment]
![sshot-1](https://user-images.githubusercontent.com/2600624/65616874-10c98a00-dfbc-11e9-919e-5d509c4c58e1.png)

**Comment by tsvetiligo** [comment]
Thank you! I conform it's improved.
