### ISSUE TITLE
Display temperature of discrete GPU (eGPU)

### ISSUE THREAD

**Issue by martinohansen** [crystalidea/macs-fan-control#209]
Hi,

First of all, thanks for a great and beautiful application. I absolutely love it! Has any work been made to allow support for eGPUs?

**Comment by kleuter** [comment]
I'd love to, but currently couldn't find any open API to do that.

**Comment by kleuter** [comment]
Also PCIe GPU on MacPro5.1 and MacPro7,1

**Comment by William-Richards** [comment]
Mac Pro 5.1 2010 with Sapphire RX580 8GB  

ioreg -l |grep \"PerformanceStatistics\" | cut -d '{' -f 2 | tr '|' ',' | tr -d '}' | tr ',' '\n'|grep 'Temp\|Fan\|%\|(W)\|Hz‘

**Comment by kleuter** [comment]
Done in #347
