### ISSUE TITLE
request for Auto fan control + a set RPM amount

### ISSUE THREAD

**Issue by brownmeteor** [crystalidea/macs-fan-control#21]
I would like to be able to use the auto fan control but also have the option to add a set amount of RPM above what the system is set to.  So if auto is at 2000 RPM, I would like the option for +500, +1000, +2000 RPM, etc., on top.

**Comment by kleuter** [comment]
Looks like this request is already covered by https://github.com/crystalidea/macs-fan-control/issues/5
