### ISSUE TITLE
MBP 2019 8-Core CPU only showing 6 Cores

### ISSUE THREAD

**Issue by krnltask** [crystalidea/macs-fan-control#213]
I'm using the latest build.

It's only showing 6 Cores instead of my 8 Cores / 16 Threads i9.
And sometimes it's not starting automatically at system startup.
Please fix that.

System:
Macs Fan Control 1.5.0 [Qt 5.13.1]
MacBookPro15,1
CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz [8 cores]
GPU: Intel UHD Graphics 630, Radeon Pro 560X
macOS 10.15.0

Fans:
Left side-min{2160}curr{2169}max{5927}mode{2,TC1C,70,90}
Right side-min{2000}curr{1982}max{5489}mode{2,TC1C,70,90}

TempSensors:
TA0V () - 22.7383, 22.7383
TB0T (Battery Max) - 27.8984, 27.8984
TB1T (Battery Sensor 1) - 27.7969, 27.7969
TB2T (Battery Sensor 2) - 27.7969, 27.7969
TC0E () - 39.957, 39.957
TC0F () - 41.0703, 41.0703
TC0P (CPU Proximity) - 34.4375, 34.4375
TC1C (CPU Core 1) - 38, 38
TC2C (CPU Core 2) - 38, 38
TC3C (CPU Core 3) - 36, 36
TC4C (CPU Core 4) - 37, 37
TC5C (CPU Core 5) - 38, 38
TC6C (CPU Core 6) - 38, 38
TC7C () - 37, 37
TC8C () - 37, 37
TCGC (GPU PECI) - 40, 40
TCMX () - 40, 40
TCSA () - 35, 35
TCXC (CPU PECI) - 39.5469, 39.5469
TF0S () - 4.64453, 4.64453
TG0P (GPU Proximity) - 33.8125, 33.8125
TGDD () - 35, 35
TGDF () - 35.3359, 35.3359
TGVP () - 31.6875, 31.6875
TH0F () - 26.3789, 26.3789
TH0X () - 26.293, 26.293
TH0a () - 26.2539, 26.2539
TH0b () - 26.293, 26.293
TH1a () - 0, 0
TH1b () - 0, 0
TM0P (Memory Proximity) - 33.1875, 33.1875
TPCD (Platform Controller Hub Die) - 34, 34
TTLD () - 27.125, 27.125
TTRD () - 26.375, 26.375
TW0P (Airport Card) - 32.625, 32.625
TaLC () - 28, 28
TaRC () - 27.25, 27.25
Th1H (Heatsink Proximity) - 31.875, 31.875
Th2H () - 35.3125, 35.3125
Tm0P () - 35.6875, 35.6875
Tm1P () - 129, 129
Ts0P (Palm Rest) - 28.8125, 28.8125
Ts0S () - 29.0859, 29.0859
Ts1P () - 25.875, 25.875
Ts1S () - 29.7813, 29.7813
Ts2S () - 30.3555, 30.3555

Disk drives:
APPLE SSD AP0512M - 26
Apple SSD - 26.332

Path: /Applications/Macs Fan Control.app/Contents/MacOS/Macs Fan Control

**Comment by kleuter** [comment]
Thank you, will be fixed in the upcoming 1.5.1 update

**Comment by kleuter** [comment]
fixed in 1.5.1
