### ISSUE TITLE
1.5.1 beta

### ISSUE THREAD

**Issue by kleuter** [crystalidea/macs-fan-control#218]
- Fixed couple of memory leaks #214
- CPU usage improvements
- Improved Mojave/Catalina dark mode detection #189 
- Improved About dialog
- Better support of MacBookAir 2019 and MacBookPro 2019 #213
- Better readability of the menubar icon #222 #163
- Fixed menubar not getting grayed out when switching between monitors
- Misc fixes and improvements
- Notarized for macOS 10.15 Catalina #215
- Fixed issue when the helper tool couldn't be installed #226

Download
[Mojave+](https://www.crystalidea.com/downloads/macsfancontrol_beta.zip)
[Mac OS X 10.7 Lion - Mac OS X 10.13 High Sierra](https://www.crystalidea.com/downloads/macsfancontrol_beta_sierra.zip)

**Comment by atomizasser** [comment]
> Improved Mojave/Catalina dark mode  detection

it doesn't work. iMac 11,3 (Catalina OS) with auto night mode activated.
![Captura de pantalla 2019-10-18 a las 17 34 43](https://user-images.githubusercontent.com/11031384/67107899-9dd3bd80-f1cd-11e9-9991-2267ea49013f.png)

**Comment by kleuter** [comment]
Beta updated

**Comment by kleuter** [comment]
1.5.1 is out
