### ISSUE TITLE
Unable to update to new version

### ISSUE THREAD

**Issue by akdiesel** [crystalidea/macs-fan-control#22]
I am unable to update to the latest version of macs-fan-control from the old version of 1.4.1.  It will download the version but states Error Extracting Update.  
[MacsFanControl.log](https://github.com/crystalidea/macs-fan-control/files/1675218/MacsFanControl.log)

**Comment by kleuter** [comment]
Sir, you have to download the latest version and install (move to your /Applications folder) manually.
https://www.crystalidea.com/downloads/macsfancontrol.zip
