### ISSUE TITLE
Doesn't work on Catalina

### ISSUE THREAD

**Issue by jessefogarty** [crystalidea/macs-fan-control#221]
Not updated to support Catalina OS.

:(

**Comment by kleuter** [comment]
What made you think that Catalina is not supported?

**Comment by kleuter** [comment]
The app does work on 10.15

**Comment by jessefogarty** [comment]
“Macs Fan Control” can’t be opened because Apple cannot check it for malicious software.

That's why.

Y'all need to calm down and not get so defensive. 
- Jesse
-- 
Securely sent with Tutanota.

If you forgot your conversation password. Please text me using Signal @ (647)571-7808.



Oct 8, 2019, 04:31 by notifications@github.com:

**Comment by kleuter** [comment]
Can you press Cmd+Click on the app once before the app is [notarized](https://github.com/crystalidea/macs-fan-control/issues/215)?
