### ISSUE TITLE
Feature Request Menu Bar Increase Temperature Font Size/Add Temp Colors

### ISSUE THREAD

**Issue by big610** [crystalidea/macs-fan-control#222]
Feature Request Menu Bar Increase Temperature Font Size/Add Temp Colors 

Increase & Decrease, choose the Size of the Font Size Temp Icon. Difficult to see, I have to put on glasses to see. Would be nice to have increased size to also see from afar.

Menu Bar Icon show a Color for the Temperatures. 
Difficult to see at Nite.
Under 65 C could be Green, 66 C to 70 C could be Orange, 71 C and above could be Red.

Screenshot example to show Font Size & Color other Devs use next to MFC.
[Screen Shot Menu Bar Increase Temp Font Sizes:Colors](https://user-images.githubusercontent.com/35133409/66615313-dfc68900-eb67-11e9-8834-794f57d38b4e.png)

**Comment by kleuter** [comment]
It must be improved in the [latest beta](https://github.com/crystalidea/macs-fan-control/issues/218)

**Comment by kleuter** [comment]
fixed in 1.5.1
