### ISSUE TITLE
My iMac mid 2011 freezes with MFC enabled

### ISSUE THREAD

**Issue by paulclaude** [crystalidea/macs-fan-control#227]
After several months of use, now my iMac mid 2011 freezes with MFC enabled (eternal bouncing ball and forced manual restart), sometimes at login, sometimes after a few minutes.
Restarting in safe mode works. Disabling MFC works.
How can I do?

**Comment by kleuter** [comment]
https://github.com/crystalidea/macs-fan-control/blob/master/.github/CONTRIBUTING.md

**Comment by paulclaude** [comment]
I've no logs, as I can't enable MFC because at login the iMac crash. I only wonder if there is some problem with High Sierra, iMac 2011 and MFC.

**Comment by kleuter** [comment]
Disable auto start in Preferences of the app and start it manually when you already logged in.
