### ISSUE TITLE
mid 2011 iMac (12,2) crashes often, gives MOT4/4/ error

### ISSUE THREAD

**Issue by prairiedad** [crystalidea/macs-fan-control#228]
Ran Apple Hardware Test and got MOT4/4/ error. HDD-1257. But fsck runs cleanly, and fans control shows only good speeds and temps. I don't really believe that's the issue. 

The crashes happen only since yesterday when I installed the latest Safari 13.0.3 and Security Update 2019-006. Seems to me that means a software issue!

Any thoughts?
![MFC-Nov4 2019](https://user-images.githubusercontent.com/57366533/68143900-adeadd00-feef-11e9-9736-6b0211c16b65.png)
[tech_info.txt](https://github.com/crystalidea/macs-fan-control/files/3805992/tech_info.txt)

**Comment by kleuter** [comment]
Anything in ~/Library/Logs/DiagnosticReports/
?

**Comment by kleuter** [comment]
Not app related
