### ISSUE TITLE
Macs Fan Control

### ISSUE THREAD

**Issue by msatterw** [crystalidea/macs-fan-control#23]
Nice software. Question about control of GPU temperature on a mid-2011 iMac. Seems this needs special attention by controlling the GPU temp via the optical drive fan by manually resetting a range suitable to respond to the GPU heating. There's no GPU fan, per se. Recommended setpoint for the optical drive fan was min 45, max 100. Seems reasonable but I'd like to hear from the author. Reason: My video card died while system was at idle for an extended period. Yes there's a known iMac video card issue, but this inquiry is due to various threads encouraging caution with Macs Fan Contol in auto mode. Thanks.

**Comment by kleuter** [comment]
Hi,

Yes, ODD fan is responsible for cooling GPU in this iMac.

https://www.crystalidea.com/macs-fan-control/faq

```
What are optimal fan settings for my MacBook/iMac/..?

The short answer is: experiment! First observe how temperature sensors behave under automatic fan control. Then try using some custom fan settings.
```

`THE PROGRAM IS FOR ADVANCED USERS WHO KNOW HOW TO USE IT WITHOUT DOING HARM TO THEIR MAC. THE AUTHORS ARE NOT LIABLE FOR DATA LOSS, DAMAGES, PROFIT LOSS OR ANY OTHER TYPES OF LOSSES CONNECTED WITH THE USE OR MISUSE OF THE PROGRAM`
