### ISSUE TITLE
Macs Fan Control 1.5.1 crashes (uncaught exception of type std::out_of_range: vector)

### ISSUE THREAD

**Issue by MarkusGiger** [crystalidea/macs-fan-control#232]
Version 1.4.12 work's normally after upgrading to Catalina
want upgrade to Version 1.5.1
can't install new 1.5.1 Version after open and ask for Permissions and move to Programm's, goes direct to trash

regards Markus

**Comment by kleuter** [comment]
Please download the app and manually move to Applications.

**Comment by MarkusGiger** [comment]
Sorry about the circumstances, i can down load and move to Application, but after open only a Windows is short flashing, Programm not running

regards Markus

**Comment by MarkusGiger** [comment]
Sorry about the circumstances, i can down load and move to Application, but after open only a Windows is short flashing, Programm not running

regards Markus

**Comment by MarkusGiger** [comment]
HI hope it help’s to find the Problem

regards Markus

**Comment by MarkusGiger** [comment]
still not working
[Macs Fan Control_2019-11-17-074244_Markus-Gigers-iMac-2.crash.zip](https://github.com/crystalidea/macs-fan-control/files/3862406/Macs.Fan.Control_2019-11-17-074244_Markus-Gigers-iMac-2.crash.zip)

**Comment by kleuter** [comment]
Thanks for the crash report. Can you please try this version:
https://www.crystalidea.com/downloads/legacy/macsfancontrol.zip

**Comment by MarkusGiger** [comment]
same also crashed, now need to work 

regards Markus

[Macs Fan Control_2019-11-19-082809_Markus-Gigers-iMac-2.crash.zip](https://github.com/crystalidea/macs-fan-control/files/3862453/Macs.Fan.Control_2019-11-19-082809_Markus-Gigers-iMac-2.crash.zip)

**Comment by kleuter** [comment]
Please try disconnecting all your external SATA devices and run again.

**Comment by bellwood** [comment]
I am having a similar issue, MFC randomly crashes on Catalina... I don't seem to be able to launch with the app with /log as indicated on the website but "Copy Technical Info" gives the following (snipped down)

```
[2019-11-19 09:05:45:423] [thread 1857931] [app.cpp#232] Macs Fan Control 1.5.1
[2019-11-19 09:05:45:424] [thread 1857931] [app.cpp#233] macOS 10.15.1
[2019-11-19 09:05:45:424] [thread 1857931] [app.cpp#234] MacBookPro13,3
[2019-11-19 09:05:45:424] [thread 1857931] [app.cpp#235] Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz [4 cores]
[2019-11-19 09:05:45:424] [thread 1857931] [app.cpp#236] Qt 5.13.1
[2019-11-19 09:05:45:427] [thread 1857931] [app_mac.mm#132] Helper installed, version - 1.0
[2019-11-19 09:05:45:428] [thread 1857931] [app_mac.mm#147] Current version - 1.0
[2019-11-19 09:05:45:442] [thread 1857931] [SMC/Platform_mac_smcwrite.mm#79] open XPC connection to com.crystalidea.macsfancontrol.smcwrite
[2019-11-19 09:05:45:495] [thread 1857931] [SMC/Platform_mac_smcwrite.mm#49] ERROR: parseReply failed
[2019-11-19 09:05:45:495] [thread 1857931] [SMC/Platform_mac.mm#60] WARNING: connectToSMCWrite failed
[2019-11-19 09:05:45:507] [thread 1857931] [SMC/Service.cpp#77] detectSmcFanKeySize KeyType fpe2
[2019-11-19 09:05:45:507] [thread 1857931] [SMC/Service.cpp#78] detectSmcFanKeySize KeyLen 2
[2019-11-19 09:05:48:063] [thread 1858359] [FanControl/FanControl.cpp#194] InitialLoadThread
[2019-11-19 09:05:48:063] [thread 1858359] [FanControl/FanControl.cpp#111] QFanControl::loadFansFromSMC
[2019-11-19 09:05:48:064] [thread 1858359] [FanControl/FanControl.cpp#117] Fans count - 2
[2019-11-19 09:05:48:080] [thread 1858359] [FanControl/FanControl.cpp#134] Fan 0: Left side
[2019-11-19 09:05:48:082] [thread 1858359] [FanControl/FanControl.cpp#134] Fan 1: Right side
[2019-11-19 09:05:48:095] [thread 1858359] [FanControl/FanControl.cpp#52] checkFansControlModeFromSMC
[2019-11-19 09:05:48:096] [thread 1858359] [FanControl/FanControl.cpp#63] WARNING: Fan 0 mode is set by another program
[2019-11-19 09:05:48:096] [thread 1858359] [FanControl/FanControl.cpp#63] WARNING: Fan 1 mode is set by another program
[2019-11-19 09:05:48:146] [thread 1858359] [SMC/Platform_mac_smcwrite.mm#251] process_command_write: SMCWriteKey FS!  0000 OK
```

Crash occurs whether or not an external drive is present - the only time one is present is my time machine G-Drive.

Glad to add more to this as requested/needed.

**Comment by kleuter** [comment]
Please post the [crash report](https://apple.stackexchange.com/questions/26480/where-can-i-find-my-crash-logs) as well

Do you have any other fan controlling software installed? e.g. iStatMenus?

**Comment by bellwood** [comment]
See attached.

**Comment by kleuter** [comment]
Thank you, seems like another crash (damn).
Can you please check if the legacy version works without crashes?
https://www.crystalidea.com/downloads/legacy/macsfancontrol.zip

**Comment by bellwood** [comment]
I'm not sure how far back the crash collector goes but from what I have (5) reports - they are all `Version:               1.5.1.6 (0)`

I know on the previous version, I was getting some as well.

One correlation, MFC seems to crash at the end of the work day when I unplug my external monitors, G-Drive and close the lid (all the crash report timestamps align with my leaving the office) and the crash reports have Sleep/Wake UUID.

Hope this insight helps =)

**Comment by kleuter** [comment]
Thanks a lot, would you please try the version at the link above?

**Comment by bellwood** [comment]
Up and running... I'll follow up =)

**Comment by MarkusGiger** [comment]
disconnect all external Disk, still not running

[Macs Fan Control_2019-11-19-191308_Markus-Gigers-iMac-2.crash.zip](https://github.com/crystalidea/macs-fan-control/files/3865387/Macs.Fan.Control_2019-11-19-191308_Markus-Gigers-iMac-2.crash.zip)

**Comment by kleuter** [comment]
@MarkusGiger

can you please also run the app with /log parameter?

```
/Applications/Macs\ Fan\ Control.app/Contents/MacOS/MacsFanControl /log
```

**Comment by kleuter** [comment]
@MarkusGiger 

Please try running this version of the app (Cmd+Click)
https://www.crystalidea.com/downloads/macsfancontrol_log.zip

It will produce the log file on your desktop "MacsFanControl.log", please attach it here. Thank you

**Comment by bellwood** [comment]
@kleuter thus far survived the usual daily routine

**Comment by kleuter** [comment]
@bellwood thanks a lot for the follow up, please update in a day or two if it works fine

**Comment by kleuter** [comment]
@bellwood do you have an external monitor?

**Comment by kleuter** [comment]
> One correlation, MFC seems to crash at the end of the work day when I unplug my external monitors, G-Drive and close the lid (all the crash report timestamps align with my leaving the office) and the crash reports have Sleep/Wake UUID.

This is useful! I might need to try with an external monitor.

**Comment by bellwood** [comment]
I have a 2K cinema display and the display one generation back from that (dongle nightmare)

**Comment by MarkusGiger** [comment]
Here the Log

[MacsFanControl.log](https://github.com/crystalidea/macs-fan-control/files/3867478/MacsFanControl.log)

**Comment by MarkusGiger** [comment]
and crash log

[Macs Fan Control_2019-11-20-063747_Markus-Gigers-iMac-2.crash.zip](https://github.com/crystalidea/macs-fan-control/files/3867491/Macs.Fan.Control_2019-11-20-063747_Markus-Gigers-iMac-2.crash.zip)

**Comment by kleuter** [comment]
@bellwood
I created a [separate issue](https://github.com/crystalidea/macs-fan-control/issues/238) with monitors

@MarkusGiger

I still see 6 connected drives in the log
```
InitialLoadThread: number of supported SMART sensors: 6
```

**Comment by MarkusGiger** [comment]
now physically disconnected the external Disk

[MacsFanControl.log](https://github.com/crystalidea/macs-fan-control/files/3870240/MacsFanControl.log)
[Macs Fan Control_2019-11-20-172332_Markus-Gigers-iMac-2.crash.zip](https://github.com/crystalidea/macs-fan-control/files/3870242/Macs.Fan.Control_2019-11-20-172332_Markus-Gigers-iMac-2.crash.zip)

**Comment by MarkusGiger** [comment]
Version 1.5.3 are working for me, also with all external Disk connected

thx
regards Markus

**Comment by kleuter** [comment]
Thank you for the follow up!
