### ISSUE TITLE
Fan/Sensor reading on two lines - Display Error

### ISSUE THREAD

**Issue by nicdnyc** [crystalidea/macs-fan-control#234]
Running macOS Mojave 10.14.6
When the fan speed number contains four wide digits (example "2400rpm" versus "2422rpm"), the reading wraps around to a third line of text, cutting off the top and bottom of the reading.

The variable width text of the display is causing a wraparound when the fan reading contains wider characters.

Macs Fan Control 1.5.1 [Qt 5.13.1]
MacBookPro11,3
CPU: Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz [4 cores]
GPU: Intel Iris Pro, NVIDIA GeForce GT 750M
macOS 10.14.6

Fans:
Left side-min{2160}curr{2544}max{6156}mode{0}
Right side-min{2000}curr{2359}max{5700}mode{0}

TempSensors:
[Screen Recording 2019-11-17 at 2.32.32 PM.mov.zip](https://github.com/crystalidea/macs-fan-control/files/3856015/Screen.Recording.2019-11-17.at.2.32.32.PM.mov.zip)

TB0T (Battery Max) - 36, 36
TB1T (Battery Sensor 1) - 36, 36
TB2T (Battery Sensor 2) - 33.1992, 33.1992
TBXT () - 36, 36
TC0E () - 73.3516, 73.3516
TC0F () - 75.1602, 75.1602
TC0P (CPU Proximity) - 64, 64
TC1C (CPU Core 1) - 72, 72
TC2C (CPU Core 2) - 69, 69
TC3C (CPU Core 3) - 69, 69
TC4C (CPU Core 4) - 69, 69
TCGC (GPU PECI) - 69, 69
TCSA () - 71, 71
TCTD () - 255.969, 255.969
TCXC (CPU PECI) - 72.75, 72.75
TG0D (GPU Diode) - 71.875, 71.875
TG0P (GPU Proximity) - 68, 68
TG1D () - 75, 75
TG1F () - 74.9648, 74.9648
TG1d () - 69, 69
TH0A () - 45.875, 45.875
TH0B () - 45.875, 45.875
TH0F () - 220.984, 220.984
TH0R () - 220.875, 220.875
TH0V () - 48.6484, 48.6484
TH0a () - 45.875, 45.875
TH0b () - 45.875, 45.875
TH0c () - 129, 129
TM0P (Memory Proximity) - 56, 56
TM0S (Memory Slot) - 55.7578, 55.7578
TP0P () - 55.875, 55.875
TPCD (Platform Controller Hub Die) - 64, 64
TW0P (Airport Card) - 53, 53
Ta0P () - 41.625, 41.625
TaSP () - 41.6016, 41.6016
Th1H (Heatsink Proximity) - 52.625, 52.625
Th2H () - 60.375, 60.375
Ts0P (Palm Rest) - 34.4375, 34.4375
Ts0S () - 42.4297, 42.4297
Ts1S () - 43.6758, 43.6758

Disk drives:
APPLE SSD SM1024F - 45
WDC WD10JMVW-11AJGS4 - 28

Path: /Applications/Macs Fan Control.app/Contents/MacOS/Macs Fan Control

**Comment by kleuter** [comment]
It's fixed in the version 1.5.1.7
https://www.crystalidea.com/macs-fan-control/download
