### ISSUE TITLE
CPU Core 1, CPU Core 2, CPU Core 3.... -> CPU Core Average ?

### ISSUE THREAD

**Issue by kleuter** [crystalidea/macs-fan-control#235]
Would it be reasonable to display one sensor (average) instead of 1,2,3...8 cores (some modern macs have up to 18 cores)

Thanks.

**Comment by kylekoren** [comment]
Honestly I would prefer this over individual core sensor values, but having both wouldn't be a bad idea. Something along the lines of "Package Temperature" or "Core Average" etc.

**Comment by L-Delorme** [comment]
Apparently PECI is quasi synonymous with max core temperature. That's the sensor I'm now using for both CPU and GPU monitoring. In my relatively short experience (a little over a week) it's always about a degree or two above the max core temperature... That's even better TBH.
<img width="1001" alt="Bildschirmfoto 2020-01-13 um 14 01 28" src="https://user-images.githubusercontent.com/52100844/72258114-87db6a80-360d-11ea-9dee-54ce424dc243.png">

**Comment by tmancey** [comment]
As my machine is maxed out while building, I just wanted to watch all 18 cores, so would be good to increase to show all cores and offer option to show average

**Comment by zecanard** [comment]
@kleuter what’s allowing https://github.com/crystalidea/macs-fan-control/issues/235#issuecomment-573653882 to show 8 CPU cores vs. only 4 https://github.com/crystalidea/macs-fan-control/issues/316#issuecomment-616783201?

**Comment by kleuter** [comment]
Done in the latest beta #347 
![image](https://user-images.githubusercontent.com/2600624/84941180-4893d700-b0e1-11ea-95c0-3f84aa80998e.png)
