### ISSUE TITLE
Crash when disconnecting external monitors (crash in libqcocoa.dylib)

### ISSUE THREAD

**Issue by kleuter** [crystalidea/macs-fan-control#238]
> One correlation, MFC seems to crash at the end of the work day when I unplug my external monitors, G-Drive and close the lid (all the crash report timestamps align with my leaving the office) and the crash reports have Sleep/Wake UUID.
I have a 2K cinema display and the display one generation back from that (dongle nightmare)
[MFC.Crash.Log.11-18-2019.zip](https://github.com/crystalidea/macs-fan-control/files/3868508/MFC.Crash.Log.11-18-2019.zip)

**Comment by kleuter** [comment]
The crash occures in libqcocoa.dylib (Qt version 5.13.1)
Please try to use the [legacy version](https://www.crystalidea.com/downloads/legacy/macsfancontrol.zip)
and report if it works fine (Qt version 5.6.3)

**Comment by kleuter** [comment]
@bellwood

> thus far survived the usual daily routine

**Comment by kleuter** [comment]
thanks a lot for the follow up, please update in a day or two if it works fine

**Comment by kleuter** [comment]
Ok, I managed to reproduce the crash with 2 external monitors. It's related to Qt framework we use unfortunately
https://bugreports.qt.io/browse/QTBUG-80211

**Comment by bellwood** [comment]
@kleuter using the version linked to another framework from #232 has resulted in no issues thus far. I've jumped between two offices already today; connecting, removing, closing the lid and vice versa.

**Comment by kleuter** [comment]
Thanks for the follow up. the crash occurs in the framework we use, will be fixed in the main download as soon as they fix it there.

**Comment by bellwood** [comment]
You bet - still running just fine here - look forward to an official release  when they fix the bug(s) =)

**Comment by lucascosti** [comment]
I think I am experiencing this a similar issue with my Catalina MacBook Pro. It occurs when I am using external monitors, and the Macbook goes to sleep. When resuming from a sleep, I notice that sometimes macs-fan-control (v1.5.2) isn't running any more.

**Comment by kleuter** [comment]
Must be fixed in 1.5.3 now

**Comment by westito** [comment]
Thank God! I have external monitors and experienced this issue from the beginning. I didn't noticed when app closed, only when MacBook started lagging because of overheat.
