### ISSUE TITLE
Check For Updates Fails on Lion.

### ISSUE THREAD

**Issue by pjpreilly** [crystalidea/macs-fan-control#239]
In os x Lion the manual check for updates fails as pictured. Is this a known issue?

![2019-11-25 08 24 39 pm](https://user-images.githubusercontent.com/10430084/69591879-24946b00-0fc2-11ea-9f17-ec6d7b1a8e6d.png)

**Comment by kleuter** [comment]
Confirmed.
I'm afraid the problem is in the Qt framework, currently have no workaround for that.

**Comment by pjpreilly** [comment]
I asked because it works for f.lux......

![2019-11-26 09 13 20 am](https://user-images.githubusercontent.com/10430084/69640956-4bd45200-102d-11ea-878e-a4f57e1ac2e1.png)

**Comment by kleuter** [comment]
We have no relation to this app.

**Comment by kleuter** [comment]
Will add a warning message in 1.5.10 to notify user about the issue and suggest updating manually
