### ISSUE TITLE
Reduce energy consumption

### ISSUE THREAD

**Issue by juanstecno** [crystalidea/macs-fan-control#24]
This application should not have so much impact on the consumption of energy, is behind only the antivirus that I have installed and I think this is completely disproportionate to the function it has...

![captura de pantalla 2018-02-02 a las 8 18 54](https://user-images.githubusercontent.com/36066157/35721362-df7e44ac-07f1-11e8-88be-ac8292bd03bd.png)

here you have the proof. This is not important if it is a desktop Mac, but for a laptop it is unacceptable.
Greetings.

**Comment by kleuter** [comment]
You you'd like to report a bug or on issue using the app, please include a screenshot and technical information from the Preferences dialog

**Comment by juanstecno** [comment]
hi,
the right titlle is "Excessive consumption of energy" because really is what the app do. Screenshot related was included when I did open the report. You can see here the presets here:
![captura de pantalla 2018-02-04 a las 23 02 59](https://user-images.githubusercontent.com/36066157/35782908-db54c1c0-09ff-11e8-867a-04bd0cd81e59.png)
![captura de pantalla 2018-02-04 a las 23 04 26](https://user-images.githubusercontent.com/36066157/35782909-db75c1ae-09ff-11e8-89c0-7d6116cefb4b.png)

**Comment by kleuter** [comment]
Please include a valid screenshot as described [here](https://github.com/crystalidea/macs-fan-control/blob/master/.github/CONTRIBUTING.md)

**Comment by juanstecno** [comment]
Macs Fan Control 1.4.9
MacBookPro8,1
CPU: Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz [100]
GPU: Intel HD Graphics 3000
macOS 10.11.6

Fans:
Exhaust-min{2000}curr{1995}max{6200}mode{2,TC0D,57,75}


TempSensors:
TB0T (Battery Max) - 26.3984, 26.3984
TB1T (Battery Sensor 1) - 29.5977, 29.5977
TB2T (Battery Sensor 2) - 29, 29
TC0C () - 57.4844, 57.4844
TC0D (CPU Diode) - 52.25, 52.25
TC0E () - 63.4336, 63.4336
TC0F () - 64.0156, 64.0156
TC0J () - 0.582031, 0.582031
TC0P (CPU Proximity) - 48.875, 48.875
TC1C (CPU Core 1) - 57, 57
TC2C (CPU Core 2) - 56, 56
TCGC (GPU PECI) - 56, 56
TCSA () - 55, 55
TCTD () - -1, 255.73
TM0P (Memory Proximity) - 30.25, 30.25
TM0S (Memory Slot) - 34.5117, 34.5117
TMBS () - -1, 0
TP0P () - 35.375, 35.375
TPCD (Platform Controller Hub Die) - 45, 45
TW0P () - -1, 129
Th1H (Heatsink Proximity) - 35.375, 35.375
Ts0P (Palm Rest) - 16.875, 16.875
Ts0S () - 29.7578, 29.7578


Disk drives:
CT240BX300SSD1 - 29

![captura de pantalla 2018-02-05 a las 18 34 25](https://user-images.githubusercontent.com/36066157/35819543-508c02e8-0aa3-11e8-800f-019dd4592bc0.png)
![captura de pantalla 2018-02-05 a las 18 34 25](https://user-images.githubusercontent.com/36066157/35819558-5b76f7ee-0aa3-11e8-95aa-daec535b4ca3.png)

All done!

**Comment by wiput1999** [comment]
![image](https://user-images.githubusercontent.com/8299278/47483475-8e908d00-d863-11e8-87f3-c327a5f27605.png)
Too high energy impact!

**Comment by kleuter** [comment]
Fixed in 1.5
