### ISSUE TITLE
Macs Fan Control 1.2.1 and ODD fan at full speed.

### ISSUE THREAD

**Issue by equenda** [crystalidea/macs-fan-control#240]
Hello.
I will try to describe my issue with my very basic English…..sorry!

Some days ago one of our iMac 21.5” (Mid-2011) suddenly hang at boot showing a gray screen.
After some unsuccessful tests (boot from recovery partition, boot from external FW drive with same OS) we took the iMac at one (indipendent) tech laboratory.
These guys have done a “reflush” (in simple words “re-soldering”…) of the GPU board.
Now the iMac is working good except for one of the (three?) FANS that spins at high speed all the time.
If you look at my Macs Fan Control snapshot, you can see a ZERO indication for the ODD fan.
So I SUPPOSE that the problem is the ODD fan and/or a damaged GPU temp sensor.

No luck with SMC reset or setting the ODD fan to a constant RPM value.

Can you give me some advice?

Thank-You.

Ettore

DIAGNOSTIC TEXT:-----------------------------
Macs Fan Control 1.2.1
iMac12,1
Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz[100]
Mac OS X 10.6

Fans:
ODD-min{1000}curr{0}max{4350}mode{0}
HDD-min{1100}curr{1099}max{6300}mode{0}
CPU-min{1200}curr{1199}max{2600}mode{2,TG0D,30,55}

TempSensors:
TA0P (Ambient) - 19.0352, 19.0352
TA0V () - 18.8516, 18.8516
TA0p () - 21.125, 21.125
TC0H (CPU Heatsink) - 25.875, 25.875
TC0P (CPU Proximity) - 26, 26
TC0c () - 33, 33
TC0h () - 25.875, 25.875
TC0p () - 26, 26
TC1c () - 32, 32
TC2c () - 32, 32
TC3c () - 32, 32
TCGc () - 31, 31
TCSc () - 30, 30
TCXc () - 33.1719, 33.1719
TG0D (GPU Diode) - 26.75, 26.75
TG0H (GPU Heatsink) - 25.25, 25.25
TG0d () - 26.75, 26.75
TG0h () - 25.25, 25.25
TG0p () - 26, 26
TH0O () - -1, 249
TH1O () - -1, 249
TL0P (LCD proximity) - 12.5742, 12.5742
TL0V () - -1, 128
TL0p () - 26.375, 26.375
TL1P () - 22.5, 22.5
TL1V () - 21.3477, 21.3477
TL1p () - 22.5, 22.5
TL1v () - 21.4375, 21.4375
TL2V () - -1, 128
TLAV () - -1, 128
TLBV () - 26.043, 26.043
TLCV () - -1, 128
TO0P (Optical Drive) - 22.875, 22.875
TO0p () - 23.875, 23.875
TPCD () - 43, 43
TS0P () - -1, 128
TS0V () - -1, 128
TS0p () - -1, 128
TS2P () - 23, 23
TS2V () - 25.4141, 25.4141
TS2p () - 23, 23
Tm0P (Mem Controller) - 27, 27
Tm0p () - 27, 27
Tp1P () - 25.75, 25.75
Tp1p () - 25.75, 25.75
Tp2H () - 32.5, 32.5
Tp2h () - 32.5, 32.5
Tp3H (PSU Primary) - 28.875, 28.875
Tp3h () - 28.875, 28.875

Disk drives:
ST3500418AS - 23
END OF DIAGNOSTIC TEXT ---------------------------------

![MFC](https://user-images.githubusercontent.com/58213191/69620487-bf7e5b00-103d-11ea-8722-62b3a7f7c1e5.jpg)

**Comment by kleuter** [comment]
Hello, I think you need make sure that ODD fan is working properly. If it's not connected or broken there's nothing we can do in the app about it.

**Comment by equenda** [comment]
> Hello, I think you need make sure that ODD fan is working properly. If it's
> not connected or broken there's nothing we can do in the app about it.
> 
> 
> 
> 
First of all Thank-You for your answer.

Since the ODD fan is spinning at full speed I suppose that:

1.  the fan itself it can¹be broken

2.  the problem is the thermal sensor not recognized by the fan.


Thank-You again.


Ettore Quaglia

**Comment by kleuter** [comment]
I'd agree to that but the app cannot help you anyways
