### ISSUE TITLE
unable to reset with system automatic model, fans alway stop unless custom

### ISSUE THREAD

**Issue by TomLao** [crystalidea/macs-fan-control#242]
The first time i set fans by customs. However, after i reset in automatic model, the fan alway stop whatever temperature it is.And i exit the macs fan control, use commend: `sudo powermetrics ... --samplers smc` to monitor fans. It is still stop. And i try to restore smc under the direction of apple.com `https://support.apple.com/en-us/HT201295`. The fans is still not run, unless i open macs fan control and set custom, the fans can start to run.

How i can solve the question?

### some screen shot

in automatic model, the fans not run.
![image](https://user-images.githubusercontent.com/24352942/69888857-0bc0e800-1329-11ea-80e4-d37d8fe78d27.png)

after i quit macs fan control and reboot my macbook, use the commend `sudo powermetrics ... --samplers smc` to check, the fan is still stop
![image](https://user-images.githubusercontent.com/24352942/69889116-41b29c00-132a-11ea-8cb2-821668168f97.png)

set with custom, the fans can work
![image](https://user-images.githubusercontent.com/24352942/69888905-4f1b5680-1329-11ea-8cbd-ac3d051d0682.png)

Thanks lots.
[tech_info.txt](https://github.com/crystalidea/macs-fan-control/files/3922230/tech_info.txt)

**Comment by kleuter** [comment]
Hi,

This macbook pro is able to turn off the fans when the computer is cold enough.

**Comment by TomLao** [comment]
> Hi,
> 
> This macbook pro is able to turn off the fans when the computer is cold enough.

So is it means that i can use my mac safely in this situation? Sometime the temperature reach 60+ celsius degree with the fans off. I have little worry.

**Comment by kleuter** [comment]
"It's safe" - says Apple 😉
