### ISSUE TITLE
Fan controller won't open and fans have been turned up to max

### ISSUE THREAD

**Issue by clane508980** [crystalidea/macs-fan-control#243]
ATTENTION: All Issue reports should please contain a screenshot and the system Diagnostics text, as described [here](https://github.com/crystalidea/macs-fan-control/blob/master/.github/CONTRIBUTING.md)

**Comment by kleuter** [comment]
https://github.com/crystalidea/macs-fan-control/blob/master/.github/CONTRIBUTING.md
