### ISSUE TITLE
Mac Pro 4,1 / 5,1 - Two SSDs of the same model... fan control will only allow first in list to be selected for monitoring

### ISSUE THREAD

**Issue by tenko23** [crystalidea/macs-fan-control#246]
Hi!

On a 2009/2010 Mac Pro... when a user has two hard drives of the same model, the user can only select the HDD that is first on the list, for monitoring.  Selecting the second will either only default to the first or cause the software to bug out when trying to switch to auto.  The two HDDs in question are two SSDs one one PCIe card.

Thanks much for looking into this!

![Screen Shot 2019-12-10 at 7 47 02 pm copy](https://user-images.githubusercontent.com/34230416/70584747-b3d77c00-1b87-11ea-916a-f2aa9275fa58.jpg)

**Comment by tenko23** [comment]
The log is too big - it can be downloaded here:...
https://www.dropbox.com/s/2cd9s3stzn92p89/log.txt?dl=0

**Comment by kleuter** [comment]
Thank you, will fix it.

**Comment by kleuter** [comment]
Done in #347
