### ISSUE TITLE
Cannot update from within v1.5.2 after week

### ISSUE THREAD

**Issue by alvarnell** [crystalidea/macs-fan-control#247]
I can understand why you might want to meter out updates, but it's been a week since v1.5.3 was released and I still cannot update by using More->Check for updates...

**Comment by kleuter** [comment]
Automatic update was not available for all regions, now it should be fine.

**Comment by alvarnell** [comment]
It's almost 24 hours later and I still can't update from the West Coast of USA

**Comment by rileytwo** [comment]
@kleuter I'm still not able to update -- I've been on 1.5.1. When I go to check for updates (via the same method as @alvarnell above), MFC says that 1.5.1 is the most up to date version.

**Comment by kleuter** [comment]
Please let me check that

**Comment by kleuter** [comment]
Must be fixed now, I do apologize for this inconvenience.
