### ISSUE TITLE
Icons change whenever mac fan control is on

### ISSUE THREAD

**Issue by nellem** [crystalidea/macs-fan-control#25]
This is vey strange, whenever i turn on mac fan control, icons become "blank paper with ruler, pencil and brush"

![screen shot 2018-02-05 at 1 00 22 am](https://user-images.githubusercontent.com/35590134/35790394-29b799e0-0a10-11e8-9686-c3284159fb4d.png)

![screen shot 2018-02-05 at 1 03 22 am](https://user-images.githubusercontent.com/35590134/35790423-60ee4c9c-0a10-11e8-947d-ecfaa7b0c99c.png)

**Comment by kleuter** [comment]
I believe this issue is not connected to the app. Otherwise, record a video that demonstrates  how the app changes icons after it starts.
