### ISSUE TITLE
Won't work on Macbook Pro 15' 2019 (Macos 10.15.1)

### ISSUE THREAD

**Issue by Watanabe-Hana** [crystalidea/macs-fan-control#250]
The App won't get any response on my Macbook, I've tried command + click and I've reboot my computer.
My device is Macbook Pro 15 inch 2019, system is Macos 10.15.1. The App is the newest to download.

**Comment by Watanabe-Hana** [comment]
System upgraded to 10.15.2, the Bug exists.

Though there is no UI shows on, there do have a process in Activity Monitor.

![image](https://user-images.githubusercontent.com/26091385/70844514-0f05b900-1e7d-11ea-85f5-7fe22a60df8c.png)

**Comment by kleuter** [comment]
Please force quit the process and try again

**Comment by Watanabe-Hana** [comment]
Of course I tried to force quit the process,  even rebooting the system won't make any change.

**Comment by Watanabe-Hana** [comment]
Different form your official release, I just found a cracked version and it worked so fine. Issue closed.

**Comment by kleuter** [comment]
Nice 😄 which version?
