### ISSUE TITLE
Control strip/touch bar support.

### ISSUE THREAD

**Issue by gcphost** [crystalidea/macs-fan-control#251]
Hi there,

I just purchased the unlocked version due to my 2019 16" MBP being very hot on the bottom and I am happy with using the presets to adjust the fan speeds to quickly cool my MBP down.

I am writing to see if it is possible to add Control strip/touch bar support, like maybe a fan button you click multiple times to adjust speed.

I think this would be a nice feature.

Also would love to see the ability to click on the pre-set menu item to set it instead of having to click Apply.

![image](https://user-images.githubusercontent.com/1173636/70952274-950b3680-201a-11ea-8ada-fcde1564258c.png)

Thank you for the useful software.

**Comment by kleuter** [comment]
Apple dropped touch bar so it won't be done.
