### ISSUE TITLE
macs fan control mac version 1.5.3 can not be open

### ISSUE THREAD

**Issue by chinanoahli** [crystalidea/macs-fan-control#252]
Symbolic Link broken at 
<img width="770" alt="11111" src="https://user-images.githubusercontent.com/10005128/71181909-6b6f3b00-22b8-11ea-80b2-5942cf47fb61.png">

**Comment by kleuter** [comment]
Please download the app from here
https://github.com/crystalidea/macs-fan-control/releases/download/v1.5.3/macsfancontrol.zip

**Comment by chinanoahli** [comment]
> Please download the app from here
> https://github.com/crystalidea/macs-fan-control/releases/download/v1.5.3/macsfancontrol.zip

I tried, but same issue, all QTfarmeworks folder had a broken symbolic link.
And mac popup a windows sad "can not open app 'macs fan control' -47"
![image](https://user-images.githubusercontent.com/10005128/71253580-b007de80-236b-11ea-9a59-9c009656569f.png)

**Comment by chinanoahli** [comment]
And I tried to run app in shell
```
cd Macs\ Fan\ Control.app/Contents/MacOS
./Macs\ Fan\ Control
```
but It stick here
![image](https://user-images.githubusercontent.com/10005128/71253756-260c4580-236c-11ea-820b-bea4569d82a0.png)

**Comment by xtrem123** [comment]
Same here. Can't open 1.5.3 on MacBookPro15,2

**Comment by xtrem123** [comment]
> Same here. Can't open 1.5.3 on MacBookPro15,2

I can see Mac Fans Control process in Activity monitor. But no icons in menu or window. Did a uninstall of all files and reinstalled. Nothing.

**Comment by xtrem123** [comment]
Also tested with a MacPro6,1 and 10.15.2.

Macs Fan Controll process running but no window or menus.

**Comment by xtrem123** [comment]
1.5.4 won't start either

**Comment by kleuter** [comment]
and 1.5.5 ?

**Comment by chinanoahli** [comment]
> and 1.5.5 ?

I downloaded macs fan control on your website few days ago, now I am using 1.5.4.

It is ok now.
