### ISSUE TITLE
1.5.3 Wont let me use the same manual speed twice in a row

### ISSUE THREAD

**Issue by HeavenlyGarden100** [crystalidea/macs-fan-control#253]
After the new 1.5.3 update, MFC suddenly wont let me use the same manual speed over again. For example, when encoding a video file, I like to keep my fans locked at either 5000, or 6000rpm depending on the resolution, however after updating to 1.5.3, if i were to lock my fans at 5000rpm, then set them back to auto, then later try to set them to 5000rpm again, it simply will not switch to manual at all. it simply stays in auto, and I have to switch the fans to either 4999, or 5001rmp in order for it to register and switch to auto. I know it not a huge issue, but when switching the fans multiple times throughout the day, it really does ruin that feel of the fans being a single switch

**Comment by kleuter** [comment]
Bug confirmed, please stay tuned for the next update. Thank you

**Comment by kleuter** [comment]
Fixed in 1.5.4 coming tomorrow (13 Jan)
