### ISSUE TITLE
MFC won't open for RPM update after the first start when Mac is freshly restarted.

### ISSUE THREAD

**Issue by hristislavbg** [crystalidea/macs-fan-control#255]
The application is not available for opening after the first time I close it.
In order to reopen it , I need to restart the mac.
I was unable to find the PID number of the process and therefore the only fix I could find was the restarting of the machine.
<details>
macOS Catalina, 10.15.1
</details>

**Comment by kleuter** [comment]
I don't understand. You can re-open the app from the menubar.

**Comment by hristislavbg** [comment]
Sometimes it does not work for me. When this happens, I need to restart the OS.
