### ISSUE TITLE
MFC for linux

### ISSUE THREAD

**Issue by startergo** [crystalidea/macs-fan-control#258]
Can you please develop a linux app based on MFC? I among many other cMP users would be glad to support the development or pay for a license. As a beginning there is already [MBPFAN ](https://github.com/linux-on-mac/mbpfan)
Basic linux application using coretemp as a control source for the fans. [lm-sensors](https://github.com/lm-sensors/lm-sensors) already display all sensors available in the cMP.

**Comment by kleuter** [comment]
I'm sorry it's not planned due to a very low % of possible linux users. I'm not closing it though.

**Comment by startergo** [comment]
How many users do you need for consideration? I linked this issue in the Macrumors. Maybe we can create a voting system. Just let us know what do you need to start the project.
Thanks for consideration.

**Comment by startergo** [comment]
How about funding the project on kickstarter or similar. All fundraisers get free license or something similar?

**Comment by startergo** [comment]
Bear in mind that all non T2 equipped macs will become obsolete and unsupported sooner than later. People will prefer switching to Linux because of the security updates. I think controlling the temperature is one of the main obstacles for people to use Linux as their main OS on Macs.

**Comment by kleuter** [comment]
Installing Linux on a T2 mac is a challenge for people who want compiling kernel and 3rdparty drivers that sometimes work and sometimes not. Since the app is not open-source, Linux support is hardly possible.

**Comment by startergo** [comment]
This is what I am saying. Your target for Linux MFC will be all non-T2 Macs. I don't even know if it is possible to install Linux on the new MBP.

**Comment by kleuter** [comment]
It's possible but very tricky. Linux is not officially supported so we don't have any plans on it.
