### ISSUE TITLE
Chrome Browser: lines across the screen

### ISSUE THREAD

**Issue by R0de0** [crystalidea/macs-fan-control#26]
Greetings,

iMac 2011 Sierra

When I run the latest Macs Fan Control, my Chrome Browser gets lines across the screen. If I exit MFC, the problem immediately goes away. Mac is running fine and is well tuned otherwise. 

Any suggestions?

Regards,
Wyatt.

**Comment by kleuter** [comment]
Please post a screenshot.

**Comment by R0de0** [comment]
![screen shot 2018-02-09 at 1 01 48 pm](https://user-images.githubusercontent.com/36279181/36042733-d88ed8c4-0d9a-11e8-887e-f654e4042ee8.png)

**Comment by kleuter** [comment]
Try to turn fans back to Auto in Macs Fan Control

**Comment by R0de0** [comment]
I will try Auto mode on Monday when I get back to this MAC. Thank you!

**Comment by R0de0** [comment]
Tried Auto mode, same lines accross screen. As soon as I turn Macs Fan Control, the lines go away.
Great program but very odd symptom.

![screen shot 2018-02-12 at 9 55 25 am](https://user-images.githubusercontent.com/36279181/36102948-e8357c04-0fdb-11e8-98a5-48684fb420c1.png)

**Comment by kleuter** [comment]
can you please record a video?

**Comment by R0de0** [comment]
Greetings,

I am going to retire this MAC so please take down my posting.

Regards,
Wyatt.
