### ISSUE TITLE
Purchased PRO version to create presets - unable to create presets

### ISSUE THREAD

**Issue by eccsolutions** [crystalidea/macs-fan-control#260]
The option to create presets showed on the Free version. Selecting the Custom option prompted me to purchase the PRO version. I proceeded to purchase and activate. Now the Custom option no longer exists and I am unable to create my own presets as described in the online documentation. In addition, the gear icon appears to be grayed out.

**Comment by kleuter** [comment]
https://www.crystalidea.com/macs-fan-control/fan-presets
