### ISSUE TITLE
Incompatibility with Windows on iMacPro1,1/MacPro7,1

### ISSUE THREAD

**Issue by johntamch** [crystalidea/macs-fan-control#262]
so excited that v1.5.4 finally support win10 with T2 chip.  But it give error when launching.  

"Error initializing SMC layer, please make sure your Mac system is supported and you have correctly installed the program."

Mine is a iMac Pro with win10 bootmcap and is supported in the release note.

**Comment by kleuter** [comment]
Please try [this build](https://www.crystalidea.com/downloads/macsfancontrol_setup_test.exe), once you see the SMC error, please press the Copy Log button and paste it in your reply. Thank you.

**Comment by johntamch** [comment]
[2020-01-15 15:19:51:942] [thread 12756] [g:\projects\macsfancontrol\app\app.cpp#255] Macs Fan Control 1.5.4
[2020-01-15 15:19:51:942] [thread 12756] [g:\projects\macsfancontrol\app\app.cpp#256] Windows 10 x64
[2020-01-15 15:19:51:942] [thread 12756] [g:\projects\macsfancontrol\app\app.cpp#257] iMacPro1,1
[2020-01-15 15:19:51:942] [thread 12756] [g:\projects\macsfancontrol\app\app.cpp#258] Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz [8 cores]
[2020-01-15 15:19:51:942] [thread 12756] [g:\projects\macsfancontrol\app\app.cpp#259] Qt 5.13.2
[2020-01-15 15:19:51:959] [thread 12756] [g:\projects\macsfancontrol\app\smc\platform_win.cpp#33] PlatformWin::open trying MMIO
[2020-01-15 15:19:51:960] [thread 12756] [g:\projects\macsfancontrol\app\smc\platform_win_sys_mmio.cpp#84] ERROR: No interfaces found, driver doesn't seem to be not installed
[2020-01-15 15:19:51:960] [thread 12756] [g:\projects\macsfancontrol\app\smc\platform_win_sys_mmio.cpp#117] ERROR: FAILED to open <no-interface>, error 0

**Comment by biglarryglz** [comment]
I seem to have same issue. Here is what i got: 

[2020-01-15 17:36:06:341] [thread 18368] [g:\projects\macsfancontrol\app\app.cpp#255] Macs Fan Control 1.5.4
[2020-01-15 17:36:06:342] [thread 18368] [g:\projects\macsfancontrol\app\app.cpp#256] Windows 10 x64
[2020-01-15 17:36:06:342] [thread 18368] [g:\projects\macsfancontrol\app\app.cpp#257] iMacPro1,1
[2020-01-15 17:36:06:342] [thread 18368] [g:\projects\macsfancontrol\app\app.cpp#258] Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz [8 cores]
[2020-01-15 17:36:06:342] [thread 18368] [g:\projects\macsfancontrol\app\app.cpp#259] Qt 5.13.2
[2020-01-15 17:36:06:367] [thread 18368] [g:\projects\macsfancontrol\app\smc\platform_win.cpp#33] PlatformWin::open trying MMIO
[2020-01-15 17:36:06:367] [thread 18368] [g:\projects\macsfancontrol\app\smc\platform_win_sys_mmio.cpp#84] ERROR: No interfaces found, driver doesn't seem to be not installed
[2020-01-15 17:36:06:368] [thread 18368] [g:\projects\macsfancontrol\app\smc\platform_win_sys_mmio.cpp#117] ERROR: FAILED to open <no-interface>, error 0

**Comment by Olprinz** [comment]
[2020-01-17 16:10:50:362] [thread 4648] [g:\projects\macsfancontrol\app\app.cpp#255] Macs Fan Control 1.5.4
[2020-01-17 16:10:50:363] [thread 4648] [g:\projects\macsfancontrol\app\app.cpp#256] Windows 10 x64
[2020-01-17 16:10:50:363] [thread 4648] [g:\projects\macsfancontrol\app\app.cpp#257] iMacPro1,1
[2020-01-17 16:10:50:363] [thread 4648] [g:\projects\macsfancontrol\app\app.cpp#258] Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz [8 cores]
[2020-01-17 16:10:50:363] [thread 4648] [g:\projects\macsfancontrol\app\app.cpp#259] Qt 5.13.2
[2020-01-17 16:10:50:380] [thread 4648] [g:\projects\macsfancontrol\app\smc\platform_win.cpp#33] PlatformWin::open trying MMIO
[2020-01-17 16:10:50:380] [thread 4648] [g:\projects\macsfancontrol\app\smc\platform_win_sys_mmio.cpp#84] ERROR: No interfaces found, driver doesn't seem to be not installed
[2020-01-17 16:10:50:381] [thread 4648] [g:\projects\macsfancontrol\app\smc\platform_win_sys_mmio.cpp#117] ERROR: FAILED to open <no-interface>, error 0

**Comment by Olprinz** [comment]
And now the fans are not working at all, even after uninstalling the program.. i now gotta format my partition!

**Comment by Olprinz** [comment]
I formated my partition now.. nevermind.

**Comment by kleuter** [comment]
1. Please go to device manager, check on Show Hidden Devices
![sshot-17](https://user-images.githubusercontent.com/2600624/72669590-06803f80-3a34-11ea-868d-4c7d3aaf814f.png)
2. Find **Apple SMC Device** under System devices and double click on it
3. Please post screenshots of the General tab and Details tab with device instance path as shown below

![sshot-23](https://user-images.githubusercontent.com/2600624/72669600-2c0d4900-3a34-11ea-91d2-ede63eeeb935.png)

![sshot-21](https://user-images.githubusercontent.com/2600624/72669599-2c0d4900-3a34-11ea-91b6-e3dfe4e24221.png)

**Comment by johntamch** [comment]
![image](https://user-images.githubusercontent.com/26667306/72670079-3fd89f80-3a74-11ea-8a43-c18243291bd7.png)
![image](https://user-images.githubusercontent.com/26667306/72670094-64347c00-3a74-11ea-87cb-09572bbaa131.png)
![image](https://user-images.githubusercontent.com/26667306/72670098-73b3c500-3a74-11ea-837d-f84321c494d8.png)

![image](https://user-images.githubusercontent.com/26667306/72670106-8d550c80-3a74-11ea-859e-5acb32939cbd.png)
![image](https://user-images.githubusercontent.com/26667306/72670108-95ad4780-3a74-11ea-8766-1513a616b078.png)

**Comment by Olprinz** [comment]
Hi John, thank you for the reply. Right now i dont want to reinstall your
software because Last time my Fans stopped working and i just hast to
Format m Partition to get Them Working Normally again. Please let me know
if you got a fix, i will consider buying the software because of your
Engagement.

With Kind Regards,
Oskar Dahm
John TAM <notifications@github.com> schrieb am Sa. 18. Jan. 2020 um 21:31:

**Comment by kleuter** [comment]
@johntamch
thanks a lot for the report. Will try to figure it out

**Comment by kleuter** [comment]
Can you try to locate the conflicting device and disable it?

**Comment by biglarryglz** [comment]
> Can you try to locate the conflicting device and disable it?

I have the same issue. The conflict device list says there is no conflicts.

**Comment by johntamch** [comment]
@kleuter 
![image](https://user-images.githubusercontent.com/26667306/72676033-7ab7f300-3ac7-11ea-9b03-72072c6f3cfb.png)

The only thing that seems to overlapped is memory.  I have disabled it but still no luck.

**Comment by kleuter** [comment]
Thanks... Currently I don't know why it doesn't work. I wish I had this computer to test... It's too expensive

**Comment by kleuter** [comment]
@did you try to restart after disabling "Apple graphics mux" ?

**Comment by johntamch** [comment]
> @johntamch did you try to restart after disabling "Apple graphics mux" ?

@kleuter    Sadly yes.

**Comment by johntamch** [comment]
@kleuter and if u have a new test build later , I’m happy to test it for u.

**Comment by kleuter** [comment]
Hi, all!

Please try [this build](https://www.crystalidea.com/downloads/macsfancontrol_setup_imac_test.exe), it's not planned to be working, but at least the Apple SMC Device is supposed  to start in the Device Manager:

![image](https://user-images.githubusercontent.com/2600624/72796147-233c9300-3c3f-11ea-8560-204d49d1c362.png)

**Comment by kleuter** [comment]
Screenshot please.

**Comment by johntamch** [comment]
@kleuter 
![image](https://user-images.githubusercontent.com/26667306/72802876-b7324d00-3c87-11ea-956b-d035803d2316.png)
![image](https://user-images.githubusercontent.com/26667306/72802881-bb5e6a80-3c87-11ea-9996-07ab252a3383.png)
![image](https://user-images.githubusercontent.com/26667306/72802900-c44f3c00-3c87-11ea-8f81-bdbdf8a1db92.png)
![image](https://user-images.githubusercontent.com/26667306/72802919-cc0ee080-3c87-11ea-84df-d4e56518508d.png)
![image](https://user-images.githubusercontent.com/26667306/72802933-d16c2b00-3c87-11ea-880c-854b44cc99fc.png)
![image](https://user-images.githubusercontent.com/26667306/72802967-e648be80-3c87-11ea-87fc-a5b7682b47d4.png)

**Comment by kleuter** [comment]
Thanks, I see. Will keep thinking, I'll probably have to buy one to test.

**Comment by kleuter** [comment]
Are there any other devices (hidden) in the Device Manager with the exclamation mark?

**Comment by johntamch** [comment]
@kleuter 
AppleSMC is the only thing with !.
![image](https://user-images.githubusercontent.com/26667306/72803317-be0d8f80-3c88-11ea-99c6-f349dd9f5b0c.png)

**Comment by kleuter** [comment]
Just a crazy idea - disable all other devices on this controller, reboot and check.

**Comment by kleuter** [comment]
Please disable macHalDriver Device as well

**Comment by johntamch** [comment]
Rebooted.  Still same error text.  Two of them have no disabled option.
 
![image](https://user-images.githubusercontent.com/26667306/72804242-f7df9580-3c8a-11ea-9b4f-61805521d819.png)

**Comment by kleuter** [comment]
and macHalDriver Device ?

**Comment by johntamch** [comment]
just disbaled the macHalDriver and rebooted.  Still same error.  :(

**Comment by kleuter** [comment]
Very bad, please re-enable all device back at the moment...

**Comment by hilcam** [comment]
Any progress on this one?

**Comment by kleuter** [comment]
I bought one, still have no idea what's going on, I can't install the driver.

**Comment by outtadorset** [comment]
metoo; iMac Pro 3GHz 10 Core, 64GB RAM, Vega 64 16 GB (Windows 10 v1909)

**Comment by xl3ackreap2** [comment]
Any new updates ?

**Comment by kleuter** [comment]
Well, no good news. The only update is that I found a guy reporting the same issue:
https://community.osr.com/discussion/287844/understanding-code12-resource-conflict

**Comment by 1105420698** [comment]
I hope you succeed, low level programming is way out of my league, wish I can I help, I also own an iMac Pro.

**Comment by kleuter** [comment]
Well, after day and night of struggle I currently came to the following (I can be wrong) thought:

For some reason ACPI DSDT tables on iMacPro1,1 and MacPro7,1 do not allow Windows kernel to give access to the requested address range for the SMC device (FE0B0000-FE0BFFFF). It might be accessible from linux I think, but it's not the point. Possible solution could be creating a patched DSDT table and override it in Windows via registry. Currently I patched the table for testing purposes and simply removed Memory32Fixed block from SMC device definition => device starts normally (without exclamation/bang icon) but doesn't work of cause.

[Complete DSDT](https://github.com/crystalidea/macs-fan-control/files/4174657/dsdt_imac_pro.zip)

SMC device block:

![image](https://user-images.githubusercontent.com/2600624/74088750-f3dcb180-4a99-11ea-9989-c77732a793f2.png)

**Comment by gabrielefx** [comment]
Hi all,
I need Macs Fan Control for Mac Pro 7.1 and Bootcamp because I use this machine with Blender and Nvidia Optix renderer. I installed two Nvidia RTX2080Tis blower version and I can tweak the fans speed with Msi Afterburner. Unfortunately I need to push more air inside the Mac Pro case then I need to tweak the 2nd Mac Pro fan speed (the one in the middle). Also the high temperature of the Nvidia gpus, during the rendering tasks, increases the overall temperature inside the case. Within the Msi Afterburner utility I can check the Radeon Pro 580X and Xeon temperature, also if these two components are idle their temperature increases.
I hope to see soon Macs Fan Control compatible with Windows and Mac Pro 7.1

Best regards
![mac_pro_gpu](https://user-images.githubusercontent.com/62420123/77146156-b0a73280-6a8a-11ea-810b-878932f192d6.jpg)

**Comment by kleuter** [comment]
@gabrielefx 
I'm not giving up iMacPro1,1 and MacPro7,1 yet! Still trying to find a workaround.

PS. thanks for the photo 😃

**Comment by johntamch** [comment]
@gabrielefx 
For the time being, u can use the restart trick.  Boot to macOS and set fan to full speed and restart to windows.  It works on imacpro.

**Comment by gabrielefx** [comment]
> @gabrielefx
> For the time being, u can use the restart trick. Boot to macOS and set fan to full speed and restart to windows. It works on imacpro.

thank you, it works but I'd like to have a full working version on Windows 10. Also I'd like to have curves to control the fans. For example if the temperature of the main board increases, because the overall interior temperature, I'd like to apply a curve for the middle Mac Pro 7.1 fan. Unfortunately on Windows 10 (bootcamp) this fan is almost off (or 500 rpm) because there is no MPX module plugged in front of it. The only fans that work are the axial bottom one (Radeon Pro 580X), the axial top one (Xeon) and the power supply blower fan.
I think the Apple Bootcamp utility should monitoring also the overall internal temperature but this doesn't happen.

**Comment by swheat89** [comment]
I’d be happy to donate $100+ if you get it working very soon! It would be great to have on my iMac Pro. Currently using the restart workaround, but this isn’t very sustainable.

**Comment by kleuter** [comment]
Thanks for your support and patience. I'll let you know of any progress on this asap.

PS. I also own a iMacPro1,1 and even managed to run linux on it and control fans there 😉 Windows ACPI is a pain though.

**Comment by kleuter** [comment]
**Good news** 😀 

I've created a special non-Plug&Play version of the driver (AppleSMC2) for iMacPro1,1 (tested) and MacPro7,1 (not tested). 
- MacBook Pro, MacBook Air and Mac mini will still use the normal AppleSMC
- When using eGPU this driver may crash (not tested, I don't have it)
- Works fine on my machine:

![sshot-1](https://user-images.githubusercontent.com/2600624/77485112-9d9ab680-6e2c-11ea-9b65-43589b7a6fb9.png)

PS. No donation required, Pro version would be fine 😋 


I need some time to create a test build, please be patient 😉

**Comment by swheat89** [comment]
Awesome work! 
Looking forward to testing the test build :)
Pro version it is

**Comment by gabrielefx** [comment]
Great,
could you check how the Msi Afterburner app works?
For example I have one Apple Radeon Pro 580X (mpx module), two Nvidia RTX20180Tis, one Nvidia GTX1080Ti on Razer Core egpu box.
The Msi Afterburner can control all Nvidia fans speed (with curves), also reads the temperature of all gpus, 580X too, + cpu. This happ works also for AMD (not Apple) gpus.
I'd like to have some rules controlling the Mac Pro 7.1 fan speeds if the Nvidia gpus temperature increases.

**Comment by kleuter** [comment]
We don't plan trying to control GPU fan speed.
Supporting of displaying PCIe GPU or eGPU temperature can be considered as feature request.

**Comment by hilcam** [comment]
> **Good news** 😀
> 
> I've created a special non-Plug&Play version of the driver (AppleSMC2) for iMacPro1,1 (tested) and MacPro7,1 (not tested).
> 
> * MacBook Pro, MacBook Air and Mac mini may still use the normal AppleSMC
> * When using eGPU this driver may crash (not tested, I don't own an eGPU)
> * Works fine on my machine:
> 
> ![sshot-1](https://user-images.githubusercontent.com/2600624/77485112-9d9ab680-6e2c-11ea-9b65-43589b7a6fb9.png)
> 
> I need some time to create a test build, please be patient 😉
> 
> PS. No donation required, buying a Pro version would be fine 😋

Incredible work Kleuter! Out of curiosity what is the theoretical/actual maximum RPM the dual-fans are capable of in the iMacPro1,1?

I notice under regular operation within osX the maximum custom 'Constant RPM value' fluctuates upon each boot of Macs Fan Control.

**Comment by kleuter** [comment]
[Test build](https://crystalidea.com/downloads/macsfancontrol_setup_pro.exe), looking forward to know if it works, specially on MacPro7,1
Can be installed without uninstalling previous version.

**Comment by swheat89** [comment]
> [Test build](https://crystalidea.com/downloads/macsfancontrol_setup_pro.exe), looking forward to know if it works, specially on MacPro7,1
> Can be installed without uninstalling previous version.
> 
> > Out of curiosity what is the theoretical/actual maximum RPM the dual-fans are capable of in the iMacPro1,1?
> 
> I have 2500 max and actual is ALWAYS 1100. I'd also want to lower min fan speed from 1100 to something like 900, will test it soon.

Awesome! Got it installed and testing it now. So far so good. 
Just bought the pro version (windows and mac)
Thanks!

**Comment by 1105420698** [comment]
> > [Test build](https://crystalidea.com/downloads/macsfancontrol_setup_pro.exe), looking forward to know if it works, specially on MacPro7,1
> 
> > Can be installed without uninstalling previous version.
> 
> > 
> 
> > > Out of curiosity what is the theoretical/actual maximum RPM the dual-fans are capable of in the iMacPro1,1?
> 
> > 
> 
> > I have 2500 max and actual is ALWAYS 1100. I'd also want to lower min fan speed from 1100 to something like 900, will test it soon.
> 
> 
> 
> Awesome! Got it installed and testing it now. So far so good. 
> 
> Just bought the pro version (windows and mac)
> 
> Thanks! 

In that case, I guess I won’t be holding myself back from getting a pro version as well. Nice job!

**Comment by kleuter** [comment]
@gabrielefx could you please test? Thanks

**Comment by 1105420698** [comment]
> Great,
> 
> could you check how the Msi Afterburner app works?
> 
> For example I have one Apple Radeon Pro 580X (mpx module), two Nvidia RTX20180Tis, one Nvidia GTX1080Ti on Razer Core egpu box.
> 
> The Msi Afterburner can control all Nvidia fans speed (with curves), also reads the temperature of all gpus, 580X too, + cpu. This happ works also for AMD (not Apple) gpus.
> 
> I'd like to have some rules controlling the Mac Pro 7.1 fan speeds if the Nvidia gpus temperature increase.

Oh so it is possible to use MSI afterburner, just not for Apple’s factory AMD GPUs? No wonder why it did not work for me and I was about to give up.

**Comment by johntamch** [comment]
Thanks you for making it work for imacpro.  Just bought pro version.

**Comment by gabrielefx** [comment]
![control_fans](https://user-images.githubusercontent.com/62420123/77747992-e6ff2780-701f-11ea-92a2-22e87d0c6004.jpg)
It works like a charm!
Well done!
I immediately purchased the Pro version.

I need some improvements:
#01 renaming the fan labels, for example top CPU (Xeon), middle (Nvidia gpus), bottom (AMD gpu)
#02 Dark interface because the full white color burns the screen
#03 Curves, at the moment the speed follows another temperature (for example the cpu). I'd like to modulate this behavior.
#04 warning sound if the temperature reaches a set degrees.
#05 ramp color from the measured temperatures and fans speed: lower green, medium orange, maximum red

best regards

**Comment by hilcam** [comment]
How do we get a hold of the upgraded version that has this fix (v1.5.6?), the website still looks to have 1.5.5

**Comment by kleuter** [comment]
Thanks for the ideas! Some of them already here as separate issues. I'd be happy if you could send the Technical info from the menu More -> Copy tech info (running the app in Windows). 

Version 1.5.6 will be officially released today.

**Comment by gabrielefx** [comment]
> Thanks for the ideas! Some of them already here as separate issues. I'd be happy if you could send the Technical info from the menu More -> Copy tech info (running the app in Windows).
> 
> Version 1.5.6 will be officially released today.

[info.txt](https://github.com/crystalidea/macs-fan-control/files/4394136/info.txt)

Hi,
I uploaded the file.
I see the More command doesn't read my two RTX2080Tis, only the external one (GTX1080Ti) on Razercore thunderbolt 3 enclosure.

**Comment by kleuter** [comment]
Thanks!
