### ISSUE TITLE
qt5XXX.dll missing

### ISSUE THREAD

**Issue by corntal** [crystalidea/macs-fan-control#265]
Every time I try to install/run Macs Fan Control, I get an error saying I'm missing:

qt5Network.dll
qt5Widget.dll
qt5Core.dll
qt5GUI.dll

I have installed those .dll files and still doesn't work.

Re-installing also doesn't work.

Any help?

**Comment by kleuter** [comment]
The installer must normally copy those dll files into the program directory:
C:\Program Files (x86)\Macs Fan Control

**Comment by Svetitskiy** [comment]
> The installer must normally copy those dll files into the program directory:
> C:\Program Files (x86)\Macs Fan Control

It doesn't work installing 1.5XXX versions to Windows 10 64-bit. The last version working correctly is 1.4.2

**Comment by sampdubs** [comment]
I also had this error with the qt5 and other dlls missing. I tried downloading them all and putting them in the folder then got some weird error. Will 1.4.2 still work with t2 Macs?

**Comment by kleuter** [comment]
What files are located in the program folder?
![sshot-56](https://user-images.githubusercontent.com/2600624/72730733-3e04fe00-3b92-11ea-981f-168f9cb6ec62.png)
![sshot-57](https://user-images.githubusercontent.com/2600624/72730734-3e9d9480-3b92-11ea-82cd-29e6b81c3aaa.png)

**Comment by sampdubs** [comment]
Oh wow, I had none of those dlls.

**Comment by kleuter** [comment]
Did you have any errors during setup?

**Comment by kleuter** [comment]
https://www.crystalidea.com/downloads/macsfancontrol_setup.exe

**Comment by sampdubs** [comment]
None until it tried to run, complaining about missing dlls. I will boot into windows, uninstall, and try again.

**Comment by sampdubs** [comment]
![image](https://user-images.githubusercontent.com/40965371/72731184-08d3be00-3b48-11ea-9c2a-a20d0c711b8d.png)

This is how the install finishes, then a few other popups complaining about qt5 dlls. It still creates the program, but when I try to run that, it gives the same errors. Will 1.4.2 work with my T2 mac?
This is the install folder:

![image](https://user-images.githubusercontent.com/40965371/72731309-56502b00-3b48-11ea-84b1-7e5642b15511.png)

**Comment by kleuter** [comment]
Ok, got it now. For some reason our "unzip" didn't succeed. Can you try to disable your antivirus software and try installing again?

**Comment by sampdubs** [comment]
Hmm... I believe I have turned off my antivirus, but I'm still getting the error.
![image](https://user-images.githubusercontent.com/40965371/72732057-c7dca900-3b49-11ea-9a60-7cc175df9e95.png)

**Comment by kleuter** [comment]
Wait... do you have 32-bit Windows?

**Comment by corntal** [comment]
Is there any way to get version 1.42?

**Comment by sampdubs** [comment]
No, I'm on a 64 bit install.

**Comment by sampdubs** [comment]
https://www.crystalidea.com/macs-fan-control/release-notes

**Comment by corntal** [comment]
Well, it works for me! Hah! Thanks!

**Comment by kleuter** [comment]
Version 1.4.x will not work with the T2 chip. I'm asking you to help me figure out to solve the installer issue, which can be solved 100%.

**Comment by corntal** [comment]
Good luck gents.

**Comment by kleuter** [comment]
@corntal what did work for you?

**Comment by sampdubs** [comment]
I believe he was just saying that using version 1.4.2 worked for him, since he doesn't have a T2 chip.

**Comment by kleuter** [comment]
What is your user folder name? 
C:\Users\xxx
?

**Comment by kleuter** [comment]
Ok, couple of minutes and I'll fix it. thanks.

**Comment by sampdubs** [comment]
What needs fixing? Is it something about the space or hyphen in the name?

**Comment by kleuter** [comment]
Exactly, the space. Hold on.

**Comment by kleuter** [comment]
Please tell me if it works for you:
https://www.crystalidea.com/downloads/macsfancontrol_setup_test.exe

**Comment by kleuter** [comment]
Oops, correct link:
https://www.crystalidea.com/downloads/macsfancontrol_setup_fix.exe

**Comment by sampdubs** [comment]
Yay, that worked. Thanks so much!

**Comment by kleuter** [comment]
Perfect, will submit the fix to the official download a bit later. Thank you!

**Comment by Svetitskiy** [comment]
> Oops, correct link:
> https://www.crystalidea.com/downloads/macsfancontrol_setup_fix.exe

The installer window doesn't close. :(
![installing](https://user-images.githubusercontent.com/59328527/72781067-7a3b6b80-3c31-11ea-9946-cd908563df20.png)

**Comment by kleuter** [comment]
Reboot and start again, please

**Comment by totowit** [comment]
@kleuter Hey, this fix worked for me too! Although I dont have any space in my User Name.... Thanks though

**Comment by kleuter** [comment]
Fixed in 1.5.5
