### ISSUE TITLE
Need to permanently ignore BSOD startup message - Bootcamp 5 Win10 1903

### ISSUE THREAD

**Issue by batcomic** [crystalidea/macs-fan-control#268]
My Mac is old enough that I haven't been able to install Bootcamp 6, so the BSOD warning message pops up every time it launches. The problem is it prevents the program from running after a restart, which will cook my fragile gpu if I'm not there to acknowledge it. Is there a way to permanently ignore it so regardless the fans will run at the set speed?

**Comment by kleuter** [comment]
When you press Ignore, does Windows crash? if no, please the following file:
C:\Windows\system32\drivers\MacHalDriver.sys

**Comment by kleuter** [comment]
Must be fine in this test build:
https://www.crystalidea.com/downloads/macsfancontrol_setup_fix_2.exe

**Comment by batcomic** [comment]
That worked perfectly. Thank you so much! It now launches without having to manually click the ignore button.

**Comment by kleuter** [comment]
Thanks for confirming, the 1.5.5 version will be released soon with this fix. thanks.

**Comment by kleuter** [comment]
Fixed in 1.5.5

**Comment by kleuter** [comment]
Still an issue with MacHALDriver.sys from 12 November 2020, will be fixed
