### ISSUE TITLE
`Skip this version` does not skip the new version but reminds later with the same version

### ISSUE THREAD

**Issue by wvierber** [crystalidea/macs-fan-control#269]
Macs Fan Control 1.5.3

**Comment by kleuter** [comment]
Sorry, can't confirm that: just ran version 1.5.3, it displayed update message for 1.5.4, i skipped it and it never appeared again for the next start

**Comment by wvierber** [comment]
It wasn’t on restart that the message showed up again… Just some random moment a few days later (I did not reboot my pc between those moments)

**Comment by kleuter** [comment]
Thank you, reproduced and will be fixed in the nearest update.

**Comment by kleuter** [comment]
Fixed in 1.5.5
