### ISSUE TITLE
Macs Fan Control doesn't open.

### ISSUE THREAD

**Issue by xtrem123** [crystalidea/macs-fan-control#270]
When starting Macs Fan Control nothing happens. No window, no icon in menu.

In Activity monitor Macs Fan Control process is running.
After a while syspolicyd is spiking over 100% CPU until both processes are force quit.

MacBookPro15,2 10.15.3 beta and MacPro6,1 and 10.15.2.
MFC 1.5.3 and 1.5.4
Both computers has previously had MFC running.

**Comment by kleuter** [comment]
Are there any crash logs?
