### ISSUE TITLE
Bootcamp Win without Fan Control will fail to start fans 

### ISSUE THREAD

**Issue by gerab** [crystalidea/macs-fan-control#276]
MacBook Pro (15-inch, 2018) 10.15.2 (19C57)
Rebooting to Windows after Mac with Fan Control will leave fans dead (and opposite from Win to Mac).
I tried SMC reset, which works until the next OS switch. Then I've found out that MFC exists for Windows. But anyway it would be nice to have normal experience even without installing MFC.

**Comment by kleuter** [comment]
'dead' ?? You mean off I suppose. This model turns the fans off when in automatic mode (when the app is not running) when the computer is cool enough.

**Comment by gerab** [comment]
no, it doesn't turn off fans. Fans wouldn't turn on even when system reaches 100C

**Comment by kleuter** [comment]
Please record a video while running the app
- the app displays CPU temperature 100C
- the app displays the fan is off

**Comment by gerab** [comment]
the problem as I believe is that MFC doesn't know about the second GPU. When I set the right side fan to be triggered by GPU Proximity I mean Radeon graphics, but what I see is that it's controlled by Intel UHD which is wrong.

**Comment by gerab** [comment]
no need that. I'm pretty sure that bug could be fixed by restoring default SMC values (or whatever helper changes) on app/system shutdown, so after reboot under OS that does not have MFC default fan behavior is expected

**Comment by kleuter** [comment]
> no need that

I need that, sorry.
