### ISSUE TITLE
Cooling issue

### ISSUE THREAD

**Issue by gerab** [crystalidea/macs-fan-control#277]
MacBook Pro (15-inch, 2018)
Yesterday I had a heavy throttling issue when the laptop became very hot and started throttling to 0.7-0.8 GHz, while temperatures in the Temperature sensors list were ok (CPU and GPU around 50-60C).  Now I cannot switch to preset because I know it will fail. Is there a possibility that there is some other component that overheats and it was excluded from the list?

**Comment by kleuter** [comment]
Please make a screenshot once you experience such a situation

**Comment by gerab** [comment]
the problem as I believe is that MFC doesn't know about the second GPU. When I set the right side fan to be triggered by GPU Proximity I mean Radeon graphics, but what I see is that it's controlled by Intel UHD which is wrong.
