### ISSUE TITLE
Northbridge Overheating Problem Mac Pro 5,1

### ISSUE THREAD

**Issue by Baron-Bar** [crystalidea/macs-fan-control#28]
Overheating of the Northbridge chip on the Mac Pro 5,1 is an endemic problem in these machines. Failure of this chip is responsible for many, if not most, main board failures. The plastic clips holding the heat-sink in place are prone to deteriorate (lifetime of about 5 years) resulting in separation of the heat-sink, rapid overheating of the Northbridge chip and failure. It seems to be planned obsolescence.

This design fault (from the point of view of the user) can be repaired by replacing the clips with suitable metal bolts fitted with spring-loader washers. Every Mac Pro 4,1 and 5,1 owner should do this. However, the Northbridge still gets hot quickly, and races up to 80 degrees Centigrade and higher when the system is under load. Macs Fan Control makes it possible to keep the Northbridge cool by linking the Intake and Exhaust fans to ambient temperature and setting the maximum at 40 degrees Centigrade. This works but causes these large fans to run hard, keeping everything cool. See the screenshot. 

![macs fan control 2018-02-12](https://user-images.githubusercontent.com/36420575/36115197-a4a41f34-1032-11e8-963c-63fb95f83a18.png)

This overkill solution takes more power than necessary and is noisy. I measure 60 to 70 dB at one meter from the tower before it ramps up, and above 80 dB at load. Incidentally, one hour of exposure to 80 dB is associated with permanent hearing damage. Since my tower is on a desk one meter from where I sit this noise level is unacceptable. Furthermore, it is unnecessary; only one chip overheats. The heat-sink is clearly inadequate. A larger heat-sink will not fit, as it is partly positioned under one of the main CPU heat-sinks. 

I am looking for a better remedy. It must be possible to attach a third-party fan to the Northbridge heatsink. Would it be possible link control of a third party fan to the IOH diode reading, as this is on the Northbridge chip? Would it be possible to get a 7th fan on the application, and how could this be done? I suppose this might entail some custom hardware using one of the PCIe slots, but perhaps this could be achieved through a USB port. Any ideas. If this problem could be solved and made available to Mac Pro users, countless Mac Pros could be saved from early demise. What a great blow against the apparent planned obsolescence.

**Comment by kleuter** [comment]
Spinning Boost A fan at 2000-3000 will cool down the Northbridge die

**Comment by seanjwong** [comment]
Hi @Baron-Bar Did you find a Northbridge Heat sink that could fit ?
I'm a convert to the @kleuter Method and have set my Macs Fans to keep my Northbridge under 60ºC 
![image](https://user-images.githubusercontent.com/3635920/82457628-ff0f9680-9af8-11ea-8719-bd13d1df4a76.png)
![Mac PRo5,1 Northbridge Heatsink with Macs Fans set to 60ºC](https://user-images.githubusercontent.com/3635920/82457763-28302700-9af9-11ea-8837-28a433cf4340.png)
