### ISSUE TITLE
SMC issues just after installing Macs Fan Control

### ISSUE THREAD

**Issue by balla-999** [crystalidea/macs-fan-control#280]
Hi, i think this is a wonderful app but im having this issues just after install it, the battery indicador lights doesnt works, also the sleep mode when closing the laptop cover doesnt works.
I already reset the SMC on my laptop like shown here [https://support.apple.com/es-lamr/HT201295](url), but still doesnt works, even i reset it after uninstall Macs Fan Control, please how can i solve this issue?
thank you.
i have a MacBook Pro mid 2012, Ram: 10Gb, MacOs Catalina, i had MacOs Mojave when install macsFanControl for firs time.

**Comment by kleuter** [comment]
It cannot be related to the app, uninstall it and reset SMC.
