### ISSUE TITLE
Option to ignore wrong hardware and silently close.

### ISSUE THREAD

**Issue by MacDragon** [crystalidea/macs-fan-control#283]
I'm trying to setup a dual bootcamp/VMware, and experimenting with macs fan control, where obviously it complains under the VM instance that it's not running on a mac. For such situations it would be good to have an option to silently ignore and just close again.

 ( and also didn't realise how quick the switch to seperate license for windows/mac was going to happen, as I just missed out on it whilst waiting for new machine to experiment on! )

**Comment by kleuter** [comment]
Thanks, it's improved now and will be available in the next update (1.5.5) soon

![image](https://user-images.githubusercontent.com/2600624/75695562-90196300-5caa-11ea-888c-d6b6feacc9f4.png)

**Comment by kleuter** [comment]
Fixed in 1.5.5
