### ISSUE TITLE
Macbook Pro with MFC slows down to a crawl when using external display

### ISSUE THREAD

**Issue by crosswick** [crystalidea/macs-fan-control#287]
Please see https://superuser.com/questions/1295897/macbook-pro-very-slow-on-dual-monitor-setup/ - my experience is the same.

**Comment by kleuter** [comment]
Thermal issues are causing kernel task to preemptively use up CPU to prevent overheating. Try putting fan(s) back to auto and if it doesn't help, try to reset the SMC.

Basically you override fans with the app incorrectly and the system is overheating.
