### ISSUE TITLE
Feature request: Developer API

### ISSUE THREAD

**Issue by chendragon2099** [crystalidea/macs-fan-control#29]
Hey, just wondering if this would be a possible consideration in the future? A developer api that would let us monitor and log the temperatures and set fan speeds would be awesome for creating other desktop widgets or external data logging tools.

Thanks!

**Comment by kleuter** [comment]
Nope, it's not planned, sorry.

**Comment by kylehase** [comment]
I realized this is already closed, but wanted to add my support for this request. In my case I'd like to use some automation tool (Automator?) to recall presets based on running apps or URLs (Lightroom, Premiere, Google Meet, Zoom...)
