### ISSUE TITLE
Menu bar icon invisible when auto mode changes from light to dark

### ISSUE THREAD

**Issue by Omoeba** [crystalidea/macs-fan-control#295]
<img width="372" alt="image" src="https://user-images.githubusercontent.com/38597972/77133711-49a16380-6a21-11ea-81a0-67fa970fefe2.png">

**Comment by Omoeba** [comment]
Update: the icon is no longer invisible after a restart. This issue occurred after I installed the software when the Mac was in auto (light) mode and then it changed to auto (dark).

**Comment by kleuter** [comment]
Please make sure to be running the latest version: 1.5.5.17:
https://crystalidea.com/downloads/macsfancontrol.zip

**Comment by rogeriocsilva** [comment]
Having this issue.  Version 1.5.6 macOS Catalina
