### ISSUE TITLE
Incorrect top fan speed on 2019 16" MBP

### ISSUE THREAD

**Issue by mchasej92** [crystalidea/macs-fan-control#296]
On Windows 10 (bootcamp), MFC caps the fan speed at 5200 rpm, but this should be at 6000 rpm (for both fans). I've tested this by running a game on the Windows partition for an extended period of time (MFC running on "Full Blast" preset), then I'll immediately restart the computer and boot into macOS (the fans still running at the speed defined by MFC within Win10). Once logged into macOS, I can actually hear the fans kick into a faster speed. iStats Pro (on macOS) confirms each fan is running at their max speed, 6000rpm.

**Comment by kleuter** [comment]
Please post tech info from Windows.

**Comment by mchasej92** [comment]
I misspoke, MFC allows a maximum speed of 5616rpm for the left fan and 5200rpm for the right.

Windows 10 Pro v.1909
Build 18363.720

-Intel i9-9880H @ 2.3GHz
-Radeon 5500M 8GB

**Comment by kleuter** [comment]
Windows may have different max speed, it's set by SMC, the app simply reads it.
Max speed is also known to change from time to time by SMC.

![1](https://user-images.githubusercontent.com/2600624/77702344-943e5500-6fb8-11ea-9a0a-eb9c084be2a7.png)
