### ISSUE TITLE
Main Window Unresponsive

### ISSUE THREAD

**Issue by zecanard** [crystalidea/macs-fan-control#297]
Very minor bug with easy steps to reproduce:
1. From the menu Bar, click Macs Fan Control, then **Preferences…**
2. Again from the Menu Bar, click Macs Fan Control, but this time click **Show Macs Fan Control**.

The Macs Fan Control window appears over the Preferences window, but cannot be interacted with. You have to use Mission Control (⌃ ↑) or App Exposé (⌃ ↓) to close the Preferences window before the main window can be interacted with.

I’ve only tried this on macOS, but the problem likely exists on Windows as well.

**Comment by kleuter** [comment]
Thanks, will be fixed soon

**Comment by kleuter** [comment]
Fixed in 1.5.6
