### ISSUE TITLE
System freeze

### ISSUE THREAD

**Issue by hughster31** [crystalidea/macs-fan-control#298]
NOTE: This may not be an issue with MacsFanControl – I have seen it with the competitor (SSD Fan Control). I can use MFC for about 45 minutes, in either Auto or Custom mode, but the machine then freezes (I think this is in Custom mode only) - spinning beachball of death, and the mouse cursor then disappears, and the keyboard becomes unresponsive. With SSDFanControl this happened either at or before login or within a minute. Any clues? I isolated this as a fan control issue by booting in safe mode and manually starting the SSDFC daemon - freeze after about 5 seconds - this was repeatable).

iMac 27" Mid 2011, 10.12.6 - 16GB RAM, replacement SSD is Crucial MX500 1TB

[Macs Fan Control_2020-03-25-084819_hiyodori.wakeups_resource.diag.zip](https://github.com/crystalidea/macs-fan-control/files/4380056/Macs.Fan.Control_2020-03-25-084819_hiyodori.wakeups_resource.diag.zip)

**Comment by hughster31** [comment]
Just to let you know - I have recently rebooted from the spinning beachball and freeze after about an hour and a half of use (following an overnight sleep in which MFC was not running) with MFC running the fans at a constant speed of 3200rpm or so. Temperature never reported above 43C, typically <40C.

**Comment by kleuter** [comment]
Do you experience high CPU kernel_task usage?

**Comment by hughster31** [comment]
Currently not running any fan control software. Activity Monitor currently showing a pretty constant 6% (some peaks). Just run Macs Control software and put the fan at a constant 3800. kernel_task usage seems unchanged. MFC using about 3%. Quitting MFC - no change in CPU usage for kernel_task.
