### ISSUE TITLE
Driver installation failure

### ISSUE THREAD

**Issue by dontevenblink** [crystalidea/macs-fan-control#300]
Upon install I got the following message:

Driver installation failed with error 3758096971

followed by this:

Error initializing SMC interaction layer
Please make sure that your mac system is supported and you have correctly installed the program. 

Macs Fan Control Version 1.5.6, MBP mid-2018 (15,1), fresh install of windows 10 pro via bootcamp.

**Comment by kleuter** [comment]
The error is ERROR_FILE_HASH_NOT_IN_CATALOG
Did you have the app installed previously? 
Please reboot and try to install it again.

**Comment by kleuter** [comment]
Please re-download, it's fixed, thanks!!
