### ISSUE TITLE
Linux Support?

### ISSUE THREAD

**Issue by 1105420698** [crystalidea/macs-fan-control#315]
I understand this is a big ask and probably a terrible idea given the amount of time it might take. Linux includes most of the drivers need so I doubt there are any kernels waiting to be written. I honestly don’t know how GUI works in Linux but check out GNOME is a start. If not pure command line is fine. I would imagine porting from the MacOS version would be a strategic advantage due to the fact that they are both Unix based systems. What do you think? Please close this if you think it’s bizarre I totally understand. Currently I use a script that I got from github that allows me to automate my fans in Linux, it is working great but it does not have a GUI. MacsFanControl is already beyond Macs and the script that I got is a one file script. How hard could it be? I never developed software for Linux so I don’t know. I am just saying it would be great to have MacsFanControl on Linux as well.

(Little biased here but I use Ubuntu so I would love to have an Ubuntu version)

Also just realized that I wrote this entire issue requesting a software to be ported onto an entirely new platform and shamelessly said that it might not be hard.

**Comment by kleuter** [comment]
While it's possible, we don't plan supporting Linux. This OS cannot be official installed on mac computers. Moreover: modern macs with the T2 chip (and all future macs apparently) require extraordinary efforts to install Linux.
