### ISSUE TITLE
Occasionally, MFC for Windows forgets all stored presets, takes a long time to display fans

### ISSUE THREAD

**Issue by bradtchapman** [crystalidea/macs-fan-control#317]
Every so often on launch, MFC seems to forget all the presets I built, and also shows a blank window for at least 15 seconds.  When all fans are finally displayed, everything is set to Auto and all my presets are gone.

As a workaround, I've resorted to backing up the registry key that holds the license and presets and simply restoring them on the occasion that MFC forgets them.

<details>
Mac Pro 5,1
Dual Intel X5690
Radeon Vega 56
MFC 1.5.6 build 652
Pro version, 1 computer license
</details>

<img width="730" alt="mfc-156-win-mainwindow" src="https://user-images.githubusercontent.com/32527656/79700104-5a274280-8248-11ea-8225-00eff6e13a2c.png">

I am a paid customer of the Mac and Windows versions.

**Comment by kleuter** [comment]
Please try version 1.5.7, it must be fixed I believe! thanks.
https://crystalidea.com/downloads/macsfancontrol_setup.exe
