### ISSUE TITLE
Is it normal that MFC displays 0rpm at new MacBook Air 2020

### ISSUE THREAD

**Issue by Palinghaas** [crystalidea/macs-fan-control#318]
Yesterday I've received my brand new MacBook Air 2020 (i7/16GB/256GB setup) and because of the various remarks of high temperatures/fan speeds in reviews I've decided to install MFC to monitor the temp and speeds during usage.

Yesterday, when I was using (installing) the laptop the measures were constantly around 60/70 degrees and around 2600-3500 rpm.

However this morning I've found the laptop at lower temperatures and 0rpm fan speed (it occasionally jumps on to 2600-3500 when the temperature's rise a little). I haven't found anything so far about it being normal for these laptops to completely shutdown the fans instead of idling around 2000rpm.

I've conducted the Apple diagnostic during boot and nothing's wrong there.

Is this normal behaviour?

Thanks for your reply.

**Comment by IXueGaoI** [comment]
having the same issue, not my fan won't work until it's 60°, in MFC if I choose auto, it won't work at min rpm, most time just sit at 0 rpm...wondering if there's a way can reset the min in system?

**Comment by kleuter** [comment]
that's normal. Apple uses quite conservative fan curve where silence is more important than actual thermals. Never saw that on 15" models indeed.
