### ISSUE TITLE
The app doesn't work on iMac Pro under Windows

### ISSUE THREAD

**Issue by kleuter** [crystalidea/macs-fan-control#32]
Sad news, looks like Apple changed something, we don't currently know how to access SMC under Windows on the new iMacPro. Maybe it's not possible at all if they blocked it.
The current version (1.4.10) don't to start on this iMac on Windows with a special message.
macOS version still works fine.

**Comment by EthanWang706** [comment]
Yes, it's fan speed is very different in Windows. I can help you on testing this, I have iMac Pro, and I have installed Windows

**Comment by kleuter** [comment]
I had iMac Pro for a week, tried a lot, no luck 😢

**Comment by EthanWang706** [comment]
Maybe it's because the new security processor? or the power controller?

**Comment by EthanWang706** [comment]
Anyway, the first thing is that if you open Macs Fan control in Windows, it will first say that it is not available on iMac Pro, I an thinking that if we can get the fan speed read first, then it's easier to fix this problem.

**Comment by Carl37** [comment]
Hi again, Kleuter.
Did you try to disable the T2 chip, before attempting to access the SMC? 
Ie. starting iMac Pro, press command+R, and enter "no security" in Startup Security Utility?
The t2-chip could be stopping you from getting Macs Fan Control to work properly in Bootcamp on iMac Pro. Just a guess, but it seems a likely cause.
Detailed instructions can be found here: http://www.idownloadblog.com/2018/01/09/how-to-imac-pro-secure-boot/

**Comment by kleuter** [comment]
@Carl37 

sorry for getting back in touch so late. Unfortunately I no longer have this machine. Can you try this yourself?

Please disable T2, then just run the app using /skipcheck command line parameter

**Comment by Carl37** [comment]
Hi,

No problem, but I don't have the beta anymore. Could you make it available again (the link was taken down), and I'll give it a try.

**Comment by Carl37** [comment]
Hi,

Unfortunately, the program finds no sensors or fans, the window is completely blank. :( There goes that theory...

**Comment by kleuter** [comment]
@Carl37 thanks for the info 😞

**Comment by Carl37** [comment]
Apple just released a Bootcamp update for iMac Pro. The update fixed issues with Ethernet, graphics and audio, I wonder if also the SMC issue has been improved. Worth checking out.

**Comment by kleuter** [comment]
Thank you for the update, @Carl37 😢

**Comment by kleuter** [comment]
https://github.com/crystalidea/macs-fan-control/issues/80

**Comment by swheat89** [comment]
Any update on this? 
I’m thinking I might need to build a new windows system just because I can’t use a 3D program I need to start using (GPU intensive) on bootcamp because my temps go up to 100 degrees Celsius without being able to control the fan speed. Would be a shame to have to do this just because a fan controller doesn’t exist!
