### ISSUE TITLE
Is Macs Fan Control displaying for integrated GPU or AMD 560x? 

### ISSUE THREAD

**Issue by timjph** [crystalidea/macs-fan-control#323]
Great app, but have a question about what I am seeing.

Running Macs Fan Control 1.56 on MacBookPro 15,1 (2018 macbook pro 15 i7 6 core, 10.14.6)

I see temperature sensor readings labelled "GPU PECI" and "GPU Proximity".  
It's unclear if these are the temperatures of the integrated graphics or for the AMD Radeon Pro 560X.  The temperatures do not seem to change when the 560X is busy which makes me suspect the 560X readings might be missing.

Best wishes,

Tim

**Comment by kleuter** [comment]
It's the integrated GPU, we're working on improving that.
