### ISSUE TITLE
Crash on start on hackintosh (platform_getAvailableGPUs)

### ISSUE THREAD

**Issue by simonhepworth69** [crystalidea/macs-fan-control#324]
I'm hoping this is the correct place to write.

Trying to get this to work but open the app doesn't do anything so tried the command line and got this result

_**> 2020-04-30 18:53:40.893 Macs Fan Control[1305:58309] -[NSTaggedPointerString bytes]: unrecognized selector sent to instance 0x1ab2004f6942ca5
> 2020-04-30 18:53:40.894 Macs Fan Control[1305:58309] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTaggedPointerString bytes]: unrecognized selector sent to instance 0x1ab2004f6942ca5'
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x00007fff40c77d7b __exceptionPreprocess + 171
> 	1   libobjc.A.dylib                     0x00007fff67f35c76 objc_exception_throw + 48
> 	2   CoreFoundation                      0x00007fff40d108d4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
> 	3   CoreFoundation                      0x00007fff40bed660 ___forwarding___ + 1456
> 	4   CoreFoundation                      0x00007fff40bed028 _CF_forwarding_prep_0 + 120
> 	5   Macs Fan Control                    0x0000000103201530 _ZNK10SystemInfo25platform_getAvailableGPUsEv + 288
> 	6   Macs Fan Control                    0x00000001031d4b49 _ZN10SystemInfoC2Ev + 617
> 	7   Macs Fan Control                    0x00000001031d9183 _ZN17QMacFanControlAppC2ERiPPc + 211
> 	8   Macs Fan Control                    0x00000001031e2205 main + 373
> 	9   libdyld.dylib                       0x00007fff68b53015 start + 1
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException
> Abort trap: 6**_

Any ideas what this could be and how to fix it?

I'm on a hackintosh if that helps

**Comment by kleuter** [comment]
Please tell us the macOS version, thanks.

**Comment by simonhepworth69** [comment]
it's 10.13.6 : I suspect it might be to do with the motherboard > Gigabyte z87x-ud5h

**Comment by kleuter** [comment]
Done in #347
