### ISSUE TITLE
Issue with Macs Fan Control

### ISSUE THREAD

**Issue by splittest** [crystalidea/macs-fan-control#328]
I want to mention I previously had no issues with Macs Fan Control. It seems the issue only started happening once I upgraded to the newest version. 

I usually use the automatic setting, but occasionally the fans will start to spin really high and stay there even when the temps are relatively low (60C) and cpu usage is low.

I also have an issue with the Custom setting using CPU/GPU PECI sensors at 40C-90C which works fine initially. Occasionally my macbook temps will spike as well as Kernel Task using up most of my cpu rendering the laptop useless.

The issues seem to go away after quitting Macs Fan Control. Does anybody have an idea of what is going on? My Macbook is clean and free of dust.

**Comment by kleuter** [comment]
![image](https://user-images.githubusercontent.com/2600624/81664841-336fbc80-9440-11ea-978f-25185a6ea0e0.png)

https://crystalidea.com/macs-fan-control/faq
