### ISSUE TITLE
I have issue 1.5.6, and i am operating a mac with 10.13.6. My fan runs at very high speed at random times.

### ISSUE THREAD

**Issue by Dennisjlittle** [crystalidea/macs-fan-control#330]

**Comment by kleuter** [comment]
You you'd like to report a bug, please include technical information from the menu "More" -> "Copy technical info". Please do not forget to put technical info inside the details tag:
<details>
YOUR TECH INFO
</details>
Screenshot of the main window of Macs Fan Control is highly appreciated as well.

**Comment by Dennisjlittle** [comment]
Hello again,

macs-fan-control] I have issue 1.5.6, and i am operating a mac with 10.13.6. My fan runs at very high speed at random times. (#330)

I had the above problem with my Macs Fan Control but it seemed to have healed itself.

The problem has now resurfaced.

It seems at random times, I come into my office and fans are running at very high speed.

I click the Fan control icon and the chart of speeds etc appears on mt screen, then the the fan speed falls back to low speed.

I am concerned that this high speed running issue could occur at night or when I am away and it could cause damage too the mac.

All my details are in the above reference.

I would appreciate some advice.

Thank you

Dennis Little

**Comment by Dennisjlittle** [comment]
> Begin forwarded message:
> 
> From: Dennis Little <dandblittle@gmail.com>
> Subject: Re: [crystalidea/macs-fan-control] I have issue 1.5.6, and i am operating a mac with 10.13.6. My fan runs at very high speed at random times. (#330)
> Date: 29 May 2020 at 11:53:01 BST
> To: crystalidea/macs-fan-control <reply@reply.github.com>
> 
> Hello again,

I have included a screen shot.
> 
> macs-fan-control] I have issue 1.5.6, and i am operating a mac with 10.13.6. My fan runs at very high speed at random times. (#330)
> 
> I had the above problem with my Macs Fan Control but it seemed to have healed itself.
> 
> The problem has now resurfaced.
> 
> It seems at random times, I come into my office and fans are running at very high speed.
> 
> I click the Fan control icon and the chart of speeds etc appears on mt screen, then the the fan speed falls back to low speed.
> 
> I am concerned that this high speed running issue could occur at night or when I am away and it could cause damage too the mac.
> 
> All my details are in the above reference.
> 
> I would appreciate some advice.
> 
> Thank you
> 
> Dennis Little



> 
>

**Comment by kleuter** [comment]
I don't see any screenshot, unfortunately.

**Comment by Dennisjlittle** [comment]
Screen shot.
Hope this is OK

**Comment by kleuter** [comment]
I don't see any screenshot, unfortunately.

**Comment by kleuter** [comment]
Don't reply with email, but attach a screenshot using the web browser

**Comment by Dennisjlittle** [comment]
Did you get my screen shot this time ?

Dennis

**Comment by kleuter** [comment]
No, attach a screenshot using the web browser

**Comment by Dennisjlittle** [comment]
How do I do that?

Dennis

**Comment by Dennisjlittle** [comment]
How do I send a screen shot from web browser?

**Comment by Dennisjlittle** [comment]
Hello,

I  have given up now With trying to make the application function properly.

Can you please tell me how I uninstall it. I cannot find a way to do it and there is little help on the net.

I am operating a Mac with 10.13.6 

Thank you

Dennis little

**Comment by kleuter** [comment]
https://crystalidea.com/uninstall
