### ISSUE TITLE
Ignore SSD temp, leave everything else on auto

### ISSUE THREAD

**Issue by Ivar9000** [crystalidea/macs-fan-control#338]
Hi, 

I recently bought an old MacMini (4,1, from 2010) for a project. I'm running macOS High Sierra, but planning to upgrade to Catalina. The previous owner had replaced the hard drive with an SSD without transferring the temperature sensors, so the fans were at full speed before i got Macs Fan Control running. Thanks!
For my use case, what I really need is just an option to ignore the temperature of the SSD, and adjust the temperature based on all other sensors. As it is now, as far as I understand, I have to select one sensor to control fan speed. I picked "CPU diode", but what if the memory or AirPort card gets really hot?
It wold be great to have an "fully automatic, but disregard the SSD" option.
All the best.

**Comment by kleuter** [comment]
It's out of scope, unfortunately. We plan on adding multiple sensors for controlling it won't be "fully automatic, but disregard the SSD" anyway
