### ISSUE TITLE
Remove "always on top" behaviour

### ISSUE THREAD

**Issue by EverydayApps** [crystalidea/macs-fan-control#343]
By default the software seems to always run on top of other app frames. I'm maybe missing a setting, but it seems to always want to be on top.  This is mildly frustrating.  It's not core functionally, but please fix.  It's very upsetting.  Been running the software for about six months now, and every time I open it up, it's Jackie-Chan-But-Why.jpg.

**Comment by kleuter** [comment]
It's not currently possible to switch this behavior off, but we'll improve that in future, thanks.

**Comment by kleuter** [comment]
Indeed this behaviour is not common for a menu bar app and it will be removed

**Comment by kleuter** [comment]
Not resolved issues: macOS 10.13 - window activate issue, macOS 10.14 - window activate issue on first start
