### ISSUE TITLE
After 10.15.5 update

### ISSUE THREAD

**Issue by nkarabulut** [crystalidea/macs-fan-control#344]
Hi,
It was working very well in version 10.15.4 Catalina. But after upgrading to 10.15.5 Catalina version, it runs the fans at the highest speed very fast. For example, when I set it between 50-60 degrees, the fans run at 5k rpm when it is 51 degrees. After a little over 50 degrees, the fans run at top speed immediately. I think it needs to be checked. In general, the program worked very well.

**Comment by nkarabulut** [comment]
Meanwhile I am using the newest version. I updated but nothing has changed. Thanks.

**Comment by kleuter** [comment]
You you'd like to report a bug, please include technical information from the menu "More" -> "Copy technical info". Please do not forget to put technical info inside the details tag:
<details>
YOUR TECH INFO
</details>
Screenshot of the main window of Macs Fan Control is highly appreciated as well.
