### ISSUE TITLE
Windows RDP: LoadLibrary failed with error 87: The parameter is incorrect

### ISSUE THREAD

**Issue by SequoiaDu** [crystalidea/macs-fan-control#345]
Running Macs Fan Control in Windows Server which is managed remotely through RDP. After updating to  1.5.7, the program will not start with an error message "LoadLibrary failed with error 87: The parameter is incorrect". If I disable the display adapter, the program will start and will continue running if I re-enable the display adapter.

**Comment by kleuter** [comment]
Which display adapter? Can you record a video?

**Comment by SequoiaDu** [comment]
It's an AMD Radeon HD 6630M. After I tried to launch Macs Fan Control, it just immediately popped up the error message.

**Comment by kleuter** [comment]
Please record a video.
