### ISSUE TITLE
Error Initializing SMC Interaction Layer on MFC 1.5.7

### ISSUE THREAD

**Issue by MacBoi8623** [crystalidea/macs-fan-control#346]
Hello there, I'm on a macbook air 13.3" and I use bootcamp. I deleted the MacOS partition because i was low on storage. So I only have windows installed. I am on Windows 10 and i had this issue on 1.5.6 too. I formatted my pc and it got fixed. I formatted it 3 days ago. But just right now i got the error again. Please help my fans are stuck at 6500rpm.

**Comment by kleuter** [comment]
Log file, please.

**Comment by MacBoi8623** [comment]
> Log file, please.
Oh i’m sorry i forgot the issue was up. I found why it was happenning. Faceit anticheat thinks this program is a cheat. Thanks for the quick response though. 👍🏻
