### ISSUE TITLE
Macs Fan control under windows10 on macbook 5,1 late 2008 unibody

### ISSUE THREAD

**Issue by Avocado201** [crystalidea/macs-fan-control#357]
Have the current 1.5.7 keeps popping up a message telling me I need to use bootcamp 6 or later, however the hardware requires older bootcamp to work. Macs fan does continue to run but I have to keep clearing the warning message. How do disable it?

**Comment by kleuter** [comment]
Please upload somewhere this file (zipped):
C:\Windows\System32\drivers\MacHALDriver.sys

**Comment by Avocado201** [comment]
[MacHALDriver.sys.zip](https://github.com/crystalidea/macs-fan-control/files/4795138/MacHALDriver.sys.zip)
Thanks for taking a look. It does work though just I have to clear the message.This file is showing s version 6.200.1.5.

**Comment by kleuter** [comment]
Thanks. 
- Does the app works fine if you press the Ignore button?
- What is your Windows 10 version? 1903? 1909?

**Comment by Avocado201** [comment]
Hello, I have 1909, build 18363.900. Yes it does appear to work fine when I select ignore. Is there a way to block/ remove the message?
