### ISSUE TITLE
Mac fan control conflict with Lacie 2big on High Sierra

### ISSUE THREAD

**Issue by eazanotti** [crystalidea/macs-fan-control#362]
[MacsFanControl.log](https://github.com/crystalidea/macs-fan-control/files/4836583/MacsFanControl.log)
Guys, sorry, but I am pretty new here and no idea how to proceed in this page, so really sorry to mess up with your orientation to post.
I cannot open the Man Fan Control, but I have just downloaded the proper version to may iMac late 2012 21,5pol runing High Sierra.
I have a partition with montain lion using for years with Mac Fan Control with no problem, how ever, since las weekend, I opened a partition and installed the high sierra and testing it. Yesterday I installed the Mac Fan Control and my Thunderbolt Lacie ext HD simply disconected and when I started the imac, when opened the finder, the drivers showed no information before disconect again.
 So I am leaving without the fan control.
I had checked the log option so I attached two log from the app.
[MacsFanControl.log](https://github.com/crystalidea/macs-fan-control/files/4836606/MacsFanControl.log)
If you can help me, it would be great.
Thanks

**Comment by kleuter** [comment]
Please reopen the issue if it happens again with the latest version of the app. Thanks.
