### ISSUE TITLE
Macs Fan Control Doesn't Launch on MacOs BigSur

### ISSUE THREAD

**Issue by ankur1674** [crystalidea/macs-fan-control#363]
The App is Installed and is also shown in the spotlight but when launched, the app does nothing. It does not open at all.

**Comment by kleuter** [comment]
Check crash reports, please:
https://bjango.com/help/crashlogmac/

**Comment by ankur1674** [comment]
> Check crash reports, please:
> https://bjango.com/help/crashlogmac/

Checked the logs, uninstalled and installed it again. The app is opening fine now, but I don't see any temperature being lowered. Should the app be recompiled for Big Sur?

**Comment by kleuter** [comment]
Screenshot please?
