### ISSUE TITLE
App doesnt completely shutdown on restart

### ISSUE THREAD

**Issue by emzarate** [crystalidea/macs-fan-control#369]
While using macsfancontrol on windows 10 bootcamp and having the settings on full blast, whenever i select restart in windows 10, macsfancontrol continues to run on full blast even if my laptop boots to mac OS

it requires a shutdown to close macsfancontrol completely

is there anyway to fix this?

**Comment by kleuter** [comment]
Are you using version 1.5.7 on Windows?

**Comment by emzarate** [comment]
yes, im using that version

i was able to solve the problem by turning on MFC manually upon boot up, and on restart, it shuts down

 but whenever MFC is set to start on boot by ticking the box in the options menu, the problem persist, albeit, not always.

**Comment by kleuter** [comment]
Should be fine with 1.5.8, reopen if not, please.
