### ISSUE TITLE
No sensor data for CPU Core 1

### ISSUE THREAD

**Issue by mastak07** [crystalidea/macs-fan-control#37]
Hi there,

When running Macs Fan control on my 2013 15" Retina I get not mention of CPU Core 1 or sensor data.

I have used Tech tools and ran the apple hardware test and not found an issue. 

Do you think I may have had damage somehow to that sensor?

Thankyou for such a cool app by the way! 

Cheers, Karl

**Comment by kleuter** [comment]
Please post technical information from the preferences dialog and screenshot.

**Comment by Xavion** [comment]
I'm having this problem as well with MFC v1.5.4 on my late-2013 15" Retina.

> Please post technical information from the preferences dialog and screenshot.

Which preferences dialog are you talking about (i.e. MFC's or "System Preferences")?  Perhaps you meant the "System Information" dialog instead.

I have attached a screenshot of the main window below.  As you can see, the "CPU Core 1" entry is missing.
<img width="905" alt="MFC-Main" src="https://user-images.githubusercontent.com/334557/73418034-defb7200-4365-11ea-98d1-490b7a61c033.png">
