### ISSUE TITLE
Add option to start minimized

### ISSUE THREAD

**Issue by xfechx** [crystalidea/macs-fan-control#378]
Would be great if we could open the program and it just stay in the system tray, with the last saved speed automatic. Rather than opening the program window.

Reason behind this: some people like me, we use our macs in clamshell mode and hooked to a TV for gaming for example. Usually game controllers can move mouse only on apps that are not run as admin or with admin privileges. As soon as an app like that is opened by the mouse controlled by the game controller, it doesn't respond to the mouse anymore. So it is useful when apps add this feature, as it is only like a ON switch when launched and can keep the window minimized in tray.

**Comment by kleuter** [comment]
https://crystalidea.com/macs-fan-control/command-line

**Comment by kleuter** [comment]
![image](https://user-images.githubusercontent.com/2600624/94907943-39bf0d80-04a1-11eb-943c-46bcaceaafe1.png)

**Comment by xfechx** [comment]
This option does not entirely solve the problem. As the option is to "Autostart" minimized. Which is different than "start" minimized. 

Some people (like me) do not want to have the program autostart with Windows. In my case, I like to click the button to start the program, only when I will be playing games. 

So for example, I would like to just click on the Macfanscontrol app, and forget about it, I don't need to be looking at the home screen for the app. And at the same time, I don't want to have the app start by itself. 

So your checkbox does two things at once, I think a better design would be to have an option to "autostart with system" and an option to "start minimized".

**Comment by kleuter** [comment]
https://crystalidea.com/macs-fan-control/command-line
