### ISSUE TITLE
[macOS] Update icon for macOS Big Sur?

### ISSUE THREAD

**Issue by ghost** [crystalidea/macs-fan-control#379]
Suggestion to update the icon of the macOS version of Macs Fan Control to match the new macOS Big Sur icon style?
Proposed new icon: https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Macs_Fan_Control.icns

**Comment by kleuter** [comment]
Dear sir,

Thanks a lot for the proposal! We'll discuss and possibly add the new icon for Big Sur.

**Comment by kleuter** [comment]
Done in 1.5.8
