### ISSUE TITLE
Max RPM fluctuation, Windows 10

### ISSUE THREAD

**Issue by IV-EV** [crystalidea/macs-fan-control#380]
For some reason when in windows, the max RPM value fluctuates between 2560 and 3500 seemingly at random. It's tayed at 2640 for 2 days, but before that it was at 3450 and cooled much better. Is there some sort of command I can run to set the max RPM? For the record, I only use Windows 10 (May 2020 update, v2004).

[tech_info.txt](https://github.com/crystalidea/macs-fan-control/files/5089558/tech_info.txt)

**Comment by kleuter** [comment]
It's not a bug, min/max RPM values are set automatically by the SMC. Currently the app is not able to modify those (which can be very dangerous!).

One more report from a customer:

> I have a Mac mini 8.1 and of course I use your fan tweaker. The problem is when I user multiple environment macOS and Windows the program can reads the maximum value from smc is 4400 RPM. it is slow because the cpu is overheating. When I reset SMC and go and logging first in the macOS. The read value is 5000 rpm and it is stayed cool of the system.

**Comment by EduRi7** [comment]
I have the exactly same issue here. Mine is an iMac 12,2 (mid 2011), i7-2600, with nvidia card swap and opencore.
Each time I start windows, it shows a different value for maximum RPM like this:

![mac frio](https://user-images.githubusercontent.com/78210848/106271387-3567ee80-620e-11eb-926c-f2e09d46e7ee.png)
![input32](https://user-images.githubusercontent.com/78210848/106271391-36991b80-620e-11eb-9d55-51f37ba677c6.png)

The same occours with CPU Fan (between 2100 and 2800rpm)

Despite it's beeing set by SMC, can I simply put the correct maximum rpm somehow?

**Comment by EduRi7** [comment]
Imediately after a SMC reset, it brings different numbers:

![smc](https://user-images.githubusercontent.com/78210848/106273734-e91ead80-6211-11eb-9b54-40aab2a57cf4.png)

**Comment by iFeel91** [comment]
I have a similar problem on iMac 12.2. The maximum speed of the fans is lower in the program than it should actually be. iStat detects the speed correctly. The situation occurs on windows and macOS

**Comment by kleuter** [comment]
It's not a problem - it's the way how SMC works.
