### ISSUE TITLE
app is freezing

### ISSUE THREAD

**Issue by sebaxaki** [crystalidea/macs-fan-control#381]
I have problem with this app ... when go to set manual the fans .. I take a screen as the attachmenet .. and when login the app is freezing.. My system is Imac (9.1 early 2009 with El capitan)
![Screen Shot 2020-08-17 at 12 06 39](https://user-images.githubusercontent.com/23407186/90382196-1a058e80-e087-11ea-9b35-a50be4746b7d.png)

**Comment by kleuter** [comment]
Did you enter a correct password?

**Comment by sebaxaki** [comment]
surely...
sometimes the HDD fan control is blocked.... After reset SMC.. it work for a little and  again freeze.
For this I installed ver 1.44 ...

**Comment by kleuter** [comment]
Our app is Macs Fan Control (not HDD fan control), please uninstall this app if you'd like to use Macs Fan Control.

**Comment by sebaxaki** [comment]
Not understood ... I have not install HDD fan control. I mean the subcategory of macs fan control HDD
![Screen Shot 2020-09-02 at 13 42 32](https://user-images.githubusercontent.com/23407186/91971669-3f9ac500-ed22-11ea-88a9-bd277bbb0857.jpg)

**Comment by kleuter** [comment]
Does the most recent version of the app (1.5.7) freeze? if yes, how do I reproduce it? Can you at least record a video? Thanks.
