### ISSUE TITLE
Fan Control Win 10 Bootcamp (iMac 2020)

### ISSUE THREAD

**Issue by Rossh51** [crystalidea/macs-fan-control#382]
Hi
Two issues:
1. Can't see a way to download the Pro version for Windows ( I have the Mac version and licence for both). 
2. I am not seeing any sensors except SSD. This is on a new 2020 iMac so wondering if it may not be supported yet?
Thanks

**Comment by kleuter** [comment]
Please run the complete command 
`ioreg -l > output.txt`
and post here output.txt

**Comment by Rossh51** [comment]
Output.txt as requested. Also two screenshots one with tickbox on Discrete GPU's in Prefs and one with tickbox cleared. Note that MFC is working normally with this unticked.
[output.txt](https://github.com/crystalidea/macs-fan-control/files/5120478/output.txt)
![Screen Shot 2020-08-25 at 8 13 56 am](https://user-images.githubusercontent.com/44332031/91102203-120fa500-e6ac-11ea-847f-5b94d4e6ecb9.jpg)
![Screen Shot 2020-08-25 at 8 14 18 am](https://user-images.githubusercontent.com/44332031/91102224-1b007680-e6ac-11ea-9903-07703eef1947.jpg)
