### ISSUE TITLE
If I quit MFC, do Apple's fan parameters automatically take over? Is there any way to use the temp reading without having MFC control the fans? thank you

### ISSUE THREAD

**Issue by evanDove** [crystalidea/macs-fan-control#384]
If I quit MFC, do Apple's fan parameters automatically take over? Is there any way to use the temp reading without having MFC control the fans? thank you

**Comment by zecanard** [comment]
Leave it on Automatic.

**Comment by kleuter** [comment]
Updated [the page](https://crystalidea.com/macs-fan-control) on that:
![image](https://user-images.githubusercontent.com/2600624/91052369-a7198c00-e621-11ea-8e70-6162ccd270bc.png)

**Comment by evanDove** [comment]
Thank you so much for that concise and comprehensive reply. aloha, evan 😊
