### ISSUE TITLE
Dangerous behavior: Macs Fan Control doesn't always reset fan control to automatic upon restart 

### ISSUE THREAD

**Issue by egalitarian** [crystalidea/macs-fan-control#387]
I've experienced a very strange behavior twice. I wanted to install Mojave on a separate partition to test something. My Macbook was running Mojave with Macs Fan Control with a preset driving the fan speed from the CPU Proximity Sensor (30C-80C). After I've downloaded the installer and rebooted during the installation the Macbook got very hot. I couldn't tell the temperature because the OS installer was running but the top right metal part of the keyboard was so hot it was impossible to touch and the worst part is that the fan was not running or running very slowly (my guess is that was at the speed left from Macs Fan Control before the reboot). The install process was also running super slowly probably due to some thermal throttling. I stopped the computer and let it cool down for a while. To test I went back to the old Mojave installation and set the fan to maximum speed and rebooted. Even **after** the reboot the fan continued blowing with maximum speed suggseting that somehow Macs Fan Control doesn't revert fan control to automatic uppon reboot which I didn't even tought that is possible.

This to me is a very dangerous behavior. If one forgets to set fan control back to automatic before running an update or OS resintall this could verry well lead to a damaged computer.

Please let men know if this is expected behavior or if not what I can I do test further this issue?

Notice: I didn't post the technical info because I got wraning "the body is too long".

**Comment by kleuter** [comment]
![sshot-22](https://user-images.githubusercontent.com/2600624/91667991-f0c61300-eb08-11ea-8ce1-ac11de7365ec.png)

[Source](https://crystalidea.com/macs-fan-control)

**Comment by egalitarian** [comment]
Well, that's the whole issue. I'm afraid it doesnt't always restore fan back to Auto. The way I tested this is the following: I'm setting the fans to full speed in Macs Fan Control then I reboot and the fans continue blowing at full speed.  I can record a video to prove it if you like.

**Comment by kleuter** [comment]
Please record a short video, that would be awesome. Try to quit the app manually as well before reboot.

**Comment by kleuter** [comment]
>Notice: I didn't post the technical info because I got wraning "the body is too long".
You can zip it, upload and post a link. Thanks.

**Comment by egalitarian** [comment]
Here's a link to the video I've just recorded: https://streamable.com/j2urq2
It's recorded on a freshly installed Catalina without any other software installed except Macs Fan Control. I've also attached the technical info.
[technical info.zip](https://github.com/crystalidea/macs-fan-control/files/5147443/technical.info.zip)

**Comment by kleuter** [comment]
Thanks, will update this issue as soon as I reproduce it.

**Comment by egalitarian** [comment]
Thanks. I hope it's fixed soon as I nearly fried my computer.

**Comment by kleuter** [comment]
Must be fixed in 1.5.8 beta now:
https://github.com/crystalidea/macs-fan-control/issues/347
