### ISSUE TITLE
Error -60006

### ISSUE THREAD

**Issue by Alejandrovt1** [crystalidea/macs-fan-control#391]
# 
<img width="426" alt="Screen Shot 2020-09-06 at 2 04 43 AM" src="https://user-images.githubusercontent.com/70826865/92316308-5414e100-eff2-11ea-826b-24e632c88d6f.png">

**Comment by kleuter** [comment]
Just enter your the password if you'd like to use custom fan control.
If the app crashed, please send us the crash report.
https://bjango.com/help/crashlogmac/
