### ISSUE TITLE
Macs Fan Control is not opening up

### ISSUE THREAD

**Issue by bkrolex** [crystalidea/macs-fan-control#393]
It was working well for a few days then all of a sudden the app will not open nor do I see it at the top right corner of my screen (iMac)

**Comment by kleuter** [comment]
mac model? Crash report?
https://bjango.com/help/crashlogmac/

**Comment by dp3lw** [comment]
I have the same issue on my MacBook Pro running High Sierra 10.13.6.  Nothing is showing up under Library/Logs/DiagnosticReports either under my local account or under the main disk.

**Comment by dp3lw** [comment]
Here is my screen.

<img width="1300" alt="Screen Shot 2020-09-29 at 8 26 56 AM" src="https://user-images.githubusercontent.com/38914358/94571951-b9dd3d00-022d-11eb-8bf4-66926b49923b.png">
<img width="1271" alt="Screen Shot 2020-09-29 at 8 27 42 AM" src="https://user-images.githubusercontent.com/38914358/94571970-bd70c400-022d-11eb-8c87-6beea6591275.png">

**Comment by dp3lw** [comment]
Looks like I didn't update it properly and was still trying to run 1.5.7.20.  I redownloaded from the GitHub page and I was Able to run 1.5.8.22.

Sorry about that.

Larry
C: 587-224-6737
H: 403-247-1435
larry.williams@shaw.ca




On Sep 29, 2020, at 8:30 AM, Kleuter <notifications@github.com> wrote:


Does it appear in the Activity Monitor?
