### ISSUE TITLE
Windows XP installation not working - MacsFanControl not usable

### ISSUE THREAD

**Issue by flegomatix** [crystalidea/macs-fan-control#398]
- Mac Pro 2013
- Windows XP Home Edition Version 2002 SP3
- Error when installing: Installation starts, runs through til "Initializing..." and then crashs with message (at my computer in German as I am from Germany, but I try to translate to English below: 

"Datei kann nicht ausgeführt werden:
C:|Programs|Macs Fan Control|MacsFanControl.exe

ShellExecuteEx schlug fehl; Code 193.
%1 ist keine zulässige Win32-Anwendung"

"File cannot be executed:
C: | Programs | Macs Fan Control | MacsFanControl.exe

ShellExecuteEx failed; Code 193.
% 1 is not a valid Win32 application"

**Comment by kleuter** [comment]
It's not a crash, it's an error message. The app should be working fine

**Comment by flegomatix** [comment]
Sorry, no. 
The application crashs and does not start at all.

**Comment by kleuter** [comment]
Can you please try to manually extract this archive and run the app, please?
[macsfancontrol_xp.zip](https://github.com/crystalidea/macs-fan-control/files/5326317/macsfancontrol_xp.zip)

**Comment by kleuter** [comment]
https://crystalidea.com/blog/drop-windows-xp-vista
