### ISSUE TITLE
I just down graded to 1.5.7 as I had the same problem with 1.5.8. No SMC reset, just deleted the update & re-installed the older version from a backup.

### ISSUE THREAD

**Issue by lucoflove** [crystalidea/macs-fan-control#404]
I just down graded to 1.5.7 as I had the same problem with 1.5.8. No SMC reset, just deleted the update & re-installed the older version from a backup.

_Originally posted by @npglambert in https://github.com/crystalidea/macs-fan-control/issues/402#issuecomment-700255394_
I have delete the 1.5.8 version and the others, and re installed from backup like you did.
Unfortunately the icon is back in the traybar but no longer shows any fan speed, nor the temperatures as seen before. At this point I also doubt how it works.

**Comment by kleuter** [comment]
Did you do SMC reset?

**Comment by lucoflove** [comment]
Yes, I have. But nothing happened. Everything as before.

**Comment by kleuter** [comment]
Please stop creating new issues.
