### ISSUE TITLE
Menu bar text cut when temp reaches 100ºC

### ISSUE THREAD

**Issue by laureanorp** [crystalidea/macs-fan-control#405]
Using macOS 10.15.7 on a 2020 MacBook Air with latest MFC version 1.5.8. I've been experiencing this for a while

<img width="183" alt="image" src="https://user-images.githubusercontent.com/14150766/94839770-c1603a00-0417-11eb-922d-b4436460a5b5.png">

**Comment by christopheraram** [comment]
With the latest update (1.5.9) it appears that the temperature unit of measure gets occasionally cut off once a certain combination of "wider" characters get used for the RPM/TEMP. I had not noticed this in any previous release, and my computer doesn't have to reach 100ºC to replicate the issue.

<img width="134" alt="Screen Shot 2021-04-17 at 12 06 40 PM" src="https://user-images.githubusercontent.com/3150351/115119562-004e7b00-9f77-11eb-850f-f243157c95f7.png">

**Comment by tiziano149** [comment]
Same issue, happens at every temperature for me, running BigSur 11.2.3 with MFC 1.5.9: 
![Bildschirmfoto 2021-04-25 um 12 58 20](https://user-images.githubusercontent.com/16635297/116090094-cd596500-a6a3-11eb-939b-d6b6650baf6a.png)

**Comment by kleuter** [comment]
Should not happen with the latest version
