### ISSUE TITLE
[Big Sur Beta 9] Text shifted slightly upwards

### ISSUE THREAD

**Issue by fbnk** [crystalidea/macs-fan-control#408]
Since I installed the beta of macOS Big Sur, the text for displaying temperature and rotation speed in the two-line display is a bit too high. In the single-line view everything is vertically centered.
<details>
MacBook Air 2020 - Big Sur Beta 9 (20A5384c)

Macs Fan Control 1.5.8 [Qt 5.13.2]
MacBookAir9,1
CPU: Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz [4 cores]
macOS 10.16.0
</details>
<img width="509" alt="Bildschirmfoto 2020-10-04 um 09 49 51" src="https://user-images.githubusercontent.com/13615809/95010273-343fff80-0628-11eb-9d23-db5d4c67a3ee.png">

**Comment by kleuter** [comment]
Please post tech info and app screenshot as described at #407
Thanks!

**Comment by fbnk** [comment]
Sure, there you go. Thanks in advance!

[Tech_info.docx](https://github.com/crystalidea/macs-fan-control/files/5323604/Tech_info.docx)
<img width="831" alt="Bildschirmfoto 2020-10-04 um 18 25 33" src="https://user-images.githubusercontent.com/13615809/95021126-7b9dae80-066f-11eb-955e-4abd80109c26.png">

**Comment by kleuter** [comment]
Please try the latest [dev build](https://crystalidea.com/downloads/macsfancontrol_dev.zip)

**Comment by fbnk** [comment]
@kleuter 
It worked! Thank you for the quick help :)

**Comment by tiziano149** [comment]
please reopen this issue, the icon is now shifted sideways:
![Bildschirmfoto 2021-04-25 um 12 58 20](https://user-images.githubusercontent.com/16635297/115990897-13d89200-a5c6-11eb-9ec4-cf94c6b8e85d.png)
