### ISSUE TITLE
The latest version number is a bit unclear

### ISSUE THREAD

**Issue by cdwmhcc** [crystalidea/macs-fan-control#409]
The two previous versions are: 1.5.8.21/1.5.8.22
The latest version is: 1.5.8.1.26

1.5.8.1.26 < 1.5.8.21

Why?

**Comment by kleuter** [comment]
21,22,26 are build numbers on macOS only.

**Comment by kleuter** [comment]
> 1.5.8.1.26 < 1.5.8.21
 
True, but 1.5.8.1 > 1.5.8, there too small changes to release 1.5.9 yet.

**Comment by cdwmhcc** [comment]
> 21,22,26 are build numbers on macOS only.
> Latest version is 1.5.8.1

If so, your version management on macOS is wrong. 

Previous version：
![image](https://user-images.githubusercontent.com/8030134/95071324-0c41c080-073c-11eb-9e60-4dd44f57f8e6.png)

The latest version:
![image](https://user-images.githubusercontent.com/8030134/95071353-1663bf00-073c-11eb-9d73-093d0e532fd8.png)

**Comment by cdwmhcc** [comment]
I think this is correct:

![image](https://user-images.githubusercontent.com/8030134/95071707-adc91200-073c-11eb-988d-14937179ea71.png)

**Comment by kleuter** [comment]
Maybe 1.5.8.1 build 26?

**Comment by kleuter** [comment]
![image](https://user-images.githubusercontent.com/2600624/95072664-d1c02f80-070b-11eb-80c2-0c747cc76a66.png)

**Comment by cdwmhcc** [comment]
Yeah!

![image](https://user-images.githubusercontent.com/8030134/95074107-8e33e880-0740-11eb-93a2-87a994405273.png)

**Comment by cdwmhcc** [comment]
What the user showed was: `CFBundleShortVersionString`
The actual version is: `CFBundleVersion`

This is the version rules in the Mac App Store

Example: Apple `Note.app`

<key>CFBundleShortVersionString</key>(version)
<string>4.7</string>
<key>CFBundleVersion</key>(build)
<string>1111.23</string>

Publish on third-party websites:

Note 4.7 (1111.23)
Note 4.6 (1111.01)
Note 4.5.1 (1110.19)
Note 4.5 (1110.18)


Macs Fan Control 1.6.0 dev (300)
Macs Fan Control 1.5.9 beta (230)
Macs Fan Control 1.5.8.1 (226)
Macs Fan Control 1.5.8 (222)
Macs Fan Control 1.5.8 (221)
Macs Fan Control 1.5.7 (198)
Macs Fan Control 1.0.0 (1)

This looks very clear.

**Comment by kleuter** [comment]
Thanks, updated those numbers, please re-download:
https://crystalidea.com/downloads/macsfancontrol.zip
