### ISSUE TITLE
[Big Sur] Menu bar icon more space saving

### ISSUE THREAD

**Issue by fbnk** [crystalidea/macs-fan-control#412]
Under Catalina I didn't notice that so much, but with Big Sur the icon wastes space. I'm aware that under Big Sure the icons are all a bit further apart, but I think the screenshots show the point quite well.

Maybe you can make the whole thing a bit more space-saving. Still thanks for the great program!

fbnk
<img width="916" alt="Bildschirmfoto 2020-10-09 um 08 04 20" src="https://user-images.githubusercontent.com/13615809/95549280-42669500-0a07-11eb-8273-bda6870bf0b4.png">
<img width="913" alt="Bildschirmfoto 2020-10-09 um 08 04 45" src="https://user-images.githubusercontent.com/13615809/95549284-4397c200-0a07-11eb-94ca-20706b4fab55.png">

**Comment by CasualDeveloper** [comment]
Seconded - the app wastes too much menu bar space even on a 16" MacBook Pro

**Comment by NeXrom** [comment]
when is this beta, final? I Don't want to use the beta 👯

**Comment by kleuter** [comment]
Very soon
