### ISSUE TITLE
iMac13,2 minimum fan speed bug

### ISSUE THREAD

**Issue by sccapstick** [crystalidea/macs-fan-control#413]
Macs Fan Control thinks iMac13.2 minimum fan speed is 1920 rpm, but (see screenshot) automatic minimum is 1,200 rpm.

Thanks, plan to buy Pro version once it is working. 

![Screen Shot 2020-10-09 at 9 48 18 AM](https://user-images.githubusercontent.com/72613955/95590871-962bab00-0a14-11eb-900b-3ce2a2978c27.png)

**Comment by kleuter** [comment]
min/max/current fan speed are read from SMC

**Comment by sccapstick** [comment]
Thanks, iStat menus was installed when I installed MFC, but I have since uninstalled it as I like MFC better. I will reset the SMC. SMC fan control not installed nor running

**Comment by sccapstick** [comment]
That fixed it, thanks!
