### ISSUE TITLE
Full blast fan speed resets to baseline after restarting on newest update

### ISSUE THREAD

**Issue by ing0mar** [crystalidea/macs-fan-control#414]
Hi there, after using this program to restart into Bootcamp to keep fan speed full blast, it started to reset to Automatic preset after restart. Sometimes it will stay at full blast successfully and sometimes it won't, I don't seem to see a pattern. Thanks for the great program!

**Comment by kleuter** [comment]
It was a bug we fixed in 1.5.8: the app now restores system control for you fans once you log out.
