### ISSUE TITLE
Display fan RPM in Windows taskbar

### ISSUE THREAD

**Issue by hellobrother222** [crystalidea/macs-fan-control#415]
It would be nice if this software could display the fan RPM in the Windows taskbar like it does in MacOS. It's the only thing keeping me from buying the premium version.

**Comment by kleuter** [comment]
How is it possible in Windows? They only offer icons in system tray.

**Comment by hellobrother222** [comment]
What do you mean? It is possible to get dynamic icons in your taskbar on Windows: I have one that shows my current CPU temp. In MacOS, Macs Fan Control can also display the current fan RPM in the toolbar. I wish this feature was migrated to Windows.

**Comment by kleuter** [comment]
3rd party apps can only display an icon in Windows tray.
MFC is also able to display temperature inside its icon but only for Celsius, because Fahrenheit scale has often 3 numbers.

**Comment by hellobrother222** [comment]
I mean this can easily be worked around by making two icons to display four digit numbers. Let's say my current fan RPM is 1450, MFC could display two icons. The first one would display 14 and the second one would display 50. Sure, there would be a bit of space between the second and third digit, but it's better than nothing.

**Comment by kleuter** [comment]
I'm sorry but we're not planning to put 2 icons to the system tray. Tooltip is the workaround here currently.
