### ISSUE TITLE
Temp "Window" cutting value in 1.4.10 Build 559

### ISSUE THREAD

**Issue by amsterdamned** [crystalidea/macs-fan-control#42]
Just had a pop-up for the new version, which I've installed on a Windows 10 desktop (running in bootcamp on a flashed 2009 Mac Pro).

The temp icon in the system tray cuts the left side of the temperature value (see screenshot).

![temp](https://user-images.githubusercontent.com/37098795/37017421-86a9a17a-2108-11e8-9f16-c05fceff3d7f.PNG)

J.

**Comment by kleuter** [comment]
What are the DPI settings?

**Comment by amsterdamned** [comment]
I'm connecting over RDP using a 23.6" Full HD monitor (1920x1080) - 93.34 PPI, 0.2721mm dot pitch

Windows 10 is set to 100% for text/apps, i.e. not scaled.

**Comment by kleuter** [comment]
Please try this [build 560](https://www.crystalidea.com/downloads/macsfancontrol_beta.exe)

**Comment by amsterdamned** [comment]
That works...just :-)

Thanks,

![temp2](https://user-images.githubusercontent.com/37098795/37133301-6263a7e2-228a-11e8-8f0d-653b9dc6717c.PNG)
