### ISSUE TITLE
Menubar text blurry (macOS 10.15.7, MFC v1.5.8.1)

### ISSUE THREAD

**Issue by Geppo1965** [crystalidea/macs-fan-control#426]
Hi to all Crystalidea users,

after the last update the text in the menu bar is out of focus as per screenshoot.

<img width="534" alt="Clear Mode" src="https://user-images.githubusercontent.com/73799091/97861297-cad50e80-1d03-11eb-9368-c352a64c7cc7.png">
<img width="534" alt="Dark Mode" src="https://user-images.githubusercontent.com/73799091/97861326-d88a9400-1d03-11eb-9998-90dcfb7eedaf.png">

Is it the same for other users ??? macOS 10.15.7
Thanks for your help Gianluigi

**Comment by kleuter** [comment]
Please post tech info and app screenshot as described at #407
External monitor?

**Comment by Geppo1965** [comment]
Hi Kleuter,
attached what you asked me.
Geppo

[Menu Bar text out of focus (Mac Fan Control 1.5.8.1) #426.txt](https://github.com/crystalidea/macs-fan-control/files/5548966/Menu.Bar.text.out.of.focus.Mac.Fan.Control.1.5.8.1.426.txt)
<img width="260" alt="Schermata 2020-11-16 alle 19 30 39" src="https://user-images.githubusercontent.com/73799091/99293290-bdab3a00-2842-11eb-959d-a0fe50e3b01f.png">
<img width="262" alt="Schermata 2020-11-16 alle 19 28 29" src="https://user-images.githubusercontent.com/73799091/99293294-bedc6700-2842-11eb-9a66-04f5d7657677.png">

**Comment by kleuter** [comment]
> Is it the same for other users ???

I hope NO.  Which display scale settings are you using? Thanks.

**Comment by Geppo1965** [comment]
Hi Kleuter,

unfortunately for all the iMac 2019 27” 5k resolutions… I use 2048x1152

**Comment by kleuter** [comment]
Something is strange, this is the first report like that.
Displays fine on our iMac pro 5k as you can see here:
<img width="689" alt="Screenshot 2020-11-17 at 10 51 57" src="https://user-images.githubusercontent.com/2600624/99375023-8892fc00-28c3-11eb-902d-82d454e62184.png">

**Comment by zecanard** [comment]
> Is it the same for other users ??? macOS 10.15.7

Looks fine for me on a 2019 27” iMac, Catalina and Big Sur. Using the default resolution 5120×2880.

**Comment by Geppo1965** [comment]
Hi Kleuter,

I checked, on the same machine, with different user
and also under Big Sur... luckily there is no problem
no issue...
So at this point there is something wrong with the
main user.  Could it depend on font you use in MFC ?

Best regards
Gianluigi Forquet
____________________________
Sent from my iPad Pro 10.5

**Comment by kleuter** [comment]
> Could it depend on font you use in MFC ?

It uses default menubar font.
