### ISSUE TITLE
temperature values inconsistent

### ISSUE THREAD

**Issue by Dinesh2V** [crystalidea/macs-fan-control#428]
Hello, 

![Screen Shot 2020-11-11 at 2 06 30 pm](https://user-images.githubusercontent.com/59717094/98760447-63b40a00-2427-11eb-839b-140ae3b3a7ce.png)

I ran the command: `sudo powermetrics --samplers smc |grep -i "CPU die temperature"` on terminal and saw that the values are inconsistent to the ones provided by macs fan control.

**Comment by kleuter** [comment]
Please post tech info as described at #407
Thanks

**Comment by Dinesh2V** [comment]
Hi kleuter,

I have attached the tech info as requested
[tech info.txt](https://github.com/crystalidea/macs-fan-control/files/5550430/tech.info.txt)

**Comment by kleuter** [comment]
Thanks, unfortunately this model SMC doesn't offer the CPU Die sensor (TC0D) reading

**Comment by Dinesh2V** [comment]
Thank you for looking into this.

**Comment by smayer97** [comment]
BUT how is Terminal getting the temp readings? And why can't macs-fan-control use the same source if those readings are available?

**Comment by kleuter** [comment]
I wish I also knew how powermetrics gets CPU die temperature.
