### ISSUE TITLE
Not working on OS Sierra

### ISSUE THREAD

**Issue by BenConsaa** [crystalidea/macs-fan-control#43]
Hello,

Since 1.4.9, the app doesn't work on my macbook pro (13-inch, mid 2012). Updating the app to 1.4.10, didn't change anything. Could you help me please?

**Comment by kleuter** [comment]
https://github.com/crystalidea/macs-fan-control/blob/master/.github/CONTRIBUTING.md

**Comment by diablo88** [comment]
Error initializing layer, please make sure your Mac system is supported and you have correctly installed the program.
OS is High Sierra 10.3   iMac 21" 3GHZ CPU.  App will not run

**Comment by kleuter** [comment]
@diablo88 did you previous version work?
https://github.com/crystalidea/macs-fan-control/releases

**Comment by diablo88** [comment]
This is the first version I have used.

High Sierra has a few bugs I note, especially the latest updates of it (Beta)

**Comment by kleuter** [comment]
@diablo88 did you previous version of the app (1.4.9) work?
Download to test:
https://github.com/crystalidea/macs-fan-control/releases/download/v1.4.9/macsfancontrol.zip
