### ISSUE TITLE
Reading GPU Temp?

### ISSUE THREAD

**Issue by Brightbrown** [crystalidea/macs-fan-control#434]
Have a GTX 980 and dual boot my 2010 cMP. On the Mac side, no temp. listed for my GPU but on the win10 side, it IS listed. How come and can you fix that?

**Comment by kleuter** [comment]
Unfortunately, the app reads T only for some GPU models like RX 580 under macOS.

**Comment by Brightbrown** [comment]
The app sure does read it in win10... so there must be a way. Hmmm, could it be it does that via the nVidia driver, just discovered that the Unigine graphics benchmarking apps also reads the 980s T?
