### ISSUE TITLE
Only monitor after big sur update

### ISSUE THREAD

**Issue by VZcoding** [crystalidea/macs-fan-control#437]
After update from catalina to big sur does not allow to control fans. Cannot connect to helper. "com.bjango.istatmenus.daemon" => false is always FALSE. "sudo launchctl enable system/com.crystalidea.macsfancontrol.smcwrite" does not turn it on. Tried to move app everywhere, nothing helps..

<img width="561" alt="Screenshot 2020-11-24 at 18 31 17" src="https://user-images.githubusercontent.com/35932738/100123528-45b4c380-2e83-11eb-9b38-40fcb5b1d769.png">

**Comment by kleuter** [comment]
Try running the following commands:

```
killall "Macs Fan Control"
rm ~/Library/Preferences/com.crystalidea.macsfancontrol.plist
killall -u `id -u -n` cfprefsd

sudo launchctl unload /Library/LaunchDaemons/com.crystalidea.macsfancontrol.smcwrite.plist 
sudo rm /Library/LaunchDaemons/com.crystalidea.macsfancontrol.smcwrite.plist 
sudo rm /Library/PrivilegedHelperTools/com.crystalidea.macsfancontrol.smcwrite 
```

Then re-download the app.

**Comment by VZcoding** [comment]
Works. Thank you.
