### ISSUE TITLE
External Fan Hub

### ISSUE THREAD

**Issue by ckrueger99** [crystalidea/macs-fan-control#445]
Does Macs Fan Control support fan control and temperature sensing via External Fan Hubs and, if so, which EFH would you particularly recommend? We're talking Hackintosh here.
My specific use case is to install an inline temperature sensor within a custom water loop that has 4 fans and 2 radiators. My motherboard, the ASRock X570 Phantom Gaming ITX/tb3, doesn't have a two-pin temperature socket, so I can't control the fans within BIOS via this inline sensor, as far as I can tell. If I were running Windows, something like the Corsair Commander Pro controlled by Corsair's iCue software would be the solution. Obviously, iCue (or similar) doesn't work in macOS, hence my interest in Macs Fan Control.
Thank you.

**Comment by kleuter** [comment]
I'm sorry we don't plan this at all. The app's main focus is macOS obviously.

**Comment by ckrueger99** [comment]
I’m only using macOS, as described. That is my reason for interest in your solution.
