### ISSUE TITLE
Windows 10 non-admin user auto start 

### ISSUE THREAD

**Issue by To-Azamat** [crystalidea/macs-fan-control#449]
Hello, I know this issue was discussed before, but I still can’t find a solution. 

MFC installed under windows 10 works fine on admin account and won’t launch at startup at ordinary user’s. Starting it manually requests for admin password. 

Can this be fixed?

**Comment by kleuter** [comment]
https://github.com/crystalidea/macs-fan-control/issues/444#issuecomment-753789729

**Comment by To-Azamat** [comment]
Thank you for reply!
I changed the permissions for user to full control but still have UAC prompt when launching MFC asking for admin password.
