### ISSUE TITLE
Presets per time of day

### ISSUE THREAD

**Issue by JCKodel** [crystalidea/macs-fan-control#451]
Use case:

At day, I don't mind a noiser fan, because I'm usually listening to music (and at day the temperatures are higher).
At night, I would like a more quiter setting, even if it means a hotter crappy MacMini.

Suggestion:
1) Allow to create as many profiles as we want
2) In Preferences, set each profile with a starting/ending hour (something like night shift)

**Comment by kleuter** [comment]
Duplicate of #373
