### ISSUE TITLE
RPM equal to MAX(automatic RPM, preset RPM) option

### ISSUE THREAD

**Issue by Rurmux** [crystalidea/macs-fan-control#453]

**Comment by kleuter** [comment]
> automatically switch to the greatest value.

Not sure what you mean, sorry

**Comment by Rurmux** [comment]
> > automatically switch to the greatest value.
> 
> Not sure what you mean, sorry

So when you set a preset (let’s say 2500 RPM) and the automatic value is less than this (let’s say 2300 RPM) we keep the fan running at the preset value. But when the automatic value increases to over our current present (let’s say 3100RPM), the automatic fan value will override the preset value and the fan will now be running at 3100 RPM.

**Comment by ecc521** [comment]
Does the kernel even allow you to reduce speed below the automatic numbers? I believe I read somewhere that it wouldn't let you do that. 

> protect the computer internals from potential heat damage when the user has not been playing close attention to the current CPU temperature

Totally agree on this one, but... The best thing here would be a way to lower the thermal throttle limit down a bit, and make turbo boost a bit less aggressive. Unless you're running fans at maximum speed all the time, they are always going to be a bit reactive.
