### ISSUE TITLE
MacBook Pro 16" T2 Firmware Corruption

### ISSUE THREAD

**Issue by eggicusroundplumpius** [crystalidea/macs-fan-control#457]
I don't know how widespread this issue could possibly be, since I have no more than one 16" MacBook Pro to test this with, but I've noticed something very concerning about using it on this machine. When using Big Sur, and consequently iBridge 18 for the T2 Chip, using MacsFanControl just once causes strange things to start happening.

The even weirder thing is that you do not have to keep using MacsFanControl. One use is enough. On my machine, my top right port stopped working for anything but USB (no charge, no thunderbolt); sleep/wake times went up by a bunch, as well as boot times; it wouldn't boot at all with other devices connected; Siri eventually stopped working, persisting even through reinstalls of macOS.

How do I know MacsFanControl is the culprit? Well, as a last ditch attempt, I completely reset T2 - wiping the drive and essentially making the entire firmware factory new. That fixed it, until I ran MacsFanControl. As soon as I did that, everything came back until another T2 reset.

One thing to note is that this behaviour does not persist when using iBridge 17, which came with Catalina. The first time I reset T2 was before Big Sur had released, so Apples servers gave me iBridge 17 to restore to (I had gotten iBridge 18 when testing out the Big Sur Beta). This issue only seems to happen when running iBridge 18, regardless of whether you reinstall Catalina since reinstalling macOS does not affect T2 firmware.

If anyone else has a 16" MacBook Pro, have they had this issue?

My System Configuration:
- i9 9880H
- 32GB RAM
- 5600M
- 1TB
- iBridge 18.16.13030.0.0,0

**Comment by kleuter** [comment]
1. The app is not able to modify T2 firmware, no other app in the world is able to do that either.
2. There's no way to reset T2 firmware. "Wiping the drive", resetting SMC will not alter firmware either.
3. You must start looking for other reasons why your computer works "weird".

**Comment by eggicusroundplumpius** [comment]
Alright, listen. 

First of all, I'm not saying your app modifies T2 firmware. What I'm saying is that after the iBridge 18 update, perhaps something to do with changing the parameters for the fans is messing up some data that T2 is supposed to access. I don't know, I'm not an expert. 

Second of all, yes you can reset the firmware. Using another Mac and Apple Configurator 2, you can either "revive" the firmware or reinstall it, clearing the Secure Enclave and wiping the drive. 

Finally, I've been investigating this issue for the better part of 6 months. I'm confident that it has something to do with how T2 and MacsFanControl interact. I'm not trying to be rude but please don't just dismiss my issue. I paid for this software and I actually quite like it and I'd like to try and help fix it, if the issue can be verified to happen on other systems.

**Comment by sauregurke** [comment]
kleuter, I regret to inform you that reinstalling T2's firmware is the literal job of Apple Configurator 2.

**Comment by kleuter** [comment]
I meant 3rd party software
