### ISSUE TITLE
I updated my MacFan Control to the latest version and now it's not working

### ISSUE THREAD

**Issue by veronicasgraphics** [crystalidea/macs-fan-control#46]
A few days ago upgraded to the latest MacFan Control version. I'm now running 1.4.10.0, and my computer is very loud. How can I downgrade or fix this issue?

**Comment by kleuter** [comment]
https://github.com/crystalidea/macs-fan-control/blob/master/.github/CONTRIBUTING.md

**Comment by veronicasgraphics** [comment]
Here you go
Macs Fan Control 1.4.10
iMac12,1
CPU: Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz [100]
GPU: Intel HD Graphics 3000 [active], AMD Radeon HD 6770M
macOS 10.13.3

Fans:
ODD-min{1400}curr{1398}max{4350}mode{0}
HDD-min{1100}curr{5692}max{6300}mode{0}
CPU-min{1200}curr{1199}max{2600}mode{0}


TempSensors:
TA0P () - 27.0117, 27.0117
TA0V () - 26.9648, 26.9648
TA0p (Ambient) - 28.375, 28.375
TC0H () - 45.375, 45.375
TC0P () - 43.75, 43.75
TC0c (CPU Core 1) - 47, 47
TC0h (CPU Heatsink) - 45.375, 45.375
TC0p (CPU Proximity) - 43.75, 43.75
TC1c (CPU Core 2) - 49, 49
TC2c (CPU Core 3) - 51, 51
TC3c (CPU Core 4) - 48, 48
TCGc (GPU PECI) - 50, 50
TCSc () - 49, 49
TCXc (CPU PECI) - 50.5312, 50.5312
TG0D () - 49.75, 49.75
TG0H () - 46.875, 46.875
TG0d (GPU Diode) - 49.75, 49.75
TG0h (GPU Heatsink) - 46.875, 46.875
TG0p (GPU Proximity) - 47, 47
TH0O () - 9, 9
TH1O () - 8.32422, 8.32422
TL0P () - 30.6953, 30.6953
TL0V () - 35.8516, 35.8516
TL0p (LCD proximity) - 43.3125, 43.3125
TL1P () - 39.3125, 39.3125
TL1V () - 35.6953, 35.6953
TL1p (LCD Proximity 2) - 39.3125, 39.3125
TL1v () - 35.6953, 35.6953
TL2V () - 37.2812, 37.2812
TLAV () - 37.2812, 37.2812
TLBV () - 33.3477, 33.3477
TLCV () - 35.8516, 35.8516
TO0P () - 38.375, 38.375
TO0p (Optical Drive) - 39.375, 39.375
TPCD (Platform Controller Hub Die) - 55, 55
TS0P () - 38.125, 38.125
TS0V () - 35.4453, 35.4453
TS0p () - 38.125, 38.125
TS2P () - 37.875, 37.875
TS2V () - 37.7891, 37.7891
TS2p () - 37.875, 37.875
Tm0P () - 45.625, 45.625
Tm0p () - 45.625, 45.625
Tp1P () - 49.75, 49.75
Tp1p () - 49.75, 49.75
Tp2H () - 59.625, 59.625
Tp2h () - 59.625, 59.625
Tp3H () - 54.875, 54.875
Tp3h (PSU Primary) - 54.875, 54.875


Disk drives:
WDC WD7500AZEX-00BN5A0 - 37
![fan](https://user-images.githubusercontent.com/37158758/37168753-866faf32-22cb-11e8-875a-eb77582d6639.jpg)

**Comment by kleuter** [comment]
The HDD fan is set to Auto, with a replaced drive it will be rotating at ~ max rpm
https://www.crystalidea.com/blog/solving-imac-fan-noise-issue-after-hdd-replacement

**Comment by becking** [comment]
I also updated, and now no fans are recognized. need mac for work.
