### ISSUE TITLE
Make available old versions for old OS's

### ISSUE THREAD

**Issue by FenixDigitalB** [crystalidea/macs-fan-control#465]
Many people like me are still running old OSs in old macs (in my case an old MB Pro 15 inches running standalone unmanned station updating values online in a 24x7x12 basis).

That specific computer has a known temperature issue, so I need to keep fans working at a little bit higher speed, in order to keep temperature midrange.

I was using Mac Fan Control for that, but had to restore operating system and the current version does not support MAC OS X 10.9 Mavericks... and my computer does not support newer OS's.

Keeping an old versions library would be of great help for us.

**Comment by kleuter** [comment]
The current version does support 10.9.
![image](https://user-images.githubusercontent.com/2600624/108927121-fb88dd00-763f-11eb-8848-c89b32e451f4.png)
