### ISSUE TITLE
activate preset by name, by command line

### ISSUE THREAD

**Issue by alemac-asc** [crystalidea/macs-fan-control#467]
Hi!

It would be great if it was possible to activate a preset by name, using command line.

I want to make a small app that detects if i'm close or distant of my mac. so, if i'm not close, i'll activate the full blast, for example. and, when i'm back, i'll activate the custom setup.

Best regards,

Alex

**Comment by kleuter** [comment]
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/373
