### ISSUE TITLE
Max Fan Speed (Upper Limit) Changed Unexpectedly

### ISSUE THREAD

**Issue by H3liusAur3lius** [crystalidea/macs-fan-control#468]
Hi All, I've been using Macs Fan Control for a few weeks now, and today I noticed that the max speed shown in the app has changed for some reason. 

When originally installed, and for the past few weeks, the max fan speed available was 3600 RPM, but now - looking at the app, the max speed is only 2640 RPM (screenshot below)

Any idea why this would have changed unexpectedly, or how to fix this would be greatly appreciated. 

![Screen Shot 2021-02-16 at 3 16 30 PM](https://user-images.githubusercontent.com/79173506/108128567-284e5a80-706a-11eb-8f21-4185a337a83b.png)

**Comment by kleuter** [comment]
Max speed is being set by SMC firmware and the app has no control over this value.
