### ISSUE TITLE
The app blocks safe release of a USB drive

### ISSUE THREAD

**Issue by StenApp** [crystalidea/macs-fan-control#473]
![USB Auswerfen](https://user-images.githubusercontent.com/32524257/109402578-38621600-7957-11eb-9976-a1eacfd824cc.PNG)
![Main window](https://user-images.githubusercontent.com/32524257/109402584-3bf59d00-7957-11eb-94cd-7b22e9bdaa41.PNG)

[Technical data.txt](https://github.com/crystalidea/macs-fan-control/files/6195391/Technical.data.txt)

**Comment by StenApp** [comment]
It seems to correlate with having the USB drive plugged during boot process.

**Comment by StenApp** [comment]
"The application \Device\HarddiskVolume3\Program Files (x86)\Macs Fan Control\MacsFanControl.exe with process ID 5276 has terminated removing or ejecting for the device USB\VID_04E8&PID_61F5\MSFT301234568320AF."

--> This means i cannot savely remove my USB drive because Macs Fan Control blocks the save release.
       Please look into that.

**Comment by kleuter** [comment]
Which USB drive is that?

**Comment by StenApp** [comment]
It is a Samsung T5 external drive plugged by USB C to my Macbook Pro 2017
