### ISSUE TITLE
iMac: fan always on before log-in

### ISSUE THREAD

**Issue by Belvicone** [crystalidea/macs-fan-control#474]
Hello,
after replace HDD within SSD on iMac 24" early 2009, fans runs loud.
So, I downloaded Macs Fan Control, installed and configured it, but since the startup until the login into an account the fan runs loud.
After login, Macs Fan Control app runs automatically and fans run correctly.
I've the free version: does the paid version solve the problem?

Thanks in advance.

**Comment by kleuter** [comment]
The payed version is not able to start before login either.

It's a wanted feature but we're still unable to implement it:
https://github.com/crystalidea/macs-fan-control/issues/2

Duplicate.
