### ISSUE TITLE
iMac CPU core 3 & 4 not showing up?

### ISSUE THREAD

**Issue by dogefreak** [crystalidea/macs-fan-control#475]
A few months ago I upgraded my 2010 iMac 11,2 (21"). I swapped out the dual core i3 for an older generation quad i7 (860s). I'm not able to see the temperature of my third and fourth core. Another thing which was upgraded is the GPU, which is a K2100M with a different VBIOS. The GPU won't show its temperature either, but I think that has to do with do VBIOS by Nick[D]vB. The thing that definitely annoys me the most is that I'm not able to see two of my CPU cores. Is this a known issue or does this have anything to do with my custom configuration?
![Schermafbeelding 2021-03-04 om 12 49 34](https://user-images.githubusercontent.com/60531982/109959682-20d4b580-7ce8-11eb-9937-c01c62d515ef.png)

**Comment by kleuter** [comment]
It's not a bug and there's basically nothing we can do here with swapped hardware.
