### ISSUE TITLE
Menubar is not centered in BigSur (all version)

### ISSUE THREAD

**Issue by otonieru** [crystalidea/macs-fan-control#479]
<img width="87" alt="Screen Shot 2021-03-14 at 20 20 32" src="https://user-images.githubusercontent.com/9674184/111070182-f9a98f80-8502-11eb-825d-c4dffea33ba4.png">

**Comment by otonieru** [comment]
This issue is nothing technical, it just visual glitch but still annoying

<details>
Macs Fan Control 1.5.8.1 [Qt 5.13.2]
MacBookPro14,1
CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz [2 cores]
macOS 10.16.0
</details>

**Comment by kleuter** [comment]
Does it happen with the latest beta?
https://github.com/crystalidea/macs-fan-control/issues/435

**Comment by danfoerster** [comment]
It has been like this at least since the last 5 versions of MacOS (OS X), not just Big Sur

**Comment by kleuter** [comment]
Fixed in 1.5.9
