### ISSUE TITLE
Enhancement request: Usage in BootCamp w. Virtualization

### ISSUE THREAD

**Issue by frake65** [crystalidea/macs-fan-control#48]
Hi,
I am using macsFanControl for a long time already and have installed it for OS/X as well as on my BOOTCAMP Partition. Most of the time I'm using BOOTCAMP with VMWare Fusion. While MacFanControl is already running then on the OS/X site, I'd rather have no message "Unsupported hardware detected.". Maybe It would be possible to introduce some kind of ignore Flag (do not show this message again) for my environment. 
Thank you!
Best regards
Frank

**Comment by kleuter** [comment]
There's a flag for that: /skipcheck command line switch:
https://www.crystalidea.com/macs-fan-control/command-line
