### ISSUE TITLE
How to adjust Macs Fan Control

### ISSUE THREAD

**Issue by PeterCPH** [crystalidea/macs-fan-control#480]
I have a 15" MacBook Pro 2.5 GHz Mid 2015 DG. It has two fans. 
In the Macs Fan Control control panel, I can control left and right fan. 
However:
I see nowhere what an acceptable temperature would be ... so I have no idea how to know what is acceptable and what is extremely hot. What is the max temperature that I should accept? What is too hot to be healthy? 
Also: 
I can adjust left and right fans separately. But it says nowhere which fan is closest to the CPU and which is closest to the GPU. Or in other words - should I turn up the speed of the left fan or the right fan to cool the CPU more? 
 
Kind Regards,
Peter

![Skærmbillede 2021-03-15 kl  11 21 16](https://user-images.githubusercontent.com/80681305/111138795-a70eb880-8580-11eb-8305-68dc5ca34c24.png)

**Comment by kleuter** [comment]
Dear sir,

We don't own this computer to test, please experiment with the app: monitor temperatures under different fan rpm values, that's the only advice, unfortunately.

**Comment by PeterCPH** [comment]
Great help
