### ISSUE TITLE
External USB Fan Control

### ISSUE THREAD

**Issue by SeanDogg33** [crystalidea/macs-fan-control#488]
Would like to see feature for a usb powered fan to activate when Mac gets above certain temp as a cooling boost for the internal fans. I have the Mac Pro 2013 (Trash Can Body) that sits on top of a custom base with usb fan. The fan is loud and only has an on/off switch. I don't care about controlling fan speed. I just want the USB port to only power on the fan automatically as needed. additionally, I imaging this will work well for MacBook owners that use the usb powered laptop cooling pads.

**Comment by kleuter** [comment]
Will never be implemented, unfortunately.

**Comment by Birowsky** [comment]
I also came for this feature. Is there a technical limitation? Or is there a different reason for not pursuing this feature?
