### ISSUE TITLE
Better Hackintosh support

### ISSUE THREAD

**Issue by ZondaDC** [crystalidea/macs-fan-control#49]
Hello, kleuter.
Thank you very much for hearing me say my idea. I really like the Macs Fan Control app. Before that I used it on my MacBook Pro. Until I built a Hackintosh, I have to say that it works well. But when I was working at night, it was really noisy! I try to use Macs Fan Control on my Hackintosh and it looks like it can work! But it cannot read the CPU's temperature sensor! I guess you might be able to add support for Hackintosh because Macs Fan Control is really great and we all need it! thank you!
The files in the attachment are FakeSMC, which is derived from RehabMan's CPU sensor driver and counterfeit. I guess it may be necessary.
Thank you again, kleuter. Hope to use Macs Fan Control on Hackintosh.If you need my help, I will do my best to help you.
[RehabMan-FakeSMC-2017-1017.zip](https://github.com/crystalidea/macs-fan-control/files/1806963/RehabMan-FakeSMC-2017-1017.zip)

**Comment by dmatora** [comment]
I would say it's not hackintosh specific issue.
It's just an issue of Macs Fan Control being the only app that would not show all temperature sensors available on smc.
`/Applications/K-Stat-i.app/Contents/Resources/smc -l | grep sp78` always shows much more sensors than Macs Fan Control does.
This sensors filtering is a bug, please fix it.

**Comment by kleuter** [comment]
Please run this [tool](https://www.crystalidea.com/downloads/smc.zip) in your Terminal.
`$./smc -l > smc_dump.txt`
and send me the output smc_dump.txt file

**Comment by ZondaDC** [comment]
[smc_dump.txt](https://github.com/crystalidea/macs-fan-control/files/1851005/smc_dump.txt)
Hello, this is the file you want.
The CPU temperature sensor that macsfancontrol cannot read.You can contact me at any time for testing.

**Comment by kleuter** [comment]
SMC is emulated on hackintosh, there's not much I can do here. A better emulation support (more sensors) is required (https://bitbucket.org/RehabMan/os-x-fakesmc-kozlek/)

**Comment by dmatora** [comment]
![2018-03-28 23 44 21](https://user-images.githubusercontent.com/647062/38055499-8480ab78-32e2-11e8-9ff1-81b5a4f21e74.png)
![2018-03-28 23 47 06](https://user-images.githubusercontent.com/647062/38055500-84a58696-32e2-11e8-97a1-11d06f346d5a.png)
`  TC0D  [sp78]  (bytes 27 00)
  TC1D  [sp78]  (bytes 2a 00)
  TC2D  [sp78]  (bytes 26 00)
  TC3D  [sp78]  (bytes 26 00)
  TCAD  [sp78]  (bytes 2c 00)
  PCTR  [sp78]  (bytes 0d 8d)
  PCPC  [sp78]  (bytes 0b d1)
  PCPG  [sp78]  (bytes 00 be)
  PCPD  [sp78]  (bytes 01 30)
  TZ0C  [sp78]  (bytes 1b cc)
  TZ1C  [sp78]  (bytes 1d cc)
  Tm0P  [sp78]  (bytes 28 00)
  TP0D  [sp78]  (bytes 2b 00)
  TC0H  [sp78]  (bytes 2b 00)
`

here are all sensors
`Num: b0=0 b1=0 b2=0 b3=4b size=4
  #KEY  [ui32]  75 (bytes 00 00 00 4b)
  FNum  [ui8 ]  5 (bytes 05)
  HWS0  [ch8*]  (bytes 47 69 67 61 62 79 74 65)
  HWS1  [ch8*]  (bytes 48 31 37 30 4e 2d 57 49 46 49 2d 43 46)
  RPlt  [ch8*]  (bytes 6a 39 35 00 00 00 00 00)
  RBr   [ch8*]  (bytes 6a 39 35 6a 39 35 61 00)
  TC0D  [sp78]  (bytes 26 00)
  TC1D  [sp78]  (bytes 2a 00)
  TC2D  [sp78]  (bytes 26 00)
  TC3D  [sp78]  (bytes 27 00)
  TCAD  [sp78]  (bytes 2b 00)
  MlCP  [fp88]  (bytes 0d 00)
  CCPC  [ui32]  20 (bytes 00 00 05 14)
  CCPA  [ui32]  18 (bytes 00 00 0b 12)
  PCTR  [sp78]  (bytes 0d c5)
  PCPC  [sp78]  (bytes 0c 03)
  PCPG  [sp78]  (bytes 00 c4)
  PCPD  [sp78]  (bytes 01 35)
  $Adr  [ui32]  0 (bytes 00 00 03 00)
  $Num  [ui8 ]  1 (bytes 01)
  ACID  [ch8*]  (bytes 85 fc 04 4d d8 12 7a f4)
  ALI0  [{ali]  (bytes 07 01 02 00)
  ALRV  [ui16]  1 (bytes 00 01)
  ALV0  [{alv]  (bytes 01 10 06 75 01 20 00 b6 0e e0)
  LsNM  [ui8 ]  1 (bytes 01)
  LsbV  [{rev]  (bytes 01 04 0a 00 06)
  MSLD  [ui8 ]  0 (bytes 00)
  MSSD  [si8 ]  (bytes 05)
  MSSP  [si8 ]  (bytes 05)
  NATJ  [ui8 ]  2 (bytes 02)
  OSK0  [ch8*]  (bytes 6f 75 72 68 61 72 64 77 6f 72 6b 62 79 74 68 65 73 65 77 6f 72 64 73 67 75 61 72 64 65 64 70 6c)
  OSK1  [ch8*]  (bytes 65 61 73 65 64 6f 6e 74 73 74 65 61 6c 28 63 29 41 70 70 6c 65 43 6f 6d 70 75 74 65 72 49 6e 63)
  REV   [{rev]  (bytes 02 33 0f 00 00 10)
  RMde  [char]  (bytes 41)
  RVBF  [{rev]  (bytes 01 30 0f 00 00 03)
  RVUF  [{rev]  (bytes 01 30 0f 00 00 03)
  BEMB  [flag]  (bytes 00)
  EPCI  [ui32]  0 (bytes 08 c0 f0 00)
  TZ0C  [sp78]  (bytes 1b cc)
  TZ1C  [sp78]  (bytes 1d cc)
  Tm0P  [sp78]  (bytes 28 00)
  TP0D  [sp78]  (bytes 2b 00)
  TC0H  [sp78]  (bytes 2b 00)
  VC0C  [fp2e]  (bytes 3c ac)
  VV2S  [fp2e]  (bytes d6 28)
  VV9S  [fp4c]  (bytes c4 fd)
  VV1S  [fp4c]  (bytes 51 1e)
  VC0G  [fp2e]  (bytes 06 e9)
  VS0C  [fp4c]  (bytes 11 16)
  VM0R  [fp2e]  (bytes 4c cc)
  VV7S  [fp2e]  (bytes d7 0a)
  Vb0R  [fp2e]  (bytes c1 89)
  FS!   [ui16]  0 (bytes 00 00)
  F0Ac  [fpe2]  0 (bytes 00 00)
  F0ID  [{fds]  (bytes 01 00 00 00 4d 42 20 46 61 6e 20 30 00 00 00 00)
  F0Mn  [fpe2]  0 (bytes 00 00)
  F0Mx  [fpe2]  6000 (bytes 5d c0)
  F0Tg  [fpe2]  0 (bytes 00 00)
  F1Ac  [fpe2]  1671 (bytes 1a 1d)
  F1ID  [{fds]  (bytes 01 00 01 00 4d 42 20 46 61 6e 20 31 00 00 00 00)
  F1Mn  [fpe2]  0 (bytes 00 00)
  F1Mx  [fpe2]  6000 (bytes 5d c0)
  F1Tg  [fpe2]  0 (bytes 00 00)
  F2Ac  [fpe2]  0 (bytes 00 00)
  F2ID  [{fds]  (bytes 01 00 02 00 4d 42 20 46 61 6e 20 32 00 00 00 00)
  F2Mn  [fpe2]  0 (bytes 00 00)
  F2Mx  [fpe2]  6000 (bytes 5d c0)
  F2Tg  [fpe2]  0 (bytes 00 00)
  F3Ac  [fpe2]  0 (bytes 00 00)
  F3ID  [{fds]  (bytes 01 00 03 00 4d 42 20 46 61 6e 20 33 00 00 00 00)
  F4Ac  [fpe2]  0 (bytes 00 00)
  F4ID  [{fds]  (bytes 01 00 04 00 4d 42 20 46 61 6e 20 34 00 00 00 00)
  NATi  [ui16]  30 (bytes 00 1e)
  NTOK  [ui8 ]  1 (bytes 01)
  MSDW  [flag]  (bytes 01)
`

**Comment by dmatora** [comment]
@kleuter "A better emulation support (more sensors) is required" what sensors are you missing? Why can't you just show all available temperature sensors like rest sensor related apps do?

**Comment by dmatora** [comment]
I've noticed, that running on same hardware with same SMBIOS
1. FakeSMC from slice makes sensors available on Sierra (without fans control since he won't implement it)
![2018-04-13 17 06 43](https://user-images.githubusercontent.com/647062/38739302-2c9981fc-3f3d-11e8-8aca-cb38e84311c0.png)
2. FakeSMC from kozlek doesn't make sensors available to Macs Fan Control, which makes them available to other programs like iStat
I've changed source code of FakeSMC from kozlek to ensure all temperature sensors have same names as on FakeSMC from slice
```
smc -l | grep sp78 
  TC0D  [sp78]  (bytes 39 00)
  TC1D  [sp78]  (bytes 36 00)
  TC2D  [sp78]  (bytes 3a 00)
  TC3D  [sp78]  (bytes 33 00)
  TN0P  [sp78]  (bytes 23 00)
  Th0H  [sp78]  (bytes 1a 00)
  TA0P  [sp78]  (bytes 2e 00)
  TG0P  [sp78]  (bytes 26 00)
```
and even after running FakeSMC from kozlek won't get it working.

@kleuter It looks like, to make judgement on which sensors should be filtered out you not just rely on sensors names or smbios, but also something else. Can you at least say what is it?
Can you share app sources so that I can fix it myself?
I can sign Non Disclosure / Non Compete agreement, if you want.

**Comment by kleuter** [comment]
But this is not iMac13,1, isn't it?

**Comment by dmatora** [comment]
It's not

**Comment by Climatoribus** [comment]
Wouldn't iMac13,1 be part of a tip?
