### ISSUE TITLE
No CPU temperature sensors on free macs-fan-control 

### ISSUE THREAD

**Issue by trebletop** [crystalidea/macs-fan-control#490]
I have just downloaded the free version of macs-fan-control which immediately resolved my noisy fan issue. Excellent. However, I notice that there are no CPU temperature sensor settings available. I take it I would need to upgrade to pro for this?  In the meantime I have used the custom ambient settings at 20c low and 45c high to control the fan for the CPU on my IMAC late 2009 running High Sierra giving a CPU rpm of around 1800.  On auto it runs loudly at 3500. Any advice welcomed.

**Comment by kleuter** [comment]
Please post tech info and app screenshot as described at #407

**Comment by Lorys89** [comment]
i have some problem, this is my log 
[log.zip](https://github.com/crystalidea/macs-fan-control/files/6327083/log.zip)

**Comment by kleuter** [comment]
https://github.com/crystalidea/macs-fan-control/issues/448
