### ISSUE TITLE
App doesn't work on Mac OX 10.6.11 after forced upgrade

### ISSUE THREAD

**Issue by dhorzen** [crystalidea/macs-fan-control#494]
I have an IMac running OX 10.11.6. After replacing the hard drive I used Macs Fan Control to turn off the screaming fan noise with no problems. The new hard drive doesn't have a Mac-compatible sensor. After the forced upgrade to Macs Fan Control 2 my fans no longer turn off. Ever.
I tried to download an older version posted on your website but it will not run on this operating system. Reinstalling the older version I was using only generates the forced upgrade window.
Do I have to buy the Pro Version to solve this problem?
Thanks in advance.

**Comment by kleuter** [comment]
![image](https://user-images.githubusercontent.com/2600624/115420250-474ca280-a1fb-11eb-8c9b-3f65f4853656.png)
https://crystalidea.com/macs-fan-control/download

**Comment by kleuter** [comment]
![image](https://user-images.githubusercontent.com/2600624/115420361-5d5a6300-a1fb-11eb-9bca-391b11e8c697.png)
