### ISSUE TITLE
LoadLibray failed with error 87

### ISSUE THREAD

**Issue by maa07092** [crystalidea/macs-fan-control#496]
MacsFan for Windows 10 crashes when loading.

LoadLibrary failed with error 87: The parameter is incorrect.

**Comment by kleuter** [comment]
Does it happen upon install?

**Comment by maa07092** [comment]
No
 
When it wakes after fresh install.
Loadlibrary failed with error 87: The parameter is incorrect
 
Mark

**Comment by kleuter** [comment]
Should be fine now with v1.5.11
