### ISSUE TITLE
I cant install the fan controller successfully windows version

### ISSUE THREAD

**Issue by IceyZNY** [crystalidea/macs-fan-control#501]
When I install the fan control software windows version, the installation always fails. I tried several versions, but after every installation, I was prompted that the files Qt5Gui.dll, Qt5Core.all, Qt5Network.all, Qt5Widgets.all are missing. The software doesnt work.

**Comment by kleuter** [comment]
Windows version?

**Comment by IceyZNY** [comment]
yes

Kleuter ***@***.***>于2021年5月4日 周二上午10:01写道：

**Comment by kleuter** [comment]
Windows 7, Windows 8, Windows 10 ?

**Comment by IceyZNY** [comment]
win10，I tried several historical versions but none of them can be used
normally

Kleuter ***@***.***>于2021年5月4日 周二上午10:40写道：

**Comment by kleuter** [comment]
Please record a video of installing the app, thanks.

**Comment by IceyZNY** [comment]
Thanks a lot bro!

https://user-images.githubusercontent.com/83614019/117202527-3486c000-adee-11eb-9a50-2b6c34a91916.mp4

https://user-images.githubusercontent.com/83614019/117202535-381a4700-adee-11eb-98f3-38152e8a5068.mp4

**Comment by kleuter** [comment]
Should not happen with the latest version
