### ISSUE TITLE
Crash on MacBook2,1 with Windows 7 x86

### ISSUE THREAD

**Issue by eXPert-nnm4evr** [crystalidea/macs-fan-control#516]
After installation and when i try to start from a shortcut on the desktop, a window appears with the words 'Close the program' and 'Debug the program'. Program doesn't start anyway.

MacBook2,1 A1181 (Late 2006) white, with Windows 7 Ultimate x86 (Only Windows, no MacOS X installed).
Intel Core 2 Duo T5600
4 Gb RAM
250 Gb HDD

**Comment by kleuter** [comment]
Please provide some more information about the crash, you can copy the crash info also in the Windows event log.

**Comment by eXPert-nnm4evr** [comment]
[Video](https://youtu.be/VAZWH56Y46c) of what happens during and after installation (Sorry, I have Russian OS localization, but I think it will be clear anyway).

Имя сбойного приложения: MacsFanControl.exe, версия: 1.5.9.670, отметка времени: 0x60781729
Имя сбойного модуля: ig4dev32.dll, версия: 8.14.10.1930, отметка времени 0x4aba6fdd
Код исключения: 0xc0000005
Смещение ошибки: 0x0000d09f
Идентификатор сбойного процесса: 0x1734
Время запуска сбойного приложения: 0x01d7611efa78748c
Путь сбойного приложения: C:\Program Files\Macs Fan Control\MacsFanControl.exe
Путь сбойного модуля: C:\Windows\system32\ig4dev32.dll
(C) Original LNG

Faulting application name: MacsFanControl.exe, version: 1.5.9.670, time stamp: 0x60781729
Faulting module name: ig4dev32.dll, version: 8.14.10.1930, time stamp 0x4aba6fdd
Exception code: 0xc0000005
Error offset: 0x0000d09f
Faulting Process ID: 0x1734
Faulting application start time: 0x01d7611efa78748c
Faulting Application Path: C:\Program Files\Macs Fan Control\MacsFanControl.exe
Faulting module path: C:\Windows\system32\ig4dev32.dll
(C) Google Translate

EventData:
MacsFanControl.exe 
   1.5.9.670 
   60781729 
   ig4dev32.dll 
   8.14.10.1930 
   4aba6fdd 
   c0000005 
   0000d09f 
   1734 
   01d7611efa78748c 
   C:\Program Files\Macs Fan Control\MacsFanControl.exe 
   C:\Windows\system32\ig4dev32.dll 
   38de5306-cd12-11eb-9259-0017f2b5aacb

**Comment by kleuter** [comment]
C:\Windows\system32\ig4dev32.dll
must be deleted

**Comment by eXPert-nnm4evr** [comment]
Rremove ig4dev32.dll (more precisely, renamed it to ig4dev32.dll.old). Now the program starts up and works fine.
Thank you for help!
