### ISSUE TITLE
iMac problems with sleep mode in sensor-based control

### ISSUE THREAD

**Issue by kleuter** [crystalidea/macs-fan-control#52]
Multiple reports from customers

> This app works great while my iMac is running, but when it’s gone to sleep my computer randomly hard resets, often in the middle of the night, is this a known bug?
(iMac14,2)

> I have a mid-2010 27” iMac that I upgraded to a i7 cpu from an i3. And I replaced the hard drive with a Samsung SSD 850 EVO 500GB drive.
When I sit in front of the computer in the mornings, after it has been in sleep mode, one or more of the fans seems to be at high speed. As soon as I log on, the fan(s) reduce to a low rpm setting. I don’t know which fan(s) are at high speed after the computer has been in sleep mode for awhile.
(iMac11,3)

**Comment by stevensnyderjr** [comment]
Having the same problem. When sleeping the fans rev up and return to normal for no apparent reason. After logging on they return to normal for the duration.

**Comment by kleuter** [comment]
@stevensnyderjr which iMac model? which settings?
Please read
[How to create an issue](https://github.com/crystalidea/macs-fan-control/blob/master/.github/CONTRIBUTING.md)

**Comment by kleuter** [comment]
Looks like a duplicate of https://github.com/crystalidea/macs-fan-control/issues/208
