### ISSUE TITLE
iMac21 Mid 2011 HDD FAN low speed minimum 3700rpm vs 1200 a few weeks ago 

### ISSUE THREAD

**Issue by bsauve** [crystalidea/macs-fan-control#526]
I am using Mac Fan Control for several years on an iMac 21 mid 2011 when the HDD was replaced by an SDD.
Since a few weeks ago, the fan speed is always faster and makes noise.

I went to the control and realize the lowest speed for the HDD is now 3700 rpm which makes noise.
The HDD speed had a range from 1200 rpm to a higher number a few weeks ago.

I don't know what has changed, I boutgh the Pro version thinking the preset would allow me to reduce the speed to 1200 has before, but no, still min of 3700 even with the Pro version.

Could you help.

Thanks
Benoit

**Comment by keyartphoto** [comment]
I have the same issue. Looking for advice. 
Thank you.
Key

**Comment by bsauve** [comment]
Hi,
I did an SMC reset and the lower speed value came back to normal.
In fact, all the 3 FAN speed had higher lower values. They all came back to original low speed after SMC reset.
Here are the low speed I have now after SMC Reset
ODD 1400rpm
HDD 1100 rpm
CPU 1200 rpm

Ben

**Comment by keyartphoto** [comment]
Thank you so much. I will try that.
