### ISSUE TITLE
MacBookPro12,1 - cannot set fan speed

### ISSUE THREAD

**Issue by kleuter** [crystalidea/macs-fan-control#53]
When the fan is off by the system, it's not possible to set a custom fan speed.
<img width="816" alt="2018-03-24 3-9 11 45" src="https://user-images.githubusercontent.com/2600624/37914003-80345d4e-3116-11e8-9042-53678444d68e.png">

**Comment by kleuter** [comment]
Please run this [tool](https://www.crystalidea.com/downloads/smc.zip) in your Terminal.
`$./smc -l > smc_dump.txt`
and send me the output smc_dump.txt file

**Comment by Eddie0401tw** [comment]
#
<img width="568" alt="2018-03-26 11 03 14" src="https://user-images.githubusercontent.com/37807642/37915185-81e3e4fe-314b-11e8-928d-9f9d16fdc9d5.png">

**Comment by kleuter** [comment]
@Eddie0401tw you must run it with parameters
`$./smc -l > smc_dump.txt`

**Comment by RyotaroTakehisa** [comment]
Macs Fan Control is not changeable but only readable. "csrutil disable" was succeeded but still not working. Are there any issues?

**Comment by kleuter** [comment]
@RyotaroTakehisa Please run this [tool](https://www.crystalidea.com/downloads/smc.zip) in your Terminal.
`$./smc -l > smc_dump.txt`
and send me the output smc_dump.txt file

**Comment by rpranshu** [comment]
[smc_dump.txt](https://github.com/crystalidea/macs-fan-control/files/2083480/smc_dump.txt)

**Comment by kleuter** [comment]
@rpranshu Please run this tool in your Terminal after you set some constant speed.

**Comment by kleuter** [comment]
Should be an issue any more
