### ISSUE TITLE
Compatibility with Windows 11

### ISSUE THREAD

**Issue by GCHS** [crystalidea/macs-fan-control#530]
On both Windows 11 builds 22000.51 and 22000.71, Macs Fan Control causes a BSOD with the message WDF_VIOLATION the instant Macs Fan Control starts up. This is confirmed to happen on v1.5.9, unknown if applies to prior versions (it probably does; couldn't check Macs version while being unable to login).
(running Early 2011 iMac)

**Comment by kleuter** [comment]
Windows 11 is not (yet) officially supported by the app. Please post some more information on the BSOD which you can locate in Computer Management
![image](https://user-images.githubusercontent.com/2600624/126320824-0750778b-d7c7-4d25-83d7-2e7d9752e4a1.png)

**Comment by GCHS** [comment]
![mmc_2021-07-22_00-36-01](https://user-images.githubusercontent.com/32718344/126604350-e1b20aca-495e-40af-97f2-64f1963fbdc3.png)
Here is an export of the events themselves: [WDF_VIOLATION BugChecks.zip](https://github.com/crystalidea/macs-fan-control/files/6860650/WDF_VIOLATION.BugChecks.zip)
The memory dump from the last BSOD BugCheck): [https://1drv.ms/u/s!AmISA9qPV0ItlxEx7EHwk3H_St8q?e=ZBMxdq](url)

**Comment by kleuter** [comment]
Ok, thanks. The Boot Camp drivers are not yet officially released for Windows 11 actually, you're using Windows 10 boot camp drivers and once of them crashes indeed (MacHALDriver.sys).

Please try to run the app using with /inpout32 as described [here](https://crystalidea.com/macs-fan-control/command-line)

**Comment by GCHS** [comment]
`/inpout32` works. Macs Fan Control launched with `/inpout32` does not cause a BSOD and can read sensors (displayed values are updating and seem plausible, displayed temperatures increased appropriately during FurMark) and control fans (changing each of the three fan values to max individually produced distinctly more fan noise).

![a screenshot of Macs Fan Control showing it running on Windows 11 with working sensor readings and fan controls](https://user-images.githubusercontent.com/32718344/126680787-ebd8acc4-9a2e-45d6-9a23-a322c19c68b1.png)

**Comment by kleuter** [comment]
That's good to know, thanks! Yep, slow startup is currently excepted with this switch.

**Comment by Cooperman1205** [comment]
Thanks for that i was having the same problem on my mac Pro so, clicked the link "Please try to run the app using with /inpout32 as described here" but it shows mac terminal command how to i do this in windows 11 command prompt??? could you please give me a detailed example as i am 61 and a bit thick when it comes to programming
many thanks
