### ISSUE TITLE
iMac M1

### ISSUE THREAD

**Issue by kleuter** [crystalidea/macs-fan-control#532]
Can someone please post a screenshot of the app and tech info (from the Menu menu) running on the latest iMac m1?

Thanks.

**Comment by Bizzare-Evan** [comment]
So I have a Mac mini M1 but whenever I try to open the application it says to me how the application cannot be launched and to contact my computers administrator, even though I checked permissions and Im the only account and administrator on this computer, so I do not know what is going on.

**Comment by kleuter** [comment]
I asked only about iMac.

Regarding your issue - please remove Open with Rosetta.

**Comment by kleuter** [comment]
Ok, it's working, can be closed now
![1](https://user-images.githubusercontent.com/2600624/127752977-f3c12d50-28b1-4705-b2f9-4e1d29f3ace3.png)
