### ISSUE TITLE
OS X 10.11.6

### ISSUE THREAD

**Issue by kinlamcheung** [crystalidea/macs-fan-control#533]
Is there a version of Macs Fan control compatible with OS X 10.11.6?  When I downloaded it for the "Older Version", it was incompatible.

**Comment by kleuter** [comment]
![image](https://user-images.githubusercontent.com/2600624/127639441-82ac6ee5-4308-4628-af76-49bc316a5602.png)
https://crystalidea.com/macs-fan-control/download

**Comment by kinlamcheung** [comment]
Dear Kleuter, 

Thank you for your advice, it has been downloaded & working now.

Regards,
Dickson
