### ISSUE TITLE
Max fan speed in macOS is lower than under bootcamp.

### ISSUE THREAD

**Issue by Naozumi520** [crystalidea/macs-fan-control#537]
I'm currently using the MacBook Pro 16 inch (2019) and have notice the max fan speed in lower in macOS compared to the bootcamp. Since my laptop is very laggy that I have to always turn on the full speed. The speed is faster in bootcamp that the noise is very noticeable, but under macOS the speed is lower and the noise is not that noticeable too.

**Comment by kleuter** [comment]
Hi, it's not a bug. Max/min fan speed are controlled by the [SMC](https://en.wikipedia.org/wiki/System_Management_Controller) and are read by the app. This is how it works.

You may try to reset SMC as described here:
https://support.apple.com/en-us/HT201295
