### ISSUE TITLE
Freeze on Setting Sensor-based value on IMac w/ High Sierra

### ISSUE THREAD

**Issue by ehovey** [crystalidea/macs-fan-control#54]
I had downloaded the "updated Macs Fan Control" and was attempting to get the fan to be sensor-based instead of constant, and not Ambient, which I don't remember being an option, especially a default option, before.*  ODD setting went fine, but on  HDD, don't remember what I tried, maybe a Core _____? produced the High Sierra-specific tone that I have come to learn means "unacceptable action."  I found I was kicked back to the fan control screen for HDD fan with Ambient pre-set and NO means of moving forward, or even of finding& shutting down the program through "Force Quit Applications." I'm surprised to find it is not there.  I clearly will need to shut down everything to get rid of the dialogue box. screen. 

I am not able to open the preferences dialogue box of Macs Fan Control 1.4.8.1. I am using an IMAC with Intel processor (3.06 GHz Intel Core i3) and 4 GB 1333 memory. 
 
![screen shot 2018-03-28 at 10 59 13 am](https://user-images.githubusercontent.com/37875532/38043740-f57cac58-3285-11e8-830b-01ebad4078ab.png)

 *I have done this many times, but somehow over months or software changes, Macs fan control disappears.

**Comment by kleuter** [comment]
Can you record a video which demostrates a freeze? With the latest version of the app 1.4.10
https://github.com/crystalidea/macs-fan-control/releases/download/v1.4.10/macsfancontrol.zip

**Comment by kleuter** [comment]
Closed due to inactivity.
