### ISSUE TITLE
Update from 1.5.9 to 1.5.10: lost custom presets

### ISSUE THREAD

**Issue by adgama001** [crystalidea/macs-fan-control#543]
Hi!

Since I updated to 1.5.10 version, personalized settings dissapear after rebooting. 

I have pro version Macs fan control. My pro user is adgama001-gmail.com

 
![Captura de pantalla 2021-10-17 a las 20 42 16](https://user-images.githubusercontent.com/59374861/137640636-99df8943-124f-41b5-8793-d9313f68013f.png)

**Comment by kleuter** [comment]
Did you have 1.5.9 before the upgrade? macOS Version? thanks.
