### ISSUE TITLE
Crashing MacBook Pro running High Sierra

### ISSUE THREAD

**Issue by maxbraketorque** [crystalidea/macs-fan-control#552]
Hello, I have a MacBook Pro running High Sierra (10.13.6) and Macs Fan Control that was running 100% stable until up updating to Macs Fan Control 1.5.10. Shortly after updating, the computer crashed, and most reboot attempts would fail and invoke another reboot. Occasionally the Mac would make it all the way to the login window, but after entering credentials and beginning the login process, the Mac would crash again.

After a bunch of experimentation (reset PRAM multiple times, reset SMC multiple times, ssh into computer to verify all disks, trying to boot into recovery), I booted into Safe Mode, removed Macs Fan Control 1.5.10, and then the computer would boot and operate normally again. The first time I successfully got the computer to boot all the way into my account, I reinstalled Macs Fan Control 1.6.10, and it worked fine for several more days, and then it did the same thing again. I then downgraded to 1.5.9, and so far, the computer has not crashed during the last 2.5 days.

**Comment by kleuter** [comment]
Crash report? You can try finding those in the Console utility.
