### ISSUE TITLE
A1398 insane temp sensor data

### ISSUE THREAD

**Issue by hxlph** [crystalidea/macs-fan-control#556]
Got a Mid 2014 15" MBP that I salvaged from a horrible future. After a lot of replacement parts, I've noticed performance hasn't been restored.
Upon further inspection, this Mac is still in panic and the fans at full thrust, with BD_PROCHOT active, so performance is abysmal.
The battery has been swapped and is working, all I'm missing is the camera connection, and IO/board flex, both are missing. The motherboard also has several little iron bars that touch the bottom cover, most are missing too.

My concern here is, using Macs Fan Control I noticed a lot of sensors in this Mac report stupid values like 255C. I would like to diagnose what's wrong (or if they're related to what Its missing being connected, but without context I'm not sure where or how to locate them.

This is the info thrown by Macs Fan Control

Macs Fan Control 1.5.10 [Qt 5.15.6]
MacBookPro11,3 [battery]
CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz [4 cores]
macOS 11.5.0

Fans:
Left side-min{2160}curr{2384}max{6156}mode{2,cpucoreavg,50,90}
Right side-min{2000}curr{2082}max{5700}mode{2,TC2C,51,90}

SMC sensors:
TB0T (Battery Max) - 35.5, 35.5
TB1T (Battery Sensor 1) - 35.5, 35.5
TB2T (Battery Sensor 2) - 34.3984, 34.3984
TBXT () - 35.5, 35.5
TC0E () - 56.0078, 56.0078
TC0F () - 57.9766, 57.9766
TC0P (CPU Proximity) - 47.375, 47.375
TC1C (CPU Core 1) - 56, 56
TC2C (CPU Core 2) - 51, 51
TC3C (CPU Core 3) - 51, 51
TC4C (CPU Core 4) - 50, 50
TCGC (GPU PECI) - 51, 51 [H]
TCSA () - 53, 53
TCTD () - 255.977, 255.977
TCXC (CPU PECI) - 55.4375, 55.4375
TG0D () - 128, 128
TG0P () - 128, 128
TG1D () - 129, 129
TG1F () - 129, 129
TG1d () - 129, 129
TH0A (Apple SSD) - 48.625, 48.625 [H]
TH0B () - 47.625, 47.625
TH0F () - 215.398, 215.398
TH0R () - 214.625, 214.625
TH0V () - 43.8203, 43.8203
TH0a () - 48.625, 48.625
TH0b () - 47.625, 47.625
TH0c () - 42.625, 42.625
TM0P (Memory Proximity) - 47, 47
TM0S (Memory Slot) - 46.207, 46.207
TP0P () - 53.125, 53.125
TPCD (Platform Controller Hub Die) - 64, 64
TW0P (Airport Proximity) - 47.5, 47.5
Ta0P () - 35.875, 35.875
TaSP () - 36.1133, 36.1133
Th1H () - 128, 128
Th2H () - 128, 128
Ts0P (Palm Rest) - 35.625, 35.625
Ts0S () - 128, 128
Ts1S () - 128, 128

GPUs:
Intel Iris Pro - 51
NVIDIA GeForce GT 750M - 0

Disk drives:
APPLE SSD SM0128G - 42

Path: /Applications/Macs Fan Control.app/Contents/MacOS/Macs Fan Control

Anyone mind help me identify what any of these measure? or where they're located? thank you.

**Comment by kleuter** [comment]
Only temperatures that have a name in brackets e.g. TC4C (CPU Core 4) are considered valid to be displayed in the app.
