### ISSUE TITLE
Error initializing SMC interaction layer after update (MacBookPro16,1/MacBookPro16,4 (v1.5.10 worked fine)

### ISSUE THREAD

**Issue by kleuter** [crystalidea/macs-fan-control#557]
Works fine after restart. Will be fixed soon

**Comment by tomvdb3001** [comment]
Thanks, restarting my laptop also solved the problem in my case.

**Comment by kleuter** [comment]
Great, I reproduced it on MacMini8,1, will be fixed soon

**Comment by kleuter** [comment]
Fixed in the most recent build
