### ISSUE TITLE
Mac Fan Control

### ISSUE THREAD

**Issue by HarshalR98** [crystalidea/macs-fan-control#561]
Mac's fan control showing me temperatures for component I don't have on my new MacBook Pro. Issue occurred after updating software. 

MacBook with M1 chip shows cpu cores. 
<img width="1728" alt="Screen Shot 2021-11-24 at 10 13 14 AM" src="https://user-images.githubusercontent.com/59987626/143265468-ffccd903-7d52-4422-9665-cfdf8a3359bc.png">

**Comment by kleuter** [comment]
Which temperature is incorrect in your opinion?

**Comment by HarshalR98** [comment]
I re-downloaded Mac fan control and work fine now. 

It's not the temperature reading that was wrong but the sensors displayed the issue. 

I have a 2021 MacBook Pro with M1 chip I don't know how it was reading CPU cores and GPUs

**Comment by HarshalR98** [comment]
** bad reading ** 
<img width="248" alt="bad " src="https://user-images.githubusercontent.com/59987626/143317829-c2800c68-65e6-4d6d-b50e-45c0ec3b78dc.png">

** good reading ** 
<img width="290" alt="good " src="https://user-images.githubusercontent.com/59987626/143317853-a3df4f93-bb61-4dde-a749-a9595e04f466.png">


The bug is the application was displaying sensors my MacBook doesn't contain.

**Comment by kleuter** [comment]
It's not about bad or good. The first screenshot if from the version 1.5.11 (latest), the second is from the previous version 1.5.10.
