### ISSUE TITLE
Macbook restarting randomly

### ISSUE THREAD

**Issue by igormaraujo** [crystalidea/macs-fan-control#562]
Is it possible the Macs Fun Control cause suddenly reboots at my MacBook? Here is what happed with me:
I updated the Macs Fun Control to version 1.5.11, at the same day, my MacBook reboots while I was working. The reboot doesn't like be by software, it is looks like more a safety hardware shutdown. The following day, this repeated 3 times only in the morning, so I quit the app and apparently solve the problem. Today, the third day after first occurrence, I did the downgrade of Macs Fun Control to version 1.5.10, and so far so good.

<details>

> **I had to erase some part of the log (More > Copy Technical Info) because the issue comment was too long (more than 65536 characters)**

Macs Fan Control 1.5.10 [Qt 5.15.6]
MacBookPro16,2 [battery]
CPU: Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz [4 cores]
macOS 11.6.0

Fans:
Left side-min{1250}curr{6341}max{6336}mode{1,6336}
Right side-min{1350}curr{6895}max{6864}mode{1,6864}

SMC sensors:
TA0V () - 32.1172, 32.1172
TB0T (Battery Max) - 36.5, 36.5
TB1T (Battery Sensor 1) - 34.3984, 34.3984
TB2T (Battery Sensor 2) - 36.5, 36.5
TC0E () - 48.875, 48.875
TC0F () - 50.6953, 50.6953
TC0P (CPU Proximity) - 43.5625, 43.5625
TC1C (CPU Core 1) - 56.5, 56.5
TC2C (CPU Core 2) - 51.5, 51.5
TC3C (CPU Core 3) - 52, 52
TC4C (CPU Core 4) - 58, 58
TCBC () - 51.3281, 51.3281
TCGC (GPU PECI) - 48, 48 [H]
TCSA () - 46.5, 46.5
TCXC (CPU PECI) - 51.3594, 51.3594
TF0S () - 3.53516, 3.53516
TH0F () - 34.6875, 34.6875
TH0X () - 34.7031, 34.7031
TH0a () - 34.7031, 34.7031
TH0b () - 33.7383, 33.7383
TM0P (Memory Proximity) - 43.4375, 43.4375
TPCD (Platform Controller Hub Die) - 48, 48
TTRD () - 34.0625, 34.0625
TTTD () - 34.625, 34.625
TTWD () - 34.375, 34.375
TTXD () - 34.125, 34.125
TW0P (Airport Proximity) - 44.375, 44.375
TaLC () - 34.1875, 34.1875
TaRC () - 32.375, 32.375
Th1H (Heatsink Proximity) - 41.6875, 41.6875
Th2H () - 44.6875, 44.6875
Ts0P (Palm Rest) - 33.5, 33.5
Ts0S () - 37.2227, 37.2227
Ts1P () - 31.9375, 31.9375
Ts1S () - 38.3125, 38.3125
Ts2S () - 36.8711, 36.8711

GPUs:
Intel Iris Plus Graphics - 52

Disk drives:
APPLE SSD AP0512N - 37

Path: /Applications/Macs Fan Control.app/Contents/MacOS/Macs Fan Control

Log:

[2021-11-25 17:36:21:752] [thread 323430] [app.cpp#305] Macs Fan Control 1.5.10
[2021-11-25 17:36:21:752] [thread 323430] [app.cpp#306] macOS 11.6.0
[2021-11-25 17:36:21:752] [thread 323430] [app.cpp#307] MacBookPro16,2
[2021-11-25 17:36:21:752] [thread 323430] [app.cpp#308] Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz [4 cores]
[2021-11-25 17:36:21:752] [thread 323430] [app.cpp#309] Qt 5.15.6
[2021-11-25 17:36:21:766] [thread 323430] [smcWriteInstaller.mm#102] installedInfoPlist is empty
[2021-11-25 17:36:21:766] [thread 323430] [smcWriteInstaller.mm#119] installHelperTool
[2021-11-25 17:36:26:019] [thread 323430] [app_mac.mm#62] removeFlag APP_FLAG_NO_SMCWRITE
[2021-11-25 17:36:26:019] [thread 323430] [Platform_mac_smcwrite.mm#79] open XPC connection to com.crystalidea.macsfancontrol.smcwrite
</details>

After the last reboot, a macOS report screen appears to me, see the screenshot below:

<img width="895" alt="Screen Shot 2021-11-24 at 13 46 40" src="https://user-images.githubusercontent.com/28158542/143590639-76f3c247-c21f-46df-8469-bc4a750e62b3.png">

**Comment by kleuter** [comment]
Can’t be caused by the app
