### ISSUE TITLE
(m1 pro) Computer won't enter sleep with fan on

### ISSUE THREAD

**Issue by gopatrik** [crystalidea/macs-fan-control#568]
I'm having an issue where the fan keeps running after I close the lid on my new m1 mbp; v1.5.11.

**Comment by kleuter** [comment]
Which settings do you leave before closing the lid? Could you please also send us the log? Thanks.

**Comment by gopatrik** [comment]
I think I did paste the logs in the initial post? I attached it as a zip again.

Any setting does it, for example if I do "Full Blast" and close the lid (or go ->Sleep, the fan never turns off.

[log.zip](https://github.com/crystalidea/macs-fan-control/files/7747339/log.zip)

**Comment by brauliolledo** [comment]
hey there! any news on this? i'm having the same issue and its making macs fan control unusable for me :(

**Comment by kleuter** [comment]
Could you please check the beta if it's fixed now?
https://github.com/crystalidea/macs-fan-control/issues/587

**Comment by gopatrik** [comment]
Appears to be fixed in the beta; thank you!
