### ISSUE TITLE
Help with Macs Fan Control

### ISSUE THREAD

**Issue by Seryani** [crystalidea/macs-fan-control#57]
Hi and thanks a lot in advance for your help:

My mid-2011 iMac with Ati Radeon HD 6970M 2 GB was affected with the GPU fail, which was changed to a new one by Apple's program.

However, now, 3 years later, it has broken again. I had to choose between buying a new one for €600 or having it repaired for €160. I did the last, and the GPU chip was changed. I was told by the tech that I should instal Macs Fan Control to check the temperature in which the fans begin to operate, and that the GPU should be cooled before the automatic iMac settings, to prevent the fail happening again.

Do you know which of the three fans (ODD, HDD and CPU) should I use to cool the GPU temperature?

Then, which temperature should I take care of? The GPU Diode, to the GPU Heatsink? 

I would also really appreciate if you could give me an idea of the starting temperatures for setting the fans beginning to work (in centigrades).

Thanks so much for any help again,

Sergio

**Comment by kleuter** [comment]
>Do you know which of the three fans (ODD, HDD and CPU) should I use to cool the GPU temperature?
ODD
