### ISSUE TITLE
[Question] Commercial Use

### ISSUE THREAD

**Issue by BrandonNolet** [crystalidea/macs-fan-control#571]
I'd like to inquire as to whether the Macs Fan Control version without Pro activation (aka free version) is permitted for use on enterprise or corporately owned macOS computers. I was not able to find this on the website or in the EULA.

If there is another webpage that has this information, please point me to it. If there is no webpage that contains this information, I'd like to request that a page be created or modified to include such information.

Thank you.

**Comment by kleuter** [comment]
Please contact us via [e-mail](https://crystalidea.com/contact)

![image](https://user-images.githubusercontent.com/2600624/149525474-723ac045-3c28-4dae-8381-10d07b6e59ad.png)
