### ISSUE TITLE
The fan randomly slow down to 500rpm and the temp so go to 90° and more

### ISSUE THREAD

**Issue by pixelikos** [crystalidea/macs-fan-control#576]
Hello good people,
**The fan randomly slow down to 500rpm and the temp so go up to 90° and more...**
Another problem,  perhaps in relation, 
is than temp setting dont stay and come back to the higher value, 
and even if i save settings,  as you can see below.

Have you an idea Mr Macfans?
Iinclude the log fine wich perhaps will speak to you.

thank a lot for your any answer,
and have a nice day.
Philippe

**My stuff :
Macs Fan Control 1.5.6 [Qt 5.6.3]
Macmini late 2012
Core i7-3615QM CPU @ 2.30GHz 
 Intel HD Graphics 4000
macOS 10.11.6**
![macs fan low fan](https://user-images.githubusercontent.com/99692038/153953007-48a8809a-35f9-4f25-aa8e-c56fd3cf7ff6.jpg)

![capture 2022-02-14 à 21 04 10](https://user-images.githubusercontent.com/99692038/153952006-34b54320-8fe2-4943-8f06-26cdf6c46c7d.jpg)
![capture 2022-02-14 à 21 03 26](https://user-images.githubusercontent.com/99692038/153952010-41033864-ae72-4d04-8a64-7adbb23df789.jpg)

[log macsfan.txt](https://github.com/crystalidea/macs-fan-control/files/8064177/log.macsfan.txt)

**Comment by kleuter** [comment]
Please try to reset SMC as described here:
https://support.apple.com/en-us/HT201295

If it will not help, probably fan replacement should.
