### ISSUE TITLE
No Fans Detected on Computer in v1.4.10

### ISSUE THREAD

**Issue by jpatton2** [crystalidea/macs-fan-control#58]
Hello,

You'll have to bare with me as I'm a Windows user but I bought iMac (version late 2009) for testing purposes at my web design company and ever since we upgraded to the latest version we now get "No fans detected on this computer" and I can't seem to find a way to shut off the annoyingly loud fans that sound like jet engines. =) I am running Mac OS High Sierra 10.12.6

Do I need to configure something to allow the fan to be detected in the machine? Uninstall and install a previous version? Any help is appreciated in resolving this matter. Thanks!

**Comment by kleuter** [comment]
Please read
[How to create an issue](https://github.com/crystalidea/macs-fan-control/blob/master/.github/CONTRIBUTING.md)

**Comment by kleuter** [comment]
Closed dee to inactivity.
