### ISSUE TITLE
Full size problem

### ISSUE THREAD

**Issue by ilaydacan** [crystalidea/macs-fan-control#581]
I was always using the app with small sized screen. One day I accidentally clicked full size symbol, and now it always opens full size without the size options on the up left. The app covers all my screen and I can't reach other apps. When I click "Menu bar display" my screen goes all black. And I have to force quit the app.

**Comment by zecanard** [comment]
Sounds similar to #506. Are you running 1.5.11? The behavior you describe no longer happens for me (running macOS Monterey).

**Comment by ilaydacan** [comment]
Exactly the same problem with #506 ! and yes I am running 1.5.11 on macOS Monterey 12.2.1.

**Comment by ilaydacan** [comment]
I tried your way on #506 with opening Mission Control (⌃↑), then drag Macs Fan Control to my primary Space, and that actually solved it. It opens with minimized window right now. So thanks @zecanard  !

**Comment by zecanard** [comment]
Happy to help! Kinda curious how you get the app into Full Screen. On mine, clicking the + only expands the window rather than taking it full screen 🧐
