### ISSUE TITLE
Mac Studio 2022 support

### ISSUE THREAD

**Issue by kleuter** [crystalidea/macs-fan-control#586]
Fan control actually works but no sensors support yet. 

Anyone got M1 Ultra model maybe? 🙄

**Comment by kleuter** [comment]
Nevermind, found one in stock 😃

**Comment by kleuter** [comment]
Working on M1 Ultra support...

**Comment by kleuter** [comment]
Latest beta now has M1 Ultra support. We decided to control the fans synced and treat both as a single dual blower fan (as in iMac Pro). The reason is obvious: both fans are cooling one heast sink. Still not sure to display so many temperature sensors:
<img width="1114" alt="Screen Shot 2022-04-02 at 6 13 20 PM" src="https://user-images.githubusercontent.com/2600624/161391672-2b67539e-9cf2-4a22-a998-68ee7ec4ee71.png">

**Comment by TomMapex** [comment]
How do I get a copy of the beta?

**Comment by kleuter** [comment]
https://github.com/crystalidea/macs-fan-control/issues/587
