### ISSUE TITLE
Free version too good!

### ISSUE THREAD

**Issue by Graydog7** [crystalidea/macs-fan-control#588]
I would like to purchase Macs-Fan-Control Pro for my MacBook Pro only while running Windows  but it only seems to have the Windows version in the bundle. I would like to support the developer but don't want to splash out on the bundle. 

P.S. The free version is very good and I'm not even sure of the benefit of buying the Pro other than supporting the dev.

**Comment by kleuter** [comment]
Thanks for the kind words!

I'm thinking of introducing some Pro feature(s) soon we you can purchase it in advance 😃
