### ISSUE TITLE
Cannot Update 1.5.11 with last update?

### ISSUE THREAD

**Issue by Chacapamac** [crystalidea/macs-fan-control#590]
Mac Os Sierra 10.12.6
MFC is 1.5.11 Pro — It download the update quit and relaunch but stay at 1.5.11

**Comment by Tigerwind** [comment]
Mac Os Sierra 10.13.6. MFC is 1.5.11 Pro. I kept getting asked to update to the latest version, which I did, but was asked to do the same again and again each time I start MFC.

**Comment by Tigerwind** [comment]
when I check the update, I was told my version was the latest. how can I turn off the popped up advise?

**Comment by kleuter** [comment]
Working on a fix for macOS 10.7-10.12

**Comment by kleuter** [comment]
Must be working fine now

**Comment by Chacapamac** [comment]
I should update to High Sierra soon - **Now I see that the new version is compatible with HighSierra up.**

Without knowing that, this morning I try to update again, this time it brick the app. I just re-download the Sierra compatible version and reinstalled , the Pro function are still working....

Good Day!
