### ISSUE TITLE
I can't run the version 1.5.11 in Mac osx 10.13.6

### ISSUE THREAD

**Issue by deigo11111** [crystalidea/macs-fan-control#591]
I was trying to update my Macs fan control on my iMac mid 2011, when the update finished, the app couldn't run appearing a text box that says "the app can't run, is incomplete", then I uninstalled the app and downloaded the lasted version from the website, so when I unzip and tried to run the application appears me the text box that says "The app "Macs Fan Control" can not run". I've tried install an older version but appears me the same text box. What can I do to install the app?

**Comment by kleuter** [comment]
Download for macOS 10.13 High Sierra
https://crystalidea.com/downloads/macsfancontrol.zip
