### ISSUE TITLE
Help to configure the Macs Fan Control

### ISSUE THREAD

**Issue by braisremeseiro** [crystalidea/macs-fan-control#592]
Hello,

I am newbie to this matter and I would like to ask How should I configure the Macs Fan Control to reduce the temperature in my internal hard drive?. I have an iMac with macOS Sierra 10.12.6 with an 2,7 GHz Intel Core i5.

Also I would like to ask which is the best setup to maintain an average temperature.

Thanks in advance.

**Comment by kleuter** [comment]
https://crystalidea.com/blog/solving-imac-fan-noise-issue-after-hdd-replacement
