### ISSUE TITLE
Regression: fan spinning in sleep mode

### ISSUE THREAD

**Issue by kleuter** [crystalidea/macs-fan-control#594]
Some people report a regression issue in v1.5.12 after upgrade (older iMac models and some other macs)

Please try this build and report if it's fixed for you

[macOS](https://crystalidea.com/downloads/macsfancontrol_test.zip)
[Windows](https://crystalidea.com/downloads/macsfancontrol_setup_test.exe)

**Comment by hkbenchan** [comment]
It works for me as well.

Env: MBP 16-inch 2019 with macOS Monterey v12.3.1

**Comment by kleuter** [comment]
Thanks!

**Comment by vnc777** [comment]
Thank you very much. I had the same problem with Mac OS High Sierra 10.13.6.
Problem is solved. Perfect!

**Comment by thore-hph** [comment]
@kleuter Confirming, fixing the spinning issue for me in sleep mode for Mac Studio on Monterey 12.3

**Comment by moranjaccov** [comment]
page error can u please fix that?
