### ISSUE TITLE
Fan Goes Full Blast When iMac Put To Sleep

### ISSUE THREAD

**Issue by drferry1** [crystalidea/macs-fan-control#595]
I updated to the latest 1.5.12 version. But now when I put the iMac to sleep, just as it's going to sleep, the fan runs at full blast momentarily until the iMaci is fully asleep. When I wake it back up all works normally. This didn't happen before the latest update. Just wanted you to know.

**Comment by kleuter** [comment]
Please try this test build:
https://github.com/crystalidea/macs-fan-control/issues/594

**Comment by drferry1** [comment]
kleuter,
This build above fixed the issue on my iMac running High Sierra 10.13.6. I am able now to put the iMac totally to sleep without the fan momentarily going full blast. Thank you for fixing the bug so quickly.
