### ISSUE TITLE
Fan runs above max speed

### ISSUE THREAD

**Issue by Jessamine1** [crystalidea/macs-fan-control#60]
I can't get manual or sensor control of the fan. After start up, the fan comes in after a while and runs continually at high speed.I have  OS Sierra 10.13.4 and late 2013 i Mac. Hope you can solve this as it looks a good application.

Regards, Roger
![screen shot 2018-04-12 at 12 13 59](https://user-images.githubusercontent.com/38316574/38677538-781448b6-3e56-11e8-8d08-b2704440c9ba.png)
[MacsFanControl.log](https://github.com/crystalidea/macs-fan-control/files/1903108/MacsFanControl.log)

**Comment by kleuter** [comment]
Did you try to reset SMC?

**Comment by Jessamine1** [comment]
Hi, Yes I did try to reset SMC. For this Model i Mac Apple say Shut computer down, Unplug all connections for 20 seconds. Re connect and then re start. I presume this is enough to reset.

Regards Roger Double

**Comment by kleuter** [comment]
https://support.apple.com/en-us/HT201295

**Comment by Jessamine1** [comment]
Hi, Trying all the reset options has not got rid of the problem. Fan still runs at high speed.

Regards, Roger Double

**Comment by Jessamine1** [comment]
Hi Kleuter, Just to let you know, the Application is now working and I can control the fan speed. I tried reseting again and it seems to have got into gear in the end. Great application and I now have a Mac that is not noisy. Thanks for your help.

Regards Roger Double

**Comment by kleuter** [comment]
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/66
