### ISSUE TITLE
More secure helper tool to avoid possible abuse of SMC interface by malware apps

### ISSUE THREAD

**Issue by mhaeuser** [crystalidea/macs-fan-control#601]
The latest release of this app ships with a Privileged Helper App that exposes an SMC interface that takes caller-specified key names without a whitelist. There are obvious security concerns with not sanity-checking the key names intended to be exposed at the high-security level (helper). To not entirely eliminate this intentional security boundary from Apple, please consider matching the supplied key names against a whitelist. Or, much better yet, do not have any direct SMC exposure, but instead abstract the operations (e.g. expose `SMCSetFanSpeed` over `SMCWriteKey` or alike).

**Comment by kleuter** [comment]
Hi,

I don't see a security concern here because macOS checks that only Macs Fan Control is able to use the priviledged helper tool.

![image](https://user-images.githubusercontent.com/2600624/167386585-277963fc-81cd-4c40-8eb5-1499ef7ca976.png)

**Comment by mhaeuser** [comment]
Well, if this was not the case, this would not be a "security concern" but an outright vulnerability, which I would have reported privately. The issue is this helper proxies a privileged interface (from the sandbox' point of view) into the sandboxed environment, defeating the security boundary as a whole. Reduced hardening from locally signed complilations, bugs in the sandboxed application, etc. may all lead to performing unintended operations on the privileged SMC interface.

**Comment by kleuter** [comment]
This is not the case, this how apple priviledged tools generally work, but I'll think of reducing API abilities.

**Comment by mhaeuser** [comment]
Just stumbled over this: https://blog.obdev.at/what-we-have-learned-from-a-vulnerability/
In post 2 you imply SMAuthorizedClients authenticates the peer (which it apparently does not). Is this considered in the code? I didn‘t check.

**Comment by kleuter** [comment]
Thanks, that's a very intereseting and important read.

Will be implemented in the next update for sure.
