### ISSUE TITLE
Disable Fans on Accelerometer Movement

### ISSUE THREAD

**Issue by Xuderis** [crystalidea/macs-fan-control#602]
If the accelerometer detects motion, kill the fans to prevent damage.  I know older MacBooks had accelerometers/"sudden motion sensors", but haven't found official documentation on new models to say whether this is still possible.  

https://osxdaily.com/2010/12/16/disable-sudden-motion-sensor-mac/

Currently this behavior is not exhibited on my M1 MacBook Pro when set to automatic.  The fans continue to spin when the device is moved.

**Comment by kleuter** [comment]
Unfortunately, this is not planned currently and not likely to be implemented
