### ISSUE TITLE
fan speed goes down to 0 when on automatic

### ISSUE THREAD

**Issue by poodusmen** [crystalidea/macs-fan-control#606]
I have a macbook pro 2020 (13 inch intel version, 4 thunderbolt ports) on MacOS 10.15.7. When I go to automatic, the fan does not go to the minimum, but instead goes to 0. This has proven dangerous for my computer because the CPU gets overheated and I see visible lag after a while from the CPU throttling. I now have it on sensor based control of CPU average to keep it operational.

**Comment by fadedmax** [comment]
Hi, are you sure that your computer is *truly* overheating? Try closing the app first, and while performing the same task(s) see if the fans automatically kick on(by just listening)

**Comment by poodusmen** [comment]
The MacBook fans should never go below a minimum (~1200 rpm) no matter what.

**Comment by kleuter** [comment]
This is a normal behaviour when CPU temperature is low enough.
