### ISSUE TITLE
i Mac Late 2013 on OS High Sierra 10.13.4 Fan Runs at high speed and won't control on Manual or Sensor Based Control

### ISSUE THREAD

**Issue by Jessamine1** [crystalidea/macs-fan-control#61]
I can't get Macs Fan Control to override the i Macs fan setting. I raised this as a previous issue earlier this month, and it got closed because it appeared to be working for a while. Why it appeared to work for a short while I don't know. I have uninstalled and re installed it, but still can't get it to work. I have carried out Apples reset several times to no effect. Have you any ideas?

Best Regards, 

[MacsFanControl.log](https://github.com/crystalidea/macs-fan-control/files/1960735/MacsFanControl.log)
![screen shot 2018-04-30 at 14 34 51](https://user-images.githubusercontent.com/38316574/39429903-4a6ee0d8-4c84-11e8-98f3-8c74aa75afc8.png)

**Comment by Jessamine1** [comment]
Further Information: When setting constant speed the fan runs at the set speed for a while, and then it appears the System overrides it, and ramps up to full speed. Also when set to a sensor control, the fan runs at a low speed for a while, and then ramps up to full speed even though the sensor temperature registered is well below the setting temperature. It appears that the system control is overriding the Macs Fan Control Application?

**Comment by kleuter** [comment]
Known issue
