### ISSUE TITLE
Customize font in menubar

### ISSUE THREAD

**Issue by Grafovich** [crystalidea/macs-fan-control#62]
MFC menubar icon size is ok and looks good, but when i choose displaying current temperature it looks too small. Digits are too small compared to other icons [56℃]. Would be great to make em as big as others. Thanx!

![screen shot 2018-05-11 at 05 36 06](https://user-images.githubusercontent.com/16868086/39903979-7ecd2896-54de-11e8-91f7-124c20504d4b.png)

**Comment by kleuter** [comment]
Well, it's the font is smaller in comparison with the font used to display current date/time. Not sure if it's really needed. Need more feedback

**Comment by Salomanuel** [comment]
it would be actually lovely to customize the font (size/font/colour), like the cherry on top of this great application

**Comment by kleuter** [comment]
Font size is increased in 1.5.1 so it should be much better

**Comment by Grafovich** [comment]
Yes it is. Thank you!

**Comment by rileytwo** [comment]
The bigger fonts seem to not fit in the space that MFC has for the menu bar

Two line display:
![macs-fan-control](https://user-images.githubusercontent.com/34988536/68523380-00c0ed80-027e-11ea-9569-9f9df679060f.jpg)

Single line display:
![macs-fan-control2](https://user-images.githubusercontent.com/34988536/68523392-20f0ac80-027e-11ea-9036-43c13d0a3393.jpg)

**Comment by kleuter** [comment]
@rileytwo macOS 10.14 or 10.15 ? Thanks

**Comment by kleuter** [comment]
thanks for the report, will be fixed ASAP:
https://github.com/crystalidea/macs-fan-control/issues/231

**Comment by rileytwo** [comment]
@kleuter macOS 10.15! thanks for responding so quickly

**Comment by kleuter** [comment]
Thanks, I reproduced it, will fix tomorrow in 1.5.1.7

**Comment by rileytwo** [comment]
When will 1.5.1.7 be released?

**Comment by kleuter** [comment]
It's [live](https://www.crystalidea.com/macs-fan-control/download)
