### ISSUE TITLE
Error - Fan min and max are the same (65535) Please delete other fan control programs and restart SMC

### ISSUE THREAD

**Issue by zhouxinhao1208** [crystalidea/macs-fan-control#620]
Error - Fan min and max are the same (65535) Please delete other fan control programs and restart SMC

**Comment by kleuter** [comment]
Hackintosh?

**Comment by zhouxinhao1208** [comment]
> Hackintosh?

Yes Yes, I can't solve this problem in hackintosh

**Comment by kleuter** [comment]
The app doesn't officially support hackintosh.
Those values are being read from smc emulation.
