### ISSUE TITLE
Not working on Windows 11?

### ISSUE THREAD

**Issue by XaXaNavi** [crystalidea/macs-fan-control#624]
I downloaded MFC from the web (from Crystalidea), installed it, but a prompt says that it works only on Apple's hardware?!? Not able to run the software. [Trying this on Dell XPS running Windows 11 (21H2)]. 

![Screenshot (61)](https://user-images.githubusercontent.com/108536419/176917020-78c9e0f3-96d9-4e8e-b90c-3d797f93afca.png)

Please help :)

**Comment by kleuter** [comment]
Dell XPS is not an Apple computer

**Comment by XaXaNavi** [comment]
Of course not but then why is there a Download for Windows option?

**Comment by kleuter** [comment]
Windows can be installed on Intel Macs
