### ISSUE TITLE
Fan speed varies too repidly

### ISSUE THREAD

**Issue by wanghongfei** [crystalidea/macs-fan-control#63]
This is my setting:
![image](https://user-images.githubusercontent.com/4201347/39963344-4b19d5bc-569b-11e8-8afe-7e9315031d1a.png)
Fan speed can vary rapidly from 1200RPM to the maximum 7200RPM in just about 2 seconds, and dramatically drops from 7000RPM to 1000+RPM, which makes people feel uncomfortable. MacOS's default fan control does not have this issue. Fan speed varies very smoothly no matter how quickly the temperature changes.

version: 1.4.10
Macbook Pro 13 2017

**Comment by kleuter** [comment]
@wanghongfei it's because the range 52-85 is too small. Try something like 70-100

**Comment by wanghongfei** [comment]
@kleuter thanks for your reply
