### ISSUE TITLE
Error - no fans detected

### ISSUE THREAD

**Issue by qsaw** [crystalidea/macs-fan-control#642]
<h3> Hi all, <br> <br>
I have a problem: I can't control the fans of my MacBook Air 10,1 .<br>
If I open the app, there is always the error: </h3> <h3> "This computer doesn't have any fans and it's cooled passively" </h3>
<br> 
<a href="https://ibb.co/SvCsrVY"><img src="https://i.ibb.co/NYBVSWD/Bildschirmfoto-2022-09-04-um-18-34-07.png" alt="Bildschirmfoto-2022-09-04-um-18-34-07" border="0"></a>
<br>
<h2> What can I do? 
<br> <br>
Thank you very much in advance! </h2> <br>

**Comment by kleuter** [comment]
This PC doesn't have a fan and it's not a bug obviously
