### ISSUE TITLE
Disable fans below specified temperature

### ISSUE THREAD

**Issue by dalisoft** [crystalidea/macs-fan-control#643]
Hi @crystalidea

Thank you for such a great app.

Could be nice to see feature of **disabling fans when temperature below threshold/specified**. Currently anyway runs fan.

Platform: M1 Macbook Pro 2020.
OS: macOS 12.6
App version: v1.5.13 (Free version)

**Comment by hricvladimir** [comment]
This is a must have option. Currently when I set manual fan "curve", the fans spin at 1200rpm on macbook pro 14. I see this as unnecessary, because when the temperature is lets say 40 degrees and threshold is at 50 degrees, there is no need for fans to run.

**Comment by JimmyBlackyB** [comment]
I support the author Add such functionality. When the temperature is below the set minimum threshold, so that the fans turn off. Since this affects the duration of battery life.

**Comment by thePaleWhale** [comment]
This feature would be the reason for me to buy the pro version. I used the app for years and I was very happy and thankful to have it. But with the newer M1 MacBooks I only need it when I do heavy number crushing on my machine. Therefore I don't want and need the fans spinning in the meantime.

**Comment by you-hengh** [comment]
Computer chip: M1 
System version: 13.2.1 (22D68)
Software version: 1.15.15

Below the control temperature, hoping to disable the notebook fan. Thank you very much

**Comment by lubomirfiala** [comment]
I bought pro version yesterday and I thought this functionality is there. 
my profile is currently 50 - 70 deg, and most of time my cpu has 42deg, so it is not necessary to run fans below 50. 
So I'm voting for this feature too.
