### ISSUE TITLE
A1398 mid 2014 (Dual Graphics) Unsupported Hardware on Windows 7/10/11 

### ISSUE THREAD

**Issue by jimmyverlis** [crystalidea/macs-fan-control#658]
Hello, i'm running into an issue with macs fan control under windows, i get this stupid error message about 6 months now, my mac is running boiling hot in windows soo macs fan control is the solution for me. I tried to reinstall windows again and again for the same reason, macs fan control never worked in windows, i reinstalled every single one bootcamp driver and i dont have "unknown devices" on device manager. 

I'm booting mac os and windows with opencore, i even tried to boot windows from mac boot menu without opencore and the problem perists. On macOS everything is fine. 
<img width="305" alt="image" src="https://user-images.githubusercontent.com/12376236/209027459-75d51003-6ad7-4a57-ad64-22e61d1f1d34.png">

**Comment by kleuter** [comment]
Can you try using the /skipcheck parameter?
https://crystalidea.com/macs-fan-control/command-line

**Comment by jimmyverlis** [comment]
oh my god, i love you really, thanks!! This solved my issue. One day when i have some spare money i will definitely buy the app! You saved me bro, i have my birthday party in two weeks and i have issues with thermal throttling when using virtual dj with stems 2.0

**Comment by kleuter** [comment]
Glad I could help. Yes, it's possible. Create a shortcut with this command line switch and add this shortcut to the startup.

Can be easier be done with [Uninstall Tool Startup manager](https://crystalidea.com/uninstall-tool/startup-programs)
