### ISSUE TITLE
Uninstall program issues

### ISSUE THREAD

**Issue by desunuts** [crystalidea/macs-fan-control#663]
Hello, so I uninstalled the application as I did not have a need for it anymore. I thought I uninstalled it on my Macbook Pro by deleting it from the Application folder then the Trash Bin, but I noticed in my Start on Startup settings that it was still there. Wondering if theres any loose files I have to go find to clear my device of the program completely.

**Comment by kleuter** [comment]
https://crystalidea.com/uninstall

**Comment by desunuts** [comment]
it did not work, I still see parts of the program

**Comment by kleuter** [comment]
Manual instructions are added to the page
