### ISSUE TITLE
MacBook Pro & Mac Mini 2023 Support

### ISSUE THREAD

**Issue by kleuter** [crystalidea/macs-fan-control#664]
Please post tech info as described [here](https://github.com/crystalidea/macs-fan-control/blob/master/how-to-post-tech-info.md).

Beta build:
https://crystalidea.com/downloads/macsfancontrol_beta.zip

**Comment by jowiec** [comment]
CPU temp not showing up on a new 14" MBP Apple M2 Max with 12‑core CPU, 38‑core GPU, 16‑core Neural Engine, 96GB memory, 2TB SSD.
[Mac14,5_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/10526084/Mac14.5_tech_info.zip)

**Comment by kleuter** [comment]
Thanks, in progress

**Comment by J-charles-C** [comment]
[Mac14,12_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/10543228/Mac14.12_tech_info.zip)

I.

Many thanks for your job.

best

**Comment by kleuter** [comment]
Thank you!

**Comment by MTCoster** [comment]
Just got my M2 Mac today - one more data point for you :)

[Mac14,6_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/10562415/Mac14.6_tech_info.zip)

**Comment by GaryQian** [comment]
[Mac14,9_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/10564438/Mac14.9_tech_info.zip)

Here's another data point, Macbook pro, 14in, M2 Pro 10/12 CPU/GPU, 16gb RAM, 1tb SSD

**Comment by clara-j** [comment]
Just got my new MacBook Pro

[Mac14,6_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/10574811/Mac14.6_tech_info.zip)

**Comment by DanielSmithAU** [comment]
New M2 Max Maacbook Pro

[Mac14,5_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/10691730/Mac14.5_tech_info.zip)

**Comment by randallkn** [comment]
Mac Mini M2 Pro 10-core
[Mac14,12_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/10714663/Mac14.12_tech_info.zip)

**Comment by vladimirgluten** [comment]
[Mac14,10_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/10845488/Mac14.10_tech_info.zip)
I just got a M2 Pro 16" MBP, attached the tech info .zip file

**Comment by kleuter** [comment]
Please tell me if this beta build works fine for you
https://crystalidea.com/downloads/macsfancontrol_beta.zip

**Comment by clara-j** [comment]
Seems to be working for me. 
<img width="1015" alt="Screenshot 2023-02-28 at 12 19 42 PM" src="https://user-images.githubusercontent.com/13851193/221928838-e4325a21-910c-4fb2-8cfc-ce3267ff00fe.png">

**Comment by Kynno** [comment]
Macbook Pro 16", M2 Max 38GPU, I can confirm it's working for me as well. 🙏 

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/9844910/221958184-3aad5820-74eb-423d-b12c-c7362afd881a.png">

**Comment by randallkn** [comment]
Looking good on my 2023 Mini
![Screenshot 2023-02-28 at 4 31 04 PM](https://user-images.githubusercontent.com/10556754/221985037-807d28b4-2274-42ab-adcf-57c8e78fafe1.png)

**Comment by J-charles-C** [comment]
> Please tell me if this beta build works fine for you
> https://crystalidea.com/downloads/macsfancontrol_beta.zip

I,
The beta version works well on my Mac mini M2 PRO.

Do you know when we can stop the fan or reduce its speed below the minimum allowed by Apple?

Thanks for your job.

**Comment by peiranAkelius** [comment]
works fine in macbook pro 14-inch, 2023
Thanks a lot
<img width="1068" alt="Screenshot 2023-03-01 at 12 46 44" src="https://user-images.githubusercontent.com/64778291/222130951-48d0de79-695e-4095-88a8-7158bbf05bb1.png">

**Comment by kleuter** [comment]
There's a new build 53 specially for [randallkn](https://github.com/randallkn).

For everyone: please post tech info described [here](https://github.com/crystalidea/macs-fan-control/blob/master/how-to-post-tech-info.md) using the new build 53.

@J-charles-C 
Your feature request is scheduled for version 1.6

Thanks!

**Comment by J-charles-C** [comment]
>
> @J-charles-C Your feature request is scheduled for version 1.6
> 
> Thanks!

I, thanks


[Macmini10,2_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/10864047/Macmini10.2_tech_info.zip)

**Comment by vladimirgluten** [comment]
[MacBookPro19,2_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/10864063/MacBookPro19.2_tech_info.zip)

Attached the tech info zip using the beta as requested.  Seems to be working great for me so far, thank you very much for the update!

**Comment by Rogacz** [comment]
[MacBookPro19,2_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/10870234/MacBookPro19.2_tech_info.zip)

**Comment by kleuter** [comment]
Thanks!

**Comment by clara-j** [comment]
Here is zip from latest build
[MacBookPro19,4_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/10870997/MacBookPro19.4_tech_info.zip)

**Comment by kleuter** [comment]
Thanks, about to release 1.5.15, please test the latest build 55 if it works fine (no tech info needed).
(I don't have any M2 Pro/Max mac at the moment)

https://crystalidea.com/downloads/macsfancontrol_beta.zip

**Comment by Rogacz** [comment]
Works fine on my M2 Pro

**Comment by dominikburri** [comment]
Works fine for my 14" M2 Pro 12C. Thanks a lot!

**Comment by kleuter** [comment]
Thanks! 1.5.15 is live, automatic update will be rolled out little later

**Comment by hugofpaiva** [comment]
Working fine on 16" M2 Max
