### ISSUE TITLE
No CPU sensor listed for iMac6,1

### ISSUE THREAD

**Issue by lcdswat** [crystalidea/macs-fan-control#666]
![Снимок](https://user-images.githubusercontent.com/16235049/218467242-9e38f0c9-bc0f-4ca8-b854-a7c6ed422ef5.PNG)
MFC works fine on my iMac6,1 late 2006, but there is no CPU temp in list, so i cant setup auto fan control. Same problem on mac os and windows. Is there any solution?

Aida64 shows CPU temp fine:
![Снимок-2](https://user-images.githubusercontent.com/16235049/218467247-8629d690-3252-47c1-a37e-ff61eced108b.PNG)

**Comment by kleuter** [comment]
Please post tech info and app screenshot as described at [here](https://github.com/crystalidea/macs-fan-control/blob/master/how-to-post-tech-info.md).

**Comment by lcdswat** [comment]
Thank you! There it is:
[iMac6,1_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/10740354/iMac6.1_tech_info.zip)
> Please post tech info as described at [here](https://github.com/crystalidea/macs-fan-control/blob/master/how-to-post-tech-info.md).

**Comment by kleuter** [comment]
Unfortunately the TCOD sensor is reporting 129 C, so we can't show him.

The app shown above (AIDA) uses intel specific toolkit to display CPU temperature which is not supported, unfortunately.
