### ISSUE TITLE
Wrong Fan RPM 

### ISSUE THREAD

**Issue by KaranGeorge1550** [crystalidea/macs-fan-control#67]
![screen shot 2018-05-31 at 5 15 16 pm](https://user-images.githubusercontent.com/39949919/40970816-d50b29c0-690f-11e8-91ae-5b66dda8bbca.png)
![screen shot 2018-06-05 at 10 20 39 pm](https://user-images.githubusercontent.com/39949919/40970828-dce6cb04-690f-11e8-9f09-b1b5fc38b163.png)
![screen shot 2018-06-07 at 8 59 40 am](https://user-images.githubusercontent.com/39949919/41064969-3bd2af58-6a31-11e8-9bd0-92cf95410650.png)

As you can see by the two screenshots above the app is displaying the wrong fan RPM. (The photos were taken on different days)

I am using Macs Fan Control 1.4.10 on a 2017 Mac Book Air

Edit: I had to replace the photos, because I placed the wrong ones 
Edit 2: Added in another photo
(FYI I'm really new to GitHub, so I hope that I have formatted my issue correctly)

**Comment by kleuter** [comment]
This is really strange. Did you try to reset smc?

Please run this [tool](https://www.crystalidea.com/downloads/smc.zip) in your Terminal.
`$./smc -l > smc_dump.txt`
and send me the output smc_dump.txt file
