### ISSUE TITLE
Xserve Fan Control (10.6)

### ISSUE THREAD

**Issue by gradystudios** [crystalidea/macs-fan-control#671]
I was going to write this under another similar bug report, but due to the legacy nature of this version of the app, I've decided to do it separate.

I own a 3,1 Xserve, upgraded Cpu's, but with the firmware on stock.
Macs fan control at first did not display this, but recently it has decided to display "fans 10-17"
These are entirely unmarked from the rest, I am guessing apart of the fan row of in and out fans. They do not allow for any configuration. I have heard this is fixed on newer versions of the app, but I cannot justify bringing this Xserve off 10.6 Server for it.

![image](https://user-images.githubusercontent.com/32470653/222991910-dc468950-9e8c-44ee-b2a3-f8e71416e9a7.png)

Help would be appreciated.

**Comment by kleuter** [comment]
You have to update to a newer OS, OS_X_El_Capitan preferably and use the latest version

**Comment by kleuter** [comment]
Unfortunately, we no longer support 10.6 and can't fix anything in the legacy version of the app

**Comment by gradystudios** [comment]
Well id think there would be a few at the time of Snow Leopard. aaaa
