### ISSUE TITLE
could not connect to the helper app

### ISSUE THREAD

**Issue by DrFishStix** [crystalidea/macs-fan-control#68]
Have been using Macs Fan control for >2 years on a mid-2010 iMac. Recently it does not allow us to change the settings after we enter an administrator password. Have deleted and reinstalled (including prior versions of 1.4). Any suggestions? Thanks.

**Comment by DrFishStix** [comment]
The error message we are getting is as follows:

"Macs Fan Control could not connect to the helper app to enable fan control as well as adjust the speeds.

Make sure to enter an administrator password when asked.

For more information, please contact us at https://www.crystalidea.com/contact"

**Comment by DrFishStix** [comment]
Macs Fan Control 1.4.10
iMac11,2
CPU: Intel(R) Core(TM) i3 CPU 540 @ 3.07GHz [105]
GPU: ATI Radeon HD 4670
macOS 10.12.6

Fans:
ODD-min{1000}curr{4350}max{4350}mode{0}
HDD-min{2363}curr{2362}max{2363}mode{0}
CPU-min{1200}curr{3997}max{4000}mode{0}


TempSensors:
TA0P () - 22.0625, 22.0625
TA0V () - 22.2578, 22.2578
TA0p (Ambient) - 23.875, 23.875
TC0C (CPU Core 1) - 31.7188, 31.7188
TC0H (CPU Heatsink) - 32, 32
TC1C (CPU Core 2) - 37, 37
TG0D (GPU Diode) - 39.25, 39.25
TG0H (GPU Heatsink) - 37.5, 37.5
TG0p (GPU Proximity) - 39, 39
TH0O () - 9, 9
TH1O () - 9, 9
TL0P () - 128, 128
TL0V () - 128, 128
TL0p () - 128, 128
TL1V () - 128, 128
TL2V () - 128, 128
TLAV () - 128, 128
TLBV () - 128, 128
TLCV () - 128, 128
TMCD () - 37, 37
TO0P () - 33.5625, 33.5625
TO0p (Optical Drive) - 34.5625, 34.5625
TPCD (Platform Controller Hub Die) - 59, 59
TS0V () - 32.2031, 32.2031
TS2P () - 35.375, 35.375
TS2V () - 32.5391, 32.5391
TS2p () - 35.375, 35.375
Tm0P () - 37.125, 37.125
Tm0p () - 37.125, 37.125
Tm1P () - 39.5, 39.5
Tm1p () - 39.5, 39.5
Tp1P () - 40.875, 40.875
Tp2H () - 47.875, 47.875
Tp3H (PSU Primary) - 38.75, 38.75


Disk drives:
 - 38
ST1000LM024 HN-M101MBB - 33

**Comment by kleuter** [comment]
The app must be moved to the Applications folder.
