### ISSUE TITLE
Current RPM is higher than max RPM

### ISSUE THREAD

**Issue by jovibroz** [crystalidea/macs-fan-control#681]
Auto CPU fan speed goes higher than 2600 rpm max. Potential overheating.

[iMac12,2_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/11254069/iMac12.2_tech_info.zip)
![Skärmavbild 2023-04-17 kl  19 59 45](https://user-images.githubusercontent.com/43058168/232572020-3fe25316-9cc8-4ab1-babc-ab77b8a62179.png)

**Comment by kleuter** [comment]
On some Apple computers current RPM can sometimes be higher than maximum (when running on auto), the reason for that is currently unknown, it can be a bug or a feature

Please try to reset SMC as described here:
https://support.apple.com/en-us/HT201295

**Comment by kleuter** [comment]
Duplicate https://github.com/crystalidea/macs-fan-control/issues/66
