### ISSUE TITLE
Mac Studio M2 Max CPU Sensors Not Avaiilable

### ISSUE THREAD

**Issue by austinramsay** [crystalidea/macs-fan-control#688]
Setup my new Mac Studio with M2 Max and the only available sensors are for the power supply and SSD. The CPU and additional sensors are not listed to setup a CPU based custom fan curve.

<img width="837" alt="Screenshot 2023-06-14 at 7 42 40 PM" src="https://github.com/crystalidea/macs-fan-control/assets/5309956/f67b7e90-150a-4804-ad8e-0e221238b93a">

**Comment by kleuter** [comment]
Please stay tunes, mac studio has just arrived to me, a beta with sensors support will be soon

**Comment by kleuter** [comment]
https://github.com/crystalidea/macs-fan-control/issues/693
