### ISSUE TITLE
New MacBook Air M2 15" / Mac Studio 2023 sensors support

### ISSUE THREAD

**Issue by Wizard37** [crystalidea/macs-fan-control#689]
Hi,

I know you just got your Mac Studio and I appreciate your help. Here's my Tech Info for the M2 MacBook Air 15". 

<img width="924" alt="MacsFanControl" src="https://github.com/crystalidea/macs-fan-control/assets/16352495/a61c3243-8889-4568-a02a-061a8e86849d">

[Mac14,15_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/11779549/Mac14.15_tech_info.zip)

**Comment by kleuter** [comment]
thank you!

**Comment by kleuter** [comment]
Could you please post tech info during CPU stress test with this app?
[Endurance.app.zip](https://github.com/crystalidea/macs-fan-control/files/11792939/Endurance.app.zip)

**Comment by Wizard37** [comment]
Here you go, I let it cook for a minute or two before running if that helps.

￼

**Comment by kleuter** [comment]
Thanks, please try the beta
https://github.com/crystalidea/macs-fan-control/issues/693
