### ISSUE TITLE
Macs Fan Control v1.5.16 beta

### ISSUE THREAD

**Issue by kleuter** [crystalidea/macs-fan-control#693]
What's new:

- #687
- #689
- #214
- #672 
- 
[macsfancontrol.zip](https://github.com/crystalidea/macs-fan-control/files/12172021/macsfancontrol.zip)

**Comment by Wizard37** [comment]
<img width="924" alt="Screenshot 2023-06-20 at 10 11 46 PM" src="https://github.com/crystalidea/macs-fan-control/assets/16352495/f96e6af2-b3e1-4fdf-a9d6-1384e5db531e">

Hit the CPU and GPU with full loads and here you go, looks great to me, thank you! (Also thanks for fixing the Memory Leak issue)

**Comment by kleuter** [comment]
Great, thanks for the screenshot.
