### ISSUE TITLE
iMac 17,1 - Fans won't go above 2800rpm

### ISSUE THREAD

**Issue by MJMullin2** [crystalidea/macs-fan-control#700]
[iMac17,1_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/12233374/iMac17.1_tech_info.zip)

I'm not sure if this is a bug, but I've noticed Macs Fan Control won't go about 2800rpm or so and I know my fans are capable of hitting 4800.  For whatever reason it just places an artificial limit of 2800 no matter how high the CPU temps go above what I have set as my max.

**Comment by kleuter** [comment]
It's not a bug, this model has max rpm limited to 2800

**Comment by MJMullin2** [comment]
That is not correct as I can get 4800 RPM using the old smcFanControl software.
