### ISSUE TITLE
Question regarding "Constant" fan speed

### ISSUE THREAD

**Issue by andsoitgoes** [crystalidea/macs-fan-control#71]
I'm hoping someone can enlighten me on this situation. I have a 2011 MacBook Pro that I'm trying to save the GPU on, I've done a lot of stuff to disable the discrete GPU, but I want to make sure I've got a fan speed that's a minimum of 4000 RPM just to be safe.

The question I have is in macs fan control, if I set it to a constant of 4000, will that mean it goes no higher? Is there a way I can easily set simply a "minimum" speed and let the system do what it needs above that? Or is that simply an impossible task? I've tried other apps and none work properly other than MFC.

Thanks so much in advance.

**Comment by kleuter** [comment]
> The question I have is in macs fan control, if I set it to a constant of 4000, will that mean it goes no higher? 
Yes.

Changing min fan rpm is currently not implemented;
https://github.com/crystalidea/macs-fan-control/issues/1

**Comment by bogdanbucluc** [comment]
hi ,i need  some help , i haw a problem whit me fan control i think .the rpm is going in to 5700 for a temperature of 55 C and i do not  know  if is  normal . me fans are placed on first cpu and on the forth cpu ... is me first time whit a apple mac retina 2012 . pleas if some one know what to do i will be  grateful 
merci Bogdan
