### ISSUE TITLE
Computer keeps crashing when not in use and Mac Fan Control is too

### ISSUE THREAD

**Issue by AndyRugg** [crystalidea/macs-fan-control#718]

**Comment by kleuter** [comment]
Windows, macOS?

Please post tech info and app screenshot as described at [here](https://github.com/crystalidea/macs-fan-control/blob/master/how-to-post-tech-info.md).

https://crystalidea.com/help/locating-mac-app-crash-logs

**Comment by AndyRugg** [comment]
Hello - 

I have a MacBook Pro with Monterey 12.7.1.

I’m sorry I don’t know which crash log you are looking for.  I have 36 logs in that particular folder.  I have copied and pasted one of the more recent Apple crash reports below that I received.  Let me know if you need something else.

Andrea



panic(cpu 2 caller 0xffffff800857f99f): userspace watchdog timeout: no successful checkins from WindowServer in 120 seconds
service: logd, total successful checkins since load (7510 seconds ago): 752, last successful checkin: 0 seconds ago
service: WindowServer, total successful checkins since load (7480 seconds ago): 732, last successful checkin: 120 seconds ago
service: remoted, total successful checkins since load (7510 seconds ago): 750, last successful checkin: 0 seconds ago
service: opendirectoryd, total successful checkins since load (7510 seconds ago): 752, last successful checkin: 0 seconds ago

Panicked task 0xffffff9506f08380: 3 threads: pid 105: watchdogd
Backtrace (CPU 2), panicked thread: 0xffffff95076a3540, Frame : Return Address
0xffffffc09a93b690 : 0xffffff8005079a3d 
0xffffffc09a93b6e0 : 0xffffff80051dca16 
0xffffffc09a93b720 : 0xffffff80051cbd83 
0xffffffc09a93b770 : 0xffffff8005019a90 
0xffffffc09a93b790 : 0xffffff8005079e0d 
0xffffffc09a93b8b0 : 0xffffff80050795c6 
0xffffffc09a93b910 : 0xffffff8005914b43 
0xffffffc09a93ba00 : 0xffffff800857f99f 
0xffffffc09a93ba10 : 0xffffff800857f5f2 
0xffffffc09a93ba30 : 0xffffff800857e971 
0xffffffc09a93bb60 : 0xffffff800588324c 
0xffffffc09a93bcc0 : 0xffffff8005182736 
0xffffffc09a93bdd0 : 0xffffff80050544cb 
0xffffffc09a93be60 : 0xffffff800506ae49 
0xffffffc09a93bef0 : 0xffffff80051aea4a 
0xffffffc09a93bfa0 : 0xffffff800501a276 
     Kernel Extensions in backtrace:
        ***@***.***>0xffffff800857ffff

Process name corresponding to current thread (0xffffff95076a3540): watchdogd
Boot args: chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
21G920

Kernel version:
Darwin Kernel Version 21.6.0: Wed Oct  4 23:55:28 PDT 2023; root:xnu-8020.240.18.704.15~1/RELEASE_X86_64
Kernel UUID: CA525A92-20FF-38D2-AB16-E64095531D5A
KernelCache slide: 0x0000000004e00000
KernelCache base:  0xffffff8005000000
Kernel slide:      0x0000000004e10000
Kernel text base:  0xffffff8005010000
__HIB  text base: 0xffffff8004f00000
System model name: MacBookPro15,1 (Mac-937A206F2EE63C01)
System shutdown begun: NO
Hibernation exit count: 0

System uptime in nanoseconds: 7514271786483
Last Sleep:           absolute           base_tsc          base_nano
 Uptime  : 0x000006d58d802ea1
 Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
 Wake    : 0x0000000000000000 0x0000000aa221d016 0x0000000000000000
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
Zone info:
 Zone map: 0xffffff8038b29000 - 0xffffffa038b29000
 . PGZ   : 0xffffff8038b29000 - 0xffffff803cb2a000
 . VM    : 0xffffff803cb2a000 - 0xffffff8508e5d000
 . RO    : 0xffffff8508e5d000 - 0xffffff86a24c3000
 . GEN0  : 0xffffff86a24c3000 - 0xffffff8b6e7f6000
 . GEN1  : 0xffffff8b6e7f6000 - 0xffffff903ab29000
 . GEN2  : 0xffffff903ab29000 - 0xffffff9506e5c000
 . GEN3  : 0xffffff9506e5c000 - 0xffffff99d318f000
 . DATA  : 0xffffff99d318f000 - 0xffffffa038b29000
 Metadata: 0xffffffcb53327000 - 0xffffffcb73327000
 Bitmaps : 0xffffffcb73327000 - 0xffffffcb7f327000

last started kext at 29739739862: @filesystems.smbfs	4.0 (addr 0xffffff7f9e531000, size 483328)
last stopped kext at 5201739480474: >!AFIVRDriver	4.1.0 (addr 0xffffff7f9c837000, size 8192)
loaded kexts:
@filesystems.smbfs	4.0
> AudioAUUC	1.70
> !ATopCaseHIDEventDriver	5450.8
> !AHIDALSService	1
> AGPM	129
> !APlatformEnabler	2.7.0d0
> X86PlatformShim	1.0.0
@kext.AMDFramebuffer	4.0.8
@filesystems.autofs	3.0
> !AUpstreamUserClient	3.6.9
@kext.AMDRadeonX4000	4.0.8
@kext.AMDRadeonServiceManager	4.0.8
> !AGFXHDA	140.3
> !A!IKBLGraphics	18.0.8
> !AGraphicsDevicePolicy	6.5.7
@AGDCPluginDisplayMetrics	6.5.7
> !ABridgeAudio!C	240.6
> pmtelemetry	1
|IOUserEthernet	1.0.1
> usb.!UUserHCI	1
> !AHV	1
> !ADiskImages2	126.141.2
> !AMuxControl2	6.5.7
@kext.AMD9500!C	4.0.8
> AGDCBacklightControl	6.5.7
> !AMCCSControl	1.16
> !A!ICFLGraphicsFramebuffer	18.0.8
> BridgeAudioCommunication	240.6
> !AAVEBridge	6.1
> !AThunderboltIP	4.0.3
> !A!IPCHPMC	2.0.1
> !A!ISlowAdaptiveClocking	4.0.0
> usb.realtek8153patcher	5.0.0
|SCSITaskUserClient	456.140.3
> BCMWLANFirmware4387.Hashstore	1
> BCMWLANFirmware4378.Hashstore	1
> BCMWLANFirmware4377.Hashstore	1
> BCMWLANFirmware4364.Hashstore	1
> BCMWLANFirmware4355.Hashstore	1
> !AFileSystemDriver	3.0.1
@filesystems.tmpfs	1
@filesystems.lifs	1
@filesystems.hfs.kext	583.100.10
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@filesystems.apfs	1934.141.2
> !ABCMWLANBusInterfacePCIeMac	1
@private.KextAudit	1.0
> !ASmartBatteryManager	161.0.0
> !AACPIButtons	6.1
> !ASMBIOS	2.1
> !AACPIEC	6.1
> !AAPIC	1.7
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	402
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
@Dont_Steal_Mac_OS_X	7.0.0
@kec.!AEncryptedArchive	1
> driverkit.serial	6.0.0
> !AActuatorDriver	5460.1
> !AMultitouchDriver	5460.1
> !AInputDeviceSupport	5460.1
> !AHS!BDriver	5450.8
> IO!BHIDDriver	9.0.0
> !AHIDKeyboard	228.2
@kext.triggers	1.0
@kext.AMDRadeonX4100HWLibs	1.0
@kext.AMDRadeonX4000HWServices	4.0.8
> !UAudio	416.2
> !AAudioClockLibs	140.1
> !A!ILpssUARTv1	3.0.60
> !A!ILpssUARTCommon	3.0.60
> !AOnboardSerial	1.0
|IOAudio!F	340.2
@vecLib.kext	1.2.0
|IO!BSerialManager	9.0.0
|IO!BPacketLogger	9.0.0
|IO!BHost!CUSBTransport	9.0.0
|IO!BHost!CUARTTransport	9.0.0
|IO!BHost!CTransport	9.0.0
> IO!BHost!CPCIeTransport	9.0.0
|IOAVB!F	1040.6
@plugin.IOgPTPPlugin	1040.3
|IOEthernetAVB!C	1.1.0
|CSR!BHost!CUSBTransport	9.0.0
|Broadcom!BHost!CUSBTransport	9.0.0
|Broadcom!B20703USBTransport	9.0.0
> !AIPAppender	1.0
> !AGraphicsControl	6.5.7
@kext.AMDSupport	4.0.8
> !ABacklightExpert	1.1.0
|IONDRVSupport	597
> !ASMBus!C	1.0.18d1
|IOAccelerator!F2	462.9
> !AThunderboltDPOutAdapter	8.5.1
> X86PlatformPlugin	1.0.0
> IOPlatformPlugin!F	6.0.0d8
@!AGPUWrangler	6.5.7
@!AGraphicsDeviceControl	6.5.7
|IOGraphics!F	597
|IOSlowAdaptiveClocking!F	1.0.0
> !UHIDMouse	196
> !AHIDMouse	196
> usb.!UHub	1.2
> usb.IOUSBHostHIDDevice	1.2
> usb.cdc.ecm	5.0.0
> usb.cdc.ncm	5.0.0
> !AThunderboltPCIUpAdapter	4.1.1
> usb.cdc	5.0.0
> usb.networking	5.0.0
> usb.!UHostCompositeDevice	1.2
> !AThunderboltPCIDownAdapter	4.1.1
> !AThunderboltDPInAdapter	8.5.1
> !AThunderboltDPAdapter!F	8.5.1
> !AHPM	3.4.4
> !A!ILpssI2C!C	3.0.60
> !A!ILpssI2C	3.0.60
> !A!ILpssDmac	3.0.60
> !ABSDKextStarter	3
|IOSurface	302.15
@filesystems.hfs.encodings.kext	1
> !AXsanScheme	3
> !AEthernetAquantiaAqtion	1.0.64
> !AThunderboltNHI	7.2.81
|IOThunderbolt!F	9.3.3
> usb.!UVHCIBCE	1.2
> usb.!UVHCICommonBCE	1.0
> usb.!UVHCI	1.2
> usb.!UVHCICommon	1.0
> !AEffaceableNOR	1.0
|IOBufferCopy!C	1.1.0
|IOBufferCopyEngine!F	1
|IONVMe!F	2.1.0
> !ABCMWLANCoreMac	1.0.0
|IOSerial!F	11
|IO80211!F	1200.12.2b2
|IOSkywalk!F	1.0
> mDNSOffloadUserClient	1.0.1b8
> IOImageLoader	1.0.0
> !AOLYHALMac	1
> corecapture	1.0.4
> usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
> usb.!UXHCIPCI	1.2
> usb.!UXHCI	1.2
> !AEFINVRAM	2.1
> !AEFIRuntime	2.1
> !ASMCRTC	1.0
|IOSMBus!F	1.1
|IOHID!F	2.0.0
|IOTimeSync!F	1040.3
|IONetworking!F	3.4
> DiskImages	493.0.0
|IO!B!F	9.0.0
|IOReport!F	47
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|CoreAnalytics!F	1
> !ASSE	1.0
> !AKeyStore	2
> !UTDM	533.120.2
|IOUSBMass!SDriver	210.120.3
|IOSCSIBlockCommandsDevice	456.140.3
|IO!S!F	2.1
|IOSCSIArchitectureModel!F	456.140.3
> !AMobileFileIntegrity	1.0.5
$!AImage4	4.2.0
@kext.CoreTrust	1
> !AFDEKeyStore	28.30
> !AEffaceable!S	1.0
> !ACredentialManager	1.0
> KernelRelayHost	1
|IOUSBHost!F	1.2
> !UHostMergeProperties	1.2
> usb.!UCommon	1.0
> !ABusPower!C	1.0
> !ASEPManager	1.0.1
> IOSlaveProcessor	1
> !AACPIPlatform	6.1
> !ASMC	3.1.9
|IOPCI!F	2.9
|IOACPI!F	1.4
> watchdog	1
@kec.pthread	1
@kec.Libm	1
@kec.corecrypto	12.0

**Comment by kleuter** [comment]
This crash report is not related to the app
