### ISSUE TITLE
Automatic doesn't work

### ISSUE THREAD

**Issue by wetdro** [crystalidea/macs-fan-control#723]
[MacBookPro19,1_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/13691727/MacBookPro19.1_tech_info.zip)

**Comment by kleuter** [comment]
What doesn't work here?

**Comment by wetdro** [comment]
> [MacBookPro19,1_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/13691727/MacBookPro19.1_tech_info.zip)

automatic, it cause my fans to not work at all and I almost fried my cpu if I didn't notice.....I

**Comment by kleuter** [comment]
I doubt that, the temperature is normal. Not a bug or an issue in the app, anyway.
