### ISSUE TITLE
Kernel_Task cpu usage

### ISSUE THREAD

**Issue by PietroAlese** [crystalidea/macs-fan-control#73]
Hi guys, I have a problem. If I use Macs Fan Control, after a few minutes of use, OSX limits the CPU to 800mhz regardless of the temperature. The process is the kernel_task. 
I have a 15 "macbook pro, 2015 version with double GPU OSX 10.13.5
How can I solve? Thank you, beautiful application!

**Comment by PietroAlese** [comment]
Hello! exactly the exact same problem! I had to give up for now.

Il giorno ven 31 ago 2018 alle 11:22 Jangar Sirah <notifications@github.com>
ha scritto:

**Comment by igorstajic** [comment]
This started happening for me after the latest Mojave update, on Macbook Pro 2018.
When running the app for a while kernel_task starts ramping up to CPU. The temperature doesn't even go over 60C, so I'm not sure if it's an overheating issue.

As soon as I turn of the fan control app, kernel_task starts going down.

**Comment by kleuter** [comment]
Normally it's an overheating issue. Please post a screenshot of the app when kernel task ramping up the CPU.

**Comment by PietroAlese** [comment]
Exact. The problem is not the temperature. By enabling manual control, the CPU after a load is set at 800 mhz until the system control is restored. Look:
https://ibb.co/Njy4Sqx

**Comment by PietroAlese** [comment]
I'm not an expert, but if I can give you feedback, it seems that when you set an "alert" temperature higher than the default one, this happens.

**Comment by PietroAlese** [comment]
After disabling MacFanControl:
https://ibb.co/BLkkRsY


Higher temperatures and almost maximum fans (default) but the CPU is full speed. Can I make you understand?

**Comment by PietroAlese** [comment]
This is fully loaded with automatic fan adjustment (from the system, without fancontrol).
Cpu at 3.3 ghz and 97 ° C with fans at full capacity.

https://ibb.co/3C9S2jS

**Comment by kleuter** [comment]
I didn't notice screenshot of Macs Fan Control, sir.

You're running iStat Menus and it can conflicts with other SMC software like Macs Fan Control.
0. Quit iStat Menus
1. Start recording a video
2. Start Macs Fan Control and leave all fans to Auto
3. Now change fans they way you did (how?)
4. Run the default Activity Monitor app, it displays CPU usage and kernel_task usage as well

**Comment by PietroAlese** [comment]
https://ibb.co/d5mpSrn

**Comment by PietroAlese** [comment]
Ok, now I'll record a video if you want.

**Comment by kleuter** [comment]
Your settings (80/95) are NOT correct and would lead to overheating. Try 60/100

**Comment by PietroAlese** [comment]
> Your settings (80/95) are NOT correct and would lead to overheating. Try 60/100 or constant value

Then it's better. BUT instead of stopping at 800 mhz now it is limited to 1.2 / 1.5 ghz.
https://ibb.co/N30RtFx

If it is deactivated, the frequency rises up to the turbo boost.
https://ibb.co/YbhW2F9

**Comment by PietroAlese** [comment]
Now I'm shortening your time. But TRUST, if active fancontrol, in full load, the CPU frequency drops drastically but at temperatures lower than those that the system manages by default.
I spend video editing. Can I explain myself?

**Comment by kleuter** [comment]
As I have already said - it's overheating. 
- Fans are spinning at MAXIMUM rpm with Auto settings
- With custom mode, the DON'T
- It leads to CPU temperature increase and [CPU throttles](https://www.pcmag.com/encyclopedia/term/60899/cpu-throttling)

**Comment by PietroAlese** [comment]
> * CPU throttles
Forgive me. With "automatic" the temperatures are higher, the fans are at maximum and the CPU is at maximum frequency.
With FanControl, temperatures are lower, the fans run less, but I have half the frequency available on the CPU. I do not understand.
it's normal?

**Comment by PietroAlese** [comment]
> As I have already said - it's overheating.
> 
> * Fans are spinning at MAXIMUM rpm with Auto settings
> * With custom mode, the DON'T
> * It leads to CPU temperature increase and [CPU throttles](https://www.pcmag.com/encyclopedia/term/60899/cpu-throttling)

Forgive me. With "automatic" the temperatures are higher, the fans are at maximum and the CPU is at maximum frequency.
With FanControl, temperatures are lower, the fans run less, but I have half the frequency available on the CPU. I do not understand.
it's normal?

**Comment by kleuter** [comment]
Temperatures with lower fan RPM are lower than with max RPM ???

**Comment by PietroAlese** [comment]
> Temperatures with lower fan RPM are less than with max RPM ??? 😮

1- 
https://ibb.co/xhWjt4k

2-
https://ibb.co/R6tm6ZT

**Comment by aviloff** [comment]
I switched off Turbo Boost Switcher off and all seems to return to normal. Would an optional feature to control turbo boost be included in some version of Mac Fan Control or in a software that would not conflict with it?

Thanks a lot for your work!
