### ISSUE TITLE
Consider open-sourcing the code

### ISSUE THREAD

**Issue by dmsnell** [crystalidea/macs-fan-control#74]
Thanks for all the work you've put into this app! It's been a helpful way to extend the usefulness of my rMBP and is something I find worth supporting. Still, there are a few small changes that I think would be useful to modify about it and I imagine that taking everyone's requests can be a bit overwhelming.

Have you considered open-sourcing the code? I'm not sure about others here but I'd still support your time and contributions even if the source were available. Thanks!

**Comment by kleuter** [comment]
@dmsnell thanks for the proposal, currently we don't have plans for that.
