### ISSUE TITLE
Macbook Pro 16 M3 PRO Not support

### ISSUE THREAD

**Issue by october-03** [crystalidea/macs-fan-control#745]
Macbook Pro 16 M3 PRO Not working

**Comment by raver119** [comment]
On M3 MAX app doesn't work either.

**Comment by HunterAhlquist** [comment]
Give this beta version a try if you haven't already, works with my M3 Pro
https://github.com/crystalidea/macs-fan-control/issues/721

**Comment by october-03** [comment]
> Give this beta version a try if you haven't already, works with my M3 Pro #721

Thanks

**Comment by october-03** [comment]
> Give this beta version a try if you haven't already, works with my M3 Pro #721

I tried this version, but it still doesn't work

**Comment by dewitpj** [comment]
I can also test this issue since it affects me too

Thanks

**Comment by kleuter** [comment]
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/785
