### ISSUE TITLE
add "monitoring only" option

### ISSUE THREAD

**Issue by irvin** [crystalidea/macs-fan-control#75]
I hope that we can have a new option to not enable to helper app.

This will be useful for those people who just want to monitoring the fan speed and temperature, but not really need to adjust the fan. Thus we can reduce the necessary of gain admin privilege.

**Comment by kleuter** [comment]
It's possible in the current version of the app.

**Comment by irvin** [comment]
@kleuter is it possible to skip the dialog when starting Mac Fan Control? 

(seems admin privilege is not a requirement to just monitoring the fan speed.
<img width="555" alt="2018-07-17 12 22 30" src="https://user-images.githubusercontent.com/165936/42770656-9f7ef5b2-8957-11e8-84ea-5e7012c6fe2b.png">
