### ISSUE TITLE
MFC does not recognize fans on windows 10, MacBookPro16,2. Resetting SMC and NVRAM does not help.

### ISSUE THREAD

**Issue by artvinee** [crystalidea/macs-fan-control#758]
MFC does not recognize fans on windows 10, MacBookPro16,2. Resetting SMC and NVRAM does not help.
![image](https://github.com/crystalidea/macs-fan-control/assets/74613662/f9b4b930-6cf6-41e3-8198-556e712b1777)

**Comment by artvinee** [comment]
> Please post tech info and app screenshot as described at [here](https://github.com/crystalidea/macs-fan-control/blob/master/how-to-post-tech-info.md).

[MacBookPro16,2_tech_info.zip](https://github.com/user-attachments/files/15872454/MacBookPro16.2_tech_info.zip)

**Comment by kleuter** [comment]
Have ever the app worked correctly on this particular mac model? (16,2)

**Comment by artvinee** [comment]
> Have ever the app worked correctly on this particular mac model? (16,2)

Yes

**Comment by kleuter** [comment]
What changed ?

**Comment by artvinee** [comment]
> What changed ?

I can't say for sure, maybe I've messed up some service responsible for determining temperatures from sensors.

**Comment by kleuter** [comment]
According to the log, there's a problem with the driver, it doesn't work and the app is not able to work without it.
Tried to uninstall the app, reboot, install again?

**Comment by artvinee** [comment]
> According to the log, there's a problem with our driver, it doesn't work and the app is not able to work without it. Tried to uninstall the app, reboot, install again?

There have certainly been attempts to both reinstall and clean all mfc data with Uninstall Tool. No result

**Comment by kleuter** [comment]
Probably the driver doesn't work when Windows is installed on an external drive.

**Comment by artvinee** [comment]
The thing is that everything worked with windows on an external disk. Reinstalling windows is very undesirable in my case.

**Comment by artvinee** [comment]
After reinstalling Windows, the problem on the MacBookPro16,2 still remains. Everything works stably on other Macs.
