### ISSUE TITLE
CPU / GPU sensor missing on 11 core Macbook M3 pro

### ISSUE THREAD

**Issue by Slash25e** [crystalidea/macs-fan-control#769]
[Mac15,6_tech_info.zip](https://github.com/user-attachments/files/16696502/Mac15.6_tech_info.zip)
![screen](https://github.com/user-attachments/assets/4ea66091-040b-4ca0-ac97-48dd8265fa72)

I don't have the option to check the cpu or gpu temperature of my device

**Comment by dtamm** [comment]
Can confirm, my view of the app looks the same!

**Comment by HeySora** [comment]
Use 1.5.17. --> https://github.com/crystalidea/macs-fan-control/issues/721

**Comment by Salzman-Software** [comment]
same issue. This appears to be a regression

**Comment by Slash25e** [comment]
Thank you!

**Comment by Davbzn89** [comment]
Will they fix it? Does anyone know how to fix it? Thank you

**Comment by Slash25e** [comment]
> Will they fix it? Does anyone know how to fix it? Thank you

The linked version of the app fixes it! 
unfortunately for me I’m on 18.1 developer beta and the fan control no longer works but as long as you aren’t on beta software than it should work great
