### ISSUE TITLE
Skip the admin privilege checking on starting when only monitoring

### ISSUE THREAD

**Issue by irvin** [crystalidea/macs-fan-control#77]
Is it possible to skip the dialog, when starting Mac Fan Control?
I only need monitoring the speed / temp, and it seems working property without admin privilege.

<img width="555" alt="2018-07-17 12 22 30" src="https://user-images.githubusercontent.com/165936/42770918-2010345c-8958-11e8-8ace-0f0e147e34a3.png">

**Comment by kleuter** [comment]
Thanks, will be implemented soon.

**Comment by kleuter** [comment]
Implemented in 1.5 beta #116
