### ISSUE TITLE
Fan control does not operate fans 

### ISSUE THREAD

**Issue by 9llawson** [crystalidea/macs-fan-control#778]
Previous used fan control every day however since yesterday fan control does nothing other than present the value of 0. System hardware tested with both fans operational.

**Comment by VABorisov** [comment]
dats true. i think cause sequoia

**Comment by 9llawson** [comment]
100% since the update

**Comment by kleuter** [comment]
Please post tech info and app screenshot as described at [here](https://github.com/crystalidea/macs-fan-control/blob/master/how-to-post-tech-info.md).

**Comment by jake765111** [comment]
> Please post tech info and app screenshot as described at [here](https://github.com/crystalidea/macs-fan-control/blob/master/how-to-post-tech-info.md).

Kleuter, Do you think a workaround will be found for this issue?

**Comment by Slash25e** [comment]
[MacBookPro20,2_tech_info.zip](https://github.com/user-attachments/files/17386976/MacBookPro20.2_tech_info.zip)

**Comment by kleuter** [comment]
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/785
