### ISSUE TITLE
Not working with Mojave upgrade

### ISSUE THREAD

**Issue by Beaksbury** [crystalidea/macs-fan-control#78]
This is a fantastic app but since installing the Beta Mojave upgrade, it no longer works. 

You can alter settings and everything appears to work, except that the fan itself doesn't run.

When will you be upgrading the app?

**Comment by kleuter** [comment]
Please read
[How to create an issue](https://github.com/crystalidea/macs-fan-control/blob/master/.github/CONTRIBUTING.md)

**Comment by cgregory22** [comment]
Was this resolved? Mine is doing the same thing.
