### ISSUE TITLE
Macbook Pro M4 Pro not working correctly

### ISSUE THREAD

**Issue by valentin56610** [crystalidea/macs-fan-control#782]
![Screenshot 2024-11-08 at 21 21 56](https://github.com/user-attachments/assets/2547a9dc-af3a-4b9c-a7ab-a9a873c86017)

I'm pretty sure you guys are aware of this already, but basically the app is not working properly with the latest macbook pros (M4 series) 

The fans will sometimes work, sometimes they won't, they will just stop working at some point, even when set to constant speed.
Also, I cannot see the temperature of the chip, only SSD or other not really useful things

Thanks a lot for your work!

**Comment by HunterAhlquist** [comment]
Same problem for me on an M4 Max. Here's my tech-zip: 
[Mac16,5_tech_info.zip](https://github.com/user-attachments/files/17684667/Mac16.5_tech_info.zip)

**Comment by d3myz** [comment]
Same here on my M4 Pro.

**Comment by cigsz** [comment]
Well so that confirms Apple is blocking not only M3 Macs but also M4 Macs to manually control fans.
Really not cool of them.

**Comment by valentin56610** [comment]
> Well so that confirms Apple is blocking not only M3 Macs but also M4 Macs to manually control fans. Really not cool of them.

Wait, what? Is this really a thing? So we can just delete the app? :'))

**Comment by cigsz** [comment]
> > Well so that confirms Apple is blocking not only M3 Macs but also M4 Macs to manually control fans. Really not cool of them.
> 
> Wait, what? Is this really a thing? So we can just delete the app? :'))

Looks like it is. Look at how many people suddenly after some updates reported that the app's not working. 

Fan control in M3 (and probably M4) Macs is dependent on the hardware settings but I think developers were somehow able to "override" these settings and we were able to control fans speed (at least I was able to make my fans work however I wanted to with iStat Menus).
But out of the sudden, I think after Sonoma 14.5 or 14.6 and Sequoia 15.0, no one can turn them on or control the speed until they turn on by themselves.
And the worse thing is that Apple made some changes that system allows the CPU to reach around 80 degrees before the fans even turn on. When they turn on, you're able to max them out but as soon as the temperature goes down, so do the fans and you're not able to control them once again. 

There's Sonoma 14.7.2 beta and Sequoia 15.2 beta so maybe they changed that, but I can't confirm as I'm still on 14.7.1

There's also a chance that M4 Macs are not "patched" yet and you'll be able to control the fans until Apple pushes an update to block them, just like they did with M3 Macs.

**Comment by valentin56610** [comment]
I am on Sequoia 15.1 (the OS that came with the new macbook pro) so I could not test any other OS version
But yeah, I tried another fans control app (TGPro) and it doesn't even register the CPU, and I cannot control the fans either

**Comment by HunterAhlquist** [comment]
iirc, didn't fan control only work after passing a firmware defined threshold? As in, the firmware turns power off to the fans, preventing software from changing speeds?

**Comment by cigsz** [comment]
> iirc, didn't fan control only work after passing a firmware defined threshold? As in, the firmware turns power off to the fans, preventing software from changing speeds?

That's true and on M3 Macs it's even hardware based but I guess developers were somehow able to bypass it? For example iStat Menus, as I was able to control fans however I wanted since the release of M3 Pro MacBook Pro until Sonoma 14.5 or 14.6
Also I've seen M1 and M2 users still being able to control fans even on Sequoia so whatever Apple did, they probably did it intentionally and only to M3+ Macs.

**Comment by valentin56610** [comment]
> > iirc, didn't fan control only work after passing a firmware defined threshold? As in, the firmware turns power off to the fans, preventing software from changing speeds?
> 
> That's true and on M3 Macs it's even hardware based but I guess developers were somehow able to bypass it? For example iStat Menus, as I was able to control fans however I wanted since the release of M3 Pro MacBook Pro until Sonoma 14.5 or 14.6 Also I've seen M1 and M2 users still being able to control fans even on Sequoia so whatever Apple did, they probably did it intentionally and only to M3+ Macs.

MacFansControl was working just fine on my M1 Pro on Sequoia 
M4 Pro, same setup, doesn't work, doesn't even list the CPU

**Comment by kealohavisuals** [comment]
This has been an issue for a while, It's explained on their support page. My M1 Max would work before Sequoia. After update, issues came.  I upgraded to M4 Max, Doesn't work.

<img width="657" alt="Screenshot 2024-11-12 at 10 32 06 PM" src="https://github.com/user-attachments/assets/c2bbbad8-5a36-44d7-b239-4676375b19e2">

**Comment by Kief5555** [comment]
Sometimes the M4 Pro is a hit or miss for me. 

Also, it seems like the system is also interfering with the controls. I set the fans to max and they correctly correspond. Moments later, macOS sets them back down to the default ~4000rpm that Apple does for fanning. Strange behaviour.

**Comment by Tab-dev-ac** [comment]
Previously using M1 pro MacBook Pro 14inch with Sequoia 15.1, it worked.
Upgrading to M4 pro MacBook Pro 16inch with Sequoia 15.1, it doesn't work.

**Comment by XEF2ZQ** [comment]
This is UNACCAPTABLE!!!! I just bought my 16inch M4pro after using windows laptop in hopes for getting something that has exceptional thermals. I had a 16inch m1max back in the days and i could have the fans set however i want to. 
Now i have M4pro that get warm to the touch and is just crap to use!
SOMEONE FIND A WAY to BYPASS or APPLE REVERT your BULLSHIT NOW!

**Comment by HunterAhlquist** [comment]
> This is UNACCAPTABLE!!!! I just bought an16inch M4pro after using windows laptop in hopes for getting something that has exceptional thermals. I had a 16inch m1max back in the days and i could have the fans set however i want to. Now i have M4pro that get warm to the touch and is just crap to use! SOMEONE FIND A WAY to BYPASS or APPLE REVERT your BULLSHIT NOW!

please don't take your anger out on innocent github users, thank you.

**Comment by Kief5555** [comment]
> This is UNACCAPTABLE!!!! I just bought an16inch M4pro after using windows laptop in hopes for getting something that has exceptional thermals. I had a 16inch m1max back in the days and i could have the fans set however i want to. 
> 
> Now i have M4pro that get warm to the touch and is just crap to use!
> 
> SOMEONE FIND A WAY to BYPASS or APPLE REVERT your BULLSHIT NOW!

Hey mate, you need to learn that the developer of the app is not responsible for changes made by Apple (if you've actually read the issue thread). Additionally, if you would've put in some research you would've also found out that this is an on-going issue. Taking out your anger on GitHub doesn't help anyone involved. We arnt your personal assistants on finding bypasses. Unless you want to contribute, I'd suggest you keep the comments to yourself (unless they help).

**Comment by XEF2ZQ** [comment]
> > This is UNACCAPTABLE!!!! I just bought an16inch M4pro after using windows laptop in hopes for getting something that has exceptional thermals. I had a 16inch m1max back in the days and i could have the fans set however i want to. Now i have M4pro that get warm to the touch and is just crap to use! SOMEONE FIND A WAY to BYPASS or APPLE REVERT your BULLSHIT NOW!
> 
> please don't take your anger out on innocent github users, thank you.

You too watch your tone incel rat

**Comment by HunterAhlquist** [comment]
> > > This is UNACCAPTABLE!!!! I just bought an16inch M4pro after using windows laptop in hopes for getting something that has exceptional thermals. I had a 16inch m1max back in the days and i could have the fans set however i want to. Now i have M4pro that get warm to the touch and is just crap to use! SOMEONE FIND A WAY to BYPASS or APPLE REVERT your BULLSHIT NOW!
> 
> > 
> 
> > please don't take your anger out on innocent github users, thank you.
> 
> 
> 
> You too watch your tone incel rat

lmfao, ban this troll

**Comment by HunterAhlquist** [comment]
> Ok let’s get this straight.
> i know this is an issue since M3.
> From what i know the SMC kext controls the fans and has the threshold values!
> 2nd: non of you are going to tell ME what i do and where i do it, who are you to talk to me like this?! I bet you wouldn’t dare saying shit IRL you‘d be kissing my feet else you‘d be done!
> I‘m not one of you 50th percentile weak beta incels, im a pro national champion athlete and highly intelligent too, extrovert, good looking, charming NOTHING I CAN SAY ABOUT you INCEL RAT.
> Know your place

new copypasta, holy shit this is so funny

**Comment by XEF2ZQ** [comment]
> > Ok let’s get this straight.
> > i know this is an issue since M3.
> > From what i know the SMC kext controls the fans and has the threshold values!
> > 2nd: non of you are going to tell ME what i do and where i do it, who are you to talk to me like this?! I bet you wouldn’t dare saying shit IRL you‘d be kissing my feet else you‘d be done!
> > I‘m not one of you 50th percentile weak beta incels, im a pro national champion athlete and highly intelligent too, extrovert, good looking, charming NOTHING I CAN SAY ABOUT you INCEL RAT.
> > Know your place
> 
> new copypasta, holy shit this is so funny

Your mother did you copy paste you scumbag rat incel!
My comment=pure reality 
Go fuck yourself keyboard warrior u ain’t shit IRL
I stomp on you IRL

**Comment by XEF2ZQ** [comment]
> > > > This is UNACCAPTABLE!!!! I just bought an16inch M4pro after using windows laptop in hopes for getting something that has exceptional thermals. I had a 16inch m1max back in the days and i could have the fans set however i want to. Now i have M4pro that get warm to the touch and is just crap to use! SOMEONE FIND A WAY to BYPASS or APPLE REVERT your BULLSHIT NOW!
> > 
> > 
> > > 
> > 
> > 
> > > please don't take your anger out on innocent github users, thank you.
> > 
> > 
> > You too watch your tone incel rat
> 
> lmfao, ban this troll

Know your place disgusting incel troll

**Comment by kleuter** [comment]
The troll was removed and banned, no worries 😄

**Comment by Tab-dev-ac** [comment]
> Previously using M1 pro MacBook Pro 14inch with Sequoia 15.1, it worked. Upgrading to M4 pro MacBook Pro 16inch with Sequoia 15.1, it doesn't work.

Yesterday, while using my MacBook under heavy load, I discovered that this app can adjust its fan speed. I suspect that as long as the MacBook’s fan isn’t completely stopped, this app can control the fan speed.

**Comment by sobchenyuk** [comment]
it's bad

**Comment by minisat0shi** [comment]
Hoping the team can find a workaround! Not that it's necessary to spin up fans if CPU/GPU cool, but good to have the option.

**Comment by kealohavisuals** [comment]
Hope everyone on this thread noticed the update they released in december. Yes it can work on the new pro/Max models, but is still limited. Honestly nothing different than the previous version. I feel the only difference they made is included a notification pop up from the software telling you why the fan has stopped and when it will kick back on. 
![Image 1-5-25 at 10 25 PM (1)](https://github.com/user-attachments/assets/d0a55259-8e35-4484-9748-31a42f85e0d9)
![Image 1-5-25 at 10 25 PM](https://github.com/user-attachments/assets/198aa01e-5fea-411a-a316-6de072aaa028)
![Image 1-5-25 at 10 27 PM](https://github.com/user-attachments/assets/13363b00-0570-47d0-b80d-e368915b3042)

**Comment by Sergi7531** [comment]
Experiencing same limitations on M4 Pro 14". Fans wont trigger and CPU average temperature sensor appears to be gone.

**Comment by sorenblank** [comment]
I thought I was the only one facing this. This was working even few months back on my M3 Pro.

**Comment by jshay21** [comment]
Are my nuts the only ones roasting here? That's why I want to turn on the damn fans a little higher! ughhh

**Comment by MahmoudAlyuDeen** [comment]
Apple's default curve leaves the laptop running warm long before the fans turn on, way too warm for way too long!
