### ISSUE TITLE
MacsFanControl doesn't work.

### ISSUE THREAD

**Issue by regnskali** [crystalidea/macs-fan-control#787]
# Issue: MacsFanControl Not Working on Apple M3 Pro (macOS Sequoia 15.1.1)

## Description:
MacsFanControl does not work on an Apple M3 Pro Mac running macOS Sequoia 15.1.1. The app is unable to control the system's fans as expected.

**Comment by kleuter** [comment]
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/785
