### ISSUE TITLE
Fans not detected on windows 10 pro

### ISSUE THREAD

**Issue by cj** [crystalidea/macs-fan-control#79]
Macs Fan Control 1.4.10
MacBookPro15,1
CPU: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz [100]
GPU: Radeon Pro 560X
Windows 10 x64 BUILD: 17134.167

Fans:

TempSensors:

Disk drives:
APPLE SSD AP1024M

![](https://image.prntscr.com/image/StHzMuuERt2IwpDMADv7-g.png)

**Comment by kleuter** [comment]
The app doesn't work on Windows on macs with [T2 chip](https://support.apple.com/en-us/HT208862)
