### ISSUE TITLE
Confirm artifact changes for v1.5.17

### ISSUE THREAD

**Issue by daeho-ro** [crystalidea/macs-fan-control#798]
Hello, this is Homebrew maintainer and I want to check the artifact changes.

 - exception while auditing macs-fan-control: SHA256 mismatch
Expected: ec22fe2723e9bd77efbcaaf5ba129571c049d88f7078224a0c2836e943b02ea5
  Actual: db659ef42c2553616817a3d92e61aaee6f20d18df98caba9d9fba73b26c1f9cf

Thanks,

**Comment by kleuter** [comment]
Sorry, we modified the zip file without version change , please always use the SHA256 of this ZIP:
https://crystalidea.com/downloads/macsfancontrol.zip
