### ISSUE TITLE
[MacOS Mojave] Newly created set will not stay selected, keeps defaulting to System Controlled after undetermined amount of time 

### ISSUE THREAD

**Issue by MarsWanKenobi** [crystalidea/macs-fan-control#81]
When I create a new set, I expect it to become the default and not revert back to System Controlled whenever it feels like it.  

Screenshot of main window: http://prntscr.com/kb5mdb
Technical info:
Macs Fan Control 1.4.10
MacBookPro14,1
CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz [100]
GPU: Intel Iris Plus Graphics 640
macOS 10.14.0

Fans:
Exhaust-min{1200}curr{0}max{7200}mode{0}

TempSensors:
TA0V () - 31.1367, 31.1367
TB0T (Battery Max) - 34.5, 34.5
TB1T (Battery Sensor 1) - 34.5, 34.5
TB2T (Battery Sensor 2) - 34.1992, 34.1992
TBXT () - 34.5, 34.5
TC0E () - 54.207, 54.207
TC0F () - 56.2891, 56.2891
TC0P (CPU Proximity) - 44.375, 44.375
TC1C (CPU Core 2) - 48, 48
TC2C (CPU Core 3) - 49, 49
TCGC (GPU PECI) - 49, 49
TCMX () - 49.3906, 49.3906
TCMc () - 0, 0
TCSA () - 48, 48
TCXC (CPU PECI) - 49.3906, 49.3906
TH0A () - 35, 35
TH0B () - 129, 129
TH0C () - 129, 129
TH0F () - 209, 209
TH0R () - 209, 209
TH0V () - 129, 129
TM0P (Memory Proximity) - 40.875, 40.875
TPCD (Platform Controller Hub Die) - 45, 45
TULD () - 128, 128
TULP () - 128, 128
TW0P () - 128, 128
TaLC () - 39.5625, 39.5625
Th1H (Heatsink Proximity) - 40.4375, 40.4375
Tm0P () - 128, 128
Ts0P (Palm Rest) - 33.25, 33.25
Ts0S () - 35.1719, 35.1719
Ts1P () - 31.9375, 31.9375
Ts1S () - 35.5, 35.5

Disk drives:

**Comment by kleuter** [comment]
__Auto__ means controlled by system, the must press on the __Custom...__ button to override the control.
