### ISSUE TITLE
Does MFC allow slower fan speeds than the systems? 

### ISSUE THREAD

**Issue by aesthicc** [crystalidea/macs-fan-control#82]
It seems like a bad idea to allow this behaviour.
On a hot day like today, MFC makes my fan spin slower than the standard fan control - values were: 75 max (celsius), 55 min, CPU PECI. 
Also, a feature request: an option to use any sensor instead of a single sensor.

I noticed this earlier, then I started using a different app so no screenshot.

**Comment by kleuter** [comment]
https://github.com/crystalidea/macs-fan-control/issues/1
https://github.com/crystalidea/macs-fan-control/issues/3
