### ISSUE TITLE
Supported Temperature Sensors

### ISSUE THREAD

**Issue by masonlee** [crystalidea/macs-fan-control#85]
Thank you for the temperature sensor description page at https://www.crystalidea.com/macs-fan-control/temperature-sensors !  I am filing this issue to note that not all the sensors in a 2018 MacBook Pro are described, in case that is helpful to you. Below is a screenshot of my sensors:

<img width="238" alt="screen shot 2018-08-02 at 7 08 04 pm" src="https://user-images.githubusercontent.com/76981/43620423-68596b02-9687-11e8-9989-d8714495ac43.png">

**Comment by kleuter** [comment]
Please read
[How to create an issue](https://github.com/crystalidea/macs-fan-control/blob/master/.github/CONTRIBUTING.md)

**Comment by masonlee** [comment]
Thanks.  Below is the additional info I assume you seek.

(Perhaps the new issue placeholder text could be improved to: "ATTENTION: All Issue reports should please contain a screenshot and the system Diagnostics text, as described here: <https://github.com/crystalidea/macs-fan-control/blob/master/.github/CONTRIBUTING.md>"?)

<img width="820" alt="image" src="https://user-images.githubusercontent.com/76981/43811583-12f0cb08-9a72-11e8-97ae-050335458db5.png">

Macs Fan Control 1.4.10
MacBookPro15,1
CPU: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz [100]
GPU: Intel UHD Graphics 630, Radeon Pro 560X
macOS 10.13.6

Fans:
Fan 0-min{2160}curr{4456}max{5927}mode{2,TC0P,38,49}
Fan 1-min{2000}curr{4151}max{5489}mode{2,TC0P,38,49}


TempSensors:
TA0V () - 26.3086, 26.3086
TB0T (Battery Max) - 35.5977, 35.5977
TB1T (Battery Sensor 1) - 34.3984, 34.3984
TB2T (Battery Sensor 2) - 35.5977, 35.5977
TC0E () - 50.1211, 50.1211
TC0F () - 52.2852, 52.2852
TC0P (CPU Proximity) - 44.1875, 44.1875
TC1C (CPU Core 2) - 46, 46
TC2C (CPU Core 3) - 47, 47
TC3C (CPU Core 4) - 47, 47
TC4C () - 46, 46
TC5C () - 46, 46
TC6C () - 46, 46
TCGC (GPU PECI) - 45, 45
TCMX () - 47.3906, 47.3906
TCSA () - 47, 47
TCXC (CPU PECI) - 47.3906, 47.3906
TF0S () - 4.64453, 4.64453
TG0P (GPU Proximity) - 43.125, 43.125
TGDD () - 35, 35
TGDF () - 35, 35
TGVP () - 41.25, 41.25
TH0F () - 40.0664, 40.0664
TH0X () - 39.9883, 39.9883
TH0a () - 36.1094, 36.1094
TH0b () - 39.3359, 39.3359
TH1a () - 39.9883, 39.9883
TH1b () - 33.2383, 33.2383
TM0P (Memory Proximity) - 45.0625, 45.0625
TPCD (Platform Controller Hub Die) - 50, 50
TTLD () - 33.8125, 33.8125
TTRD () - 46.75, 46.75
TW0P (Airport Card) - 45.4375, 45.4375
TaLC () - 34.5, 34.5
TaRC () - 42.4375, 42.4375
Th1H (Heatsink Proximity) - 40.75, 40.75
Th2H () - 45.3125, 45.3125
Tm0P () - 45.625, 45.625
Tm1P () - 129, 129
Ts0P (Palm Rest) - 34.9375, 34.9375
Ts0S () - 38.8008, 38.8008
Ts1P () - 32.0625, 32.0625
Ts1S () - 39.9219, 39.9219
Ts2S () - 37.6172, 37.6172


Disk drives:

**Comment by kleuter** [comment]
Thanks for the update. Sorry for the late reply. Looks like HDD temperature sensor is missing, will improve that as soon as I get this model.

**Comment by d-rosenberg** [comment]
There seem to be more sensors which are not documented. I don't see documentation of the following:
CPU Heatsink
GPU Proximity
LCD Proximity
MCP Proximity
PSU Primary
<Internal HDD model>


﻿Macs Fan Control 1.4.12
iMac10,1
CPU: Intel(R) Core(TM)2 Duo CPU E7600 @ 3.06GHz [100]
GPU: ATI Radeon HD 4670
macOS 10.13.6

Fans:
ODD-min{1000}curr{998}max{3800}mode{2,TL0p,56,66}
HDD-min{1100}curr{1324}max{5500}mode{2,Tp3H,58,68}
CPU-min{940}curr{1745}max{4600}mode{2,TG0p,48,58}

TempSensors:
TA0P () - 19.0234, 19.0234
TA0p (Ambient) - 24.75, 24.75
TA1v () - 25.0938, 25.0938
TC0C () - 129, 129
TC0D () - 129, 129
TC0H (CPU Heatsink) - 38.125, 38.125
TG0D (GPU Diode) - 52.25, 52.25
TG0H (GPU Heatsink) - 50.625, 50.625
TG0p (GPU Proximity) - 51, 51
TH0O () - 250, 250
TH1O () - 250, 250
TL0P () - 36.1992, 36.1992
TL0V () - 43.3906, 43.3906
TL0p (LCD proximity) - 50, 50
TL1V () - 39.9609, 39.9609
TL2V () - 41.0078, 41.0078
TLAV () - 41.0078, 41.0078
TLBV () - 40.1641, 40.1641
TLCV () - 43.3906, 43.3906
TN0D () - 129, 129
TN0H (MCP Heatsink) - 63.125, 63.125
TN0P () - 129, 129
TO0P () - 42.5, 42.5
TO0p (Optical Drive) - 43.5, 43.5
TS0V () - 39.418, 39.418
TS2V () - 39.3633, 39.3633
Tm0P () - 54.125, 54.125
Tm0p () - 54.125, 54.125
Tp1P () - 47.25, 47.25
Tp2H () - 50.25, 50.25
Tp3H (PSU Primary) - 47.125, 47.125

Disk drives:
ST31000528AS - 45

![image](https://user-images.githubusercontent.com/42289159/46242033-20a29400-c391-11e8-9470-145284de0863.png)

**Comment by roko-p** [comment]
@kleuter I am commenting here as the website suggests that as the recommended way to get support, and it is about supported temperature sensors.


### **My question: Is there a way to get readings from other sensors, like the ones @d-rosenberg listed?**

In my case, I seem to have faulty **`TC0T`** and **`TG0T`** sensors which alternate between show 256℃ and 0℃, and this seems to cause the fan to alternate between max speed (3700RPM) and normal speed every 2 seconds.

--------

I was going to buy the Pro Version so that I can bypass these two sensors with a custom configuration, but Macs Fan Control doesn't even show them (compared to https://github.com/exelban/stats , for example).

I assume I don't have any use of it for my case, do I?

This is on an iMac20,1 (2020).

Thanks!
