### ISSUE TITLE
Macs fan not detecting any fan on my Mac.

### ISSUE THREAD

**Issue by DaveTheThird** [crystalidea/macs-fan-control#86]
Hi there,

as requested I'm posting log and screenshot down here. Can anybody help me out? Already tried resetting SMC.

![image](https://user-images.githubusercontent.com/42073155/43655458-fdfd9a80-974e-11e8-8663-61814faadce6.png)

Macs Fan Control 1.4.10
MacBookPro15,1
CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz [100]
GPU: Radeon Pro 560X
Windows 10 x64

Fans:

TempSensors:

Disk drives:
APPLE SSD AP0512M

**Comment by DarkEcho3s** [comment]
I have the same issue. Works fine in MacOS but not in Windows. Looking around on various forums and Twitter it seems that many others are experiencing the same thing.

**Comment by DaveTheThird** [comment]
Do you know if there's any other viable way to control the fans while using Windows? I'm having 0 luck at finding a good software for that.

**Comment by DarkEcho3s** [comment]
Not that I have found. Was hoping Macs Fan Control would be updated to support the 2018 Macbook Pros.

**Comment by kleuter** [comment]
I'm sorry guys, the app currently [doesn't support the T2](https://github.com/crystalidea/macs-fan-control/issues/80) chip under Windows.
I've updated the [windows setup](https://www.crystalidea.com/downloads/macsfancontrol_setup.exe) to display a warning message now.

**Comment by DarkEcho3s** [comment]
Any chance this will be updated to support it? Even just knowing support will come eventually would be nice.....

**Comment by kleuter** [comment]
Currently no trace of chance to make it happen.
