### ISSUE TITLE
No Fans detected on this computer.

### ISSUE THREAD

**Issue by iamxwilson** [crystalidea/macs-fan-control#90]
Here are my specs

Macs Fan Control 1.4.10
MacBookAir7,2
CPU: Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz [100]
GPU: Intel HD Graphics 6000
macOS 10.12.6

Fans:

TempSensors:

Disk drives:
APPLE SSD SM0256G - 29

**Comment by kleuter** [comment]
Duplicate of
https://github.com/crystalidea/macs-fan-control/issues/15
