### ISSUE TITLE
Crackling Audio when Fan Control is turned on

### ISSUE THREAD

**Issue by mott91** [crystalidea/macs-fan-control#91]
Hello dear Fan Control Dev(s) and Users,

I have a new MacBook Pro 2018 13" which is pretty great but apple does a terrible job with fan ramping so I got Macs Fan Control. It does a great job cooling the computer but whenever I turn on Fan Control I get crackling Audio when I use it with my Focusrite Scarlett 2i4 Audio Interface.

The crackling happens approximately once per minute and lasts only a split second. Happens with every audio source but only with my Audio Interface.

Does anyone have a similar problem or any idea what the problem might be?

Thanks a lot!

<img width="822" alt="screen shot 2018-08-24 at 22 02 12" src="https://user-images.githubusercontent.com/26288363/44605450-b58dfc80-a7e9-11e8-8931-29944752be91.png">

Macs Fan Control 1.4.10
MacBookPro15,2
CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz [100]
GPU: Intel Iris Plus Graphics 655
macOS 10.13.6

Fans:
Fan 0-min{1250}curr{1254}max{6336}mode{2,TC1C,43,60}
Fan 1-min{1350}curr{1338}max{6864}mode{2,TC1C,43,60}

TempSensors:
TA0V () - 29.1758, 29.1758
TB0T (Battery Max) - 32.6992, 32.6992
TB1T (Battery Sensor 1) - 31.0977, 31.0977
TB2T (Battery Sensor 2) - 32.6992, 32.6992
TC0E () - 40.3828, 40.3828
TC0F () - 41.375, 41.375
TC0P (CPU Proximity) - 35.6875, 35.6875
TC1C (CPU Core 2) - 39, 39
TC2C (CPU Core 3) - 38, 38
TC3C (CPU Core 4) - 38, 38
TC4C () - 38, 38
TCGC (GPU PECI) - 39, 39
TCSA () - 41, 41
TCXC (CPU PECI) - 40.7344, 40.7344
TF0S () - 0, 0
TH0F () - 33.2812, 33.2812
TH0X () - 33.4141, 33.4141
TH0a () - 33.4141, 33.4141
TH0b () - 33.375, 33.375
TM0P (Memory Proximity) - 35.625, 35.625
TPCD (Platform Controller Hub Die) - 37, 37
TTLD () - 30.8125, 30.8125
TTRD () - 37.625, 37.625
TW0P (Airport Card) - 34.5625, 34.5625
TaLC () - 31.75, 31.75
TaRC () - 33.3125, 33.3125
Th1H (Heatsink Proximity) - 36.9375, 36.9375
Th2H () - 34.1875, 34.1875
Ts0P (Palm Rest) - 30.6875, 30.6875
Ts0S () - 32.2812, 32.2812
Ts1P () - 29.375, 29.375
Ts1S () - 32.1875, 32.1875
Ts2S () - 32.4453, 32.4453

Disk drives:

**Comment by kleuter** [comment]
Thanks for the info, unfortunately we're not able to reproduce the issue (no such hardware).

**Comment by mott91** [comment]
I understand. In the meantime I found out that this only happens when In turn on the sensor based value. Everything works fine with fixed fan values. So I guess the problem has to do with increasing or decreasing fan speeds.

**Comment by ckhatton** [comment]
Sounds like there's a short circuiting going on. I found that with my external speakers. If I plugged in my external powered hard drive, you could hear it through the speakers.
