### ISSUE TITLE
Test TjMax Temperature (max allowed CPU T) on your Mac

### ISSUE THREAD

**Issue by kleuter** [crystalidea/macs-fan-control#94]
**On Windows (running Boot Camp) (RECOMMENDED)**
1. Download and extract this small (100kb) [ZIP file](http://www.crystalidea.com/downloads/tools/tjMaxTest_win.zip)
2. Open cmd, run the following command
```
tjMaxTest_win.exe > output.txt
```
3. Paste here contents of newly created output.txt file.

**on OS X (only works with SIP, System Integrity Protection off)**
1. Download and extract this small (20kb) [ZIP file](http://www.crystalidea.com/downloads/tools/tjMaxTest_mac.zip). There should be 2 files inside (runTest and macsfancontrol.kext)
2. Open Terminal and go to this directory (runTest). After that execute the following commands:
```
sudo chown -R root:wheel macsfancontrol.kext
sudo kextload macsfancontrol.kext
./runTest > output.txt
sudo kextunload macsfancontrol.kext
```
3. Paste here contents of newly created output.txt file.

**Comment by Redzircon** [comment]
Is the maximum the temperature where the machine will shut down?

**Comment by Redzircon** [comment]
Thanks. :)

**Comment by ducphuc** [comment]
Sharing the TjMax for the Mac Pro "Six Core" 3.5 (Late 2013)
Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
MacPro6,1
ctl_id: 0xe for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 95

**Comment by DarrenMack-OD** [comment]
Sharing the TjMax for the MacBook Pro (15-inch, 2018), 2.6GHz Intel "Quad Core" i7
Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
MacBookPro15,1
ctl_id: 0x11 for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 100

**Comment by TrickzRazal** [comment]
_**Sharing the TjMax for the MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports), 2.3 GHz Intel "Quad Core" i5**_
Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
MacBookPro15,2
ctl_id: 0x10 for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 100

**Comment by ciotka-paszczaka** [comment]
Sharing the TjMax for the Mac Mini 6,1
Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
Macmini 6,1
ctl_id: 0xc for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 105

**Comment by Nick-Z0** [comment]
### Sharing the TjMax for the Macbook pro 13-inch 2015 i7
Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
MacBookPro12,1
TJMax T (C): 105

**Comment by mstrassell09** [comment]
Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
MacBookPro15,1
ctl_id: 0xf for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 100

**Comment by cygvis** [comment]
Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
MacBookPro10,1
ctl_id: 0xe for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 105

**Comment by rkwms** [comment]
Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz
iMac12,1
ctl_id: 0xd for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 86

**Comment by nickp1972** [comment]
Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
Macmini8,1
ctl_id: 0x10 for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 100

**Comment by nickp1972** [comment]
Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
MacBookPro11,1
ctl_id: 0xd for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 100

**Comment by beeflin** [comment]
iMac (Retina 4K, 21.5-inch, 2019):

Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
iMac19,2
ctl_id: 0x12 for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 100

**Comment by LangdonStIves** [comment]
BTW, I found a tool that shows this `TC0F` sensor correctly, as it's a signed delta from the temperature at which the CPU starts throttling: [istats](https://github.com/Chris911/iStats) (no relation to iStat Menus). I've opened an [issue for Fanny to get this fixed](https://github.com/DanielStormApps/Fanny/issues/53), more details see there.

**Comment by marcgarciamarti** [comment]
HI there,

any ideas?

```
Marcs-MacBook-Air:tjMaxTest_mac marc$ ls -l
total 24
drwxr-xr-x@ 3 marc  staff    96 Jul 25  2014 macsfancontrol.kext
-rwxr-xr-x@ 1 marc  staff  9316 Jul 25  2014 runTest
Marcs-MacBook-Air:tjMaxTest_mac marc$ 
Marcs-MacBook-Air:tjMaxTest_mac marc$ sudo chown -R root:wheel macsfancontrol.kext
Marcs-MacBook-Air:tjMaxTest_mac marc$ sudo kextload macsfancontrol.kext
/Users/marc/Downloads/tjMaxTest_mac/macsfancontrol.kext failed to load - (libkern/kext) not loadable (reason unspecified); check the system/kernel logs for errors or try kextutil(8).
Marcs-MacBook-Air:tjMaxTest_mac marc$
```

**Comment by simone412** [comment]
MacBook Pro (13 inch, Mid 2010) El Capitan OSX
Intel(R) Core(TM)2 Duo CPU     P8800  @ 2.66GHz
MacBookPro7,1
ctl_id: 0xd for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 0

???? There is some particular reason for this 0 value? Is my MacBook Pro too old to run this script?

**Comment by simone412** [comment]
MacBook Pro (13 inch, Mid 2010) El Capitan OSX
Intel(R) Core(TM)2 Duo CPU     P8800  @ 2.66GHz
MacBookPro7,1
ctl_id: 0xd for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 0

???? There is some particular reason for this 0 value? Is my MacBook Pro too old to run this script?

**Comment by simone412** [comment]
MacBook Pro (13 inch, Mid 2010) El Capitan OSX
Intel(R) Core(TM)2 Duo CPU     P8800  @ 2.66GHz
MacBookPro7,1
ctl_id: 0xd for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 0

???? There is some particular reason for this 0 value? Is my MacBook Pro too old to run this script?

**Comment by simone412** [comment]
MacBook Pro (13 inch, Mid 2010) El Capitan OSX
Intel(R) Core(TM)2 Duo CPU     P8800  @ 2.66GHz
MacBookPro7,1
ctl_id: 0xd for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 0

???? There is some particular reason for this 0 value? Is my MacBook Pro too old to run this script?

**Comment by simone412** [comment]
MacBook Pro (13 inch, Mid 2010) El Capitan OSX
Intel(R) Core(TM)2 Duo CPU     P8800  @ 2.66GHz
MacBookPro7,1
ctl_id: 0xd for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 0

???? There is some particular reason for this 0 value? Is my MacBook Pro too old to run this script?

**Comment by simone412** [comment]
MacBook Pro (13 inch, Mid 2010) El Capitan OSX
Intel(R) Core(TM)2 Duo CPU     P8800  @ 2.66GHz
MacBookPro7,1
ctl_id: 0xd for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 0

???? There is some particular reason for this 0 value? Is my MacBook Pro too old to run this script?

**Comment by simone412** [comment]
MacBook Pro (13 inch, Mid 2010) El Capitan OSX
Intel(R) Core(TM)2 Duo CPU     P8800  @ 2.66GHz
MacBookPro7,1
ctl_id: 0xd for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 0

???? There is some particular reason for this 0 value? Is my MacBook Pro too old to run this script?

**Comment by simone412** [comment]
MacBook Pro (13 inch, Mid 2010) El Capitan OSX
Intel(R) Core(TM)2 Duo CPU     P8800  @ 2.66GHz
MacBookPro7,1
ctl_id: 0xd for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 0

???? There is some particular reason for this 0 value? Is my MacBook Pro too old to run this script?

**Comment by simone412** [comment]
MacBook Pro (13 inch, Mid 2010) El Capitan OSX
Intel(R) Core(TM)2 Duo CPU     P8800  @ 2.66GHz
MacBookPro7,1
ctl_id: 0xd for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 0

???? There is some particular reason for this 0 value? Is my MacBook Pro too old to run this script?

**Comment by simone412** [comment]
MacBook Pro (13 inch, Mid 2010) El Capitan OSX
Intel(R) Core(TM)2 Duo CPU     P8800  @ 2.66GHz
MacBookPro7,1
ctl_id: 0xd for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 0

???? There is some particular reason for this 0 value? Is my MacBook Pro too old to run this script?

**Comment by simone412** [comment]
MacBook Pro (13 inch, Mid 2010) El Capitan OSX
Intel(R) Core(TM)2 Duo CPU     P8800  @ 2.66GHz
MacBookPro7,1
ctl_id: 0xd for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 0

???? There is some particular reason for this 0 value? Is my MacBook Pro too old to run this script?

**Comment by simone412** [comment]
MacBook Pro (13 inch, Mid 2010) El Capitan OSX
Intel(R) Core(TM)2 Duo CPU     P8800  @ 2.66GHz
MacBookPro7,1
ctl_id: 0xd for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 0

???? There is some particular reason for this 0 value? Is my MacBook Pro too old to run this script?

**Comment by simone412** [comment]
MacBook Pro (13 inch, Mid 2010) El Capitan OSX
Intel(R) Core(TM)2 Duo CPU     P8800  @ 2.66GHz
MacBookPro7,1
ctl_id: 0xd for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 0

???? There is some particular reason for this 0 value? Is my MacBook Pro too old to run this script?

**Comment by simone412** [comment]
MacBook Pro (13 inch, Mid 2010) El Capitan OSX
Intel(R) Core(TM)2 Duo CPU     P8800  @ 2.66GHz
MacBookPro7,1
ctl_id: 0xd for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 0

???? There is some particular reason for this 0 value? Is my MacBook Pro too old to run this script?

**Comment by adamlogan** [comment]
Output in Bootcamp on Bootcamp on clean WIndows 10 install. Not sure what's going on with the Error bit, I'm not as familiar with the command line development environment considerations on Windows. I will try again on macOS Catalina and report back.

Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
Macmini8,1
Error init InitOpenLibSys, return code

**Comment by Prerunning** [comment]
Why not just look it up on Intels website?

**Comment by kleuter** [comment]
It's only available for some CPU models

**Comment by keramzyt** [comment]
Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
MacBookPro14,1
ctl_id: 0x10 for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 100

**Comment by pauloord123** [comment]
Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz
MacBookPro10,1
ctl_id: 0xe for ctl_name: crystalidea.macsfancontrol.kext
TjMax T: 105

...but what is TjMax and how to relate it to the sensors in MacFanControl?

I use both fans (L and R) in my MBP for controlling the SSD with MacFanControl.

**Comment by arjun372** [comment]
Unable to use the provided kext file on Ventura 13.3.1, getting a Bad Code Signature message.

Ventura 13.3.1
Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
MacBookPro16,1

```zsh
arjun@ArjunsMcBookPro tjMaxTest_mac % sudo chown -R root:wheel macsfancontrol.kext
sudo kextload macsfancontrol.kext
./runTest > output.txt
sudo kextunload macsfancontrol.kext
Password:
Executing: /usr/bin/kmutil load -p /Users/arjun/Downloads/tjMaxTest_mac/macsfancontrol.kext
Error Domain=KMErrorDomain Code=29 "Authenticating extension failed: Kext crystalidea.macsfancontrol.kext v1 in executable kext bundle crystalidea.macsfancontrol.kext at /private/var/db/KernelExtensionManagement/Staging/crystalidea.macsfancontrol.kext.qjWx7Y/macsfancontrol.kext:

Authenticating extension failed: Bad code signature" UserInfo={NSLocalizedDescription=Authenticating extension failed: Kext crystalidea.macsfancontrol.kext v1 in executable kext bundle crystalidea.macsfancontrol.kext at /private/var/db/KernelExtensionManagement/Staging/crystalidea.macsfancontrol.kext.qjWx7Y/macsfancontrol.kext:

Authenticating extension failed: Bad code signature}
ioctl CTLIOCGINFO: No such file or directory
Executing: /usr/bin/kmutil unload -p /Users/arjun/Downloads/tjMaxTest_mac/macsfancontrol.kext
Error Domain=KMErrorDomain Code=3 "Error occurred unloading extensions: Missing extension with identifier crystalidea.macsfancontrol.kext : Authenticating extension failed: Kext crystalidea.macsfancontrol.kext v1 in executable kext bundle crystalidea.macsfancontrol.kext at /private/var/db/KernelExtensionManagement/Staging/crystalidea.macsfancontrol.kext.qjWx7Y/macsfancontrol.kext:

Authenticating extension failed: Bad code signature" UserInfo={NSLocalizedDescription=Error occurred unloading extensions: Missing extension with identifier crystalidea.macsfancontrol.kext : Authenticating extension failed: Kext crystalidea.macsfancontrol.kext v1 in executable kext bundle crystalidea.macsfancontrol.kext at /private/var/db/KernelExtensionManagement/Staging/crystalidea.macsfancontrol.kext.qjWx7Y/macsfancontrol.kext:

Authenticating extension failed: Bad code signature}

```

**Comment by AlixSPQR** [comment]
The link to the zip file for OS X doesn't work. Please direct me to the zip file.
