### ISSUE TITLE
Updating failure.

### ISSUE THREAD

**Issue by Philipwfarris** [crystalidea/macs-fan-control#95]
Hi,

I keep getting this error when trying to update from 1.4.10 to 1.4.11

![screen shot 2018-09-01 at 5 45 52 pm](https://user-images.githubusercontent.com/42899784/44950241-c1447900-ae10-11e8-8ade-ce3643a9a21b.jpg)

ATTENTION: All Issue reports should please contain a screenshot and the system Diagnostics text, as described [here](https://github.com/crystalidea/macs-fan-control/blob/master/.github/CONTRIBUTING.md)

Macs Fan Control 1.4.10
MacBookPro14,2
CPU: Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz [100]
GPU: Intel Iris Plus Graphics 650
macOS 10.14.0

Fans:
Left side-min{1250}curr{4308}max{6336}mode{2,Th1H,32,43}
Right side-min{1350}curr{4678}max{6864}mode{2,Th1H,32,43}

TempSensors:
TA0V () - 33.4102, 33.4102
TB0T (Battery Max) - 34.1992, 34.1992
TB1T (Battery Sensor 1) - 34.1992, 34.1992
TB2T (Battery Sensor 2) - 33.7969, 33.7969
TBXT () - 34.1992, 34.1992
TC0E () - 47.75, 47.75
TC0F () - 49.1719, 49.1719
TC0P (CPU Proximity) - 39.25, 39.25
TC1C (CPU Core 2) - 53, 53
TC2C (CPU Core 3) - 53, 53
TCGC (GPU PECI) - 43, 43
TCMX () - 53, 53
TCMc () - 0, 0
TCSA () - 45, 45
TCTD () - 0.199219, 0.199219
TCXC (CPU PECI) - 44.9219, 44.9219
TH0A () - 30.9375, 30.9375
TH0B () - 255.996, 255.996
TH0C () - 255.996, 255.996
TH0F () - 207.008, 207.008
TH0R () - 206.938, 206.938
TH0a () - 30.9375, 30.9375
TH0b () - 255.996, 255.996
TH0c () - 255.996, 255.996
TH0x () - 129, 129
TM0P (Memory Proximity) - 39.5625, 39.5625
TPCD (Platform Controller Hub Die) - 39, 39
TSDO () - 0, 0
TSDV () - 129, 129
TTLD () - 32.125, 32.125
TTRD () - 29.625, 29.625
TW0P () - 129, 129
TaLC () - 32.8125, 32.8125
TaRC () - 28.875, 28.875
Th1H (Heatsink Proximity) - 38.875, 38.875
Th2H () - 36.8125, 36.8125
Ts0P (Palm Rest) - 32.625, 32.625
Ts0S () - 35.5, 35.5
Ts1P () - 30.125, 30.125
Ts1S () - 35.4805, 35.4805

Disk drives:

**Comment by masonlee** [comment]
I was able to update without any problem, in case that helps someone track down this issue.

**Comment by kleuter** [comment]
Looks like there were too many people updating 😄
