### ISSUE TITLE
requests for an update, with latest update installed

### ISSUE THREAD

**Issue by millerthegorilla** [crystalidea/macs-fan-control#96]
I have just updated the program, having been prompted to by the control that appears, but I have already updated to the latest version available from the website.

Many thanks

Technical Data:
Macs Fan Control 1.4.11
iMac11,1
CPU: Intel(R) Core(TM) i7 CPU 860 @ 2.80GHz [99]
GPU: ATI Radeon HD 4850
macOS 10.13.6

Fans:
ODD-min{1000}curr{998}max{3800}mode{0}
HDD-min{1100}curr{1100}max{5500}mode{2,TG0p,64,74}
CPU-min{940}curr{938}max{2100}mode{2,TC0C,60,75}

TempSensors:
TA0P () - 20.125, 20.125
TA0V () - 20.0469, 20.0469
TA0p (Ambient) - 25.75, 25.75
TA1v () - 25.1914, 25.1914
TC0C (CPU Core 1) - 32.375, 32.375
TC0D () - 129, 129
TC0H (CPU Heatsink) - 33.375, 33.375
TC0P () - 129, 129
TC1C (CPU Core 2) - 32, 32
TG0D (GPU Diode) - 43.75, 43.75
TG0H (GPU Heatsink) - 41.75, 41.75
TG0p (GPU Proximity) - 44, 44
TH0O () - 9, 9
TH1O () - 9, 9
TL0P () - 21.7383, 21.7383
TL0V () - 29.4844, 29.4844
TL0p (LCD proximity) - 35.375, 35.375
TL1V () - 28.8945, 28.8945
TL2V () - 30.4219, 30.4219
TLAV () - 30.4219, 30.4219
TLBV () - 28.5859, 28.5859
TLCV () - 29.4844, 29.4844
TMCD () - 0, 0
TO0P () - 28.375, 28.375
TO0p (Optical Drive) - 29.375, 29.375
TPCD (Platform Controller Hub Die) - 59, 59
TS0V () - 34.543, 34.543
TS2P () - 30.75, 30.75
TS2V () - 28.8906, 28.8906
TS2p () - 30.75, 30.75
Tm0P () - 34.375, 34.375
Tm0p () - 34.375, 34.375
Tp1P () - 36.25, 36.25
Tp2H () - 47.75, 47.75
Tp3H (PSU Primary) - 40, 40

Disk drives:
Samsung SSD 850 EVO 500GB - 26

**Comment by kleuter** [comment]
Your probably have 2 versions installed
