### ISSUE TITLE
Upgrade prompt prevents cooling until clicked - wth?

### ISSUE THREAD

**Issue by rc3105** [crystalidea/macs-fan-control#98]
Very very simple incredibly stupid issue. 

On boot we're presented with a "new version available please see our website" dialog. 

The fans don't spin up until that dialog is cleared by clicking ok.

The utility installed SPECIFICALLY to COOL the machine AUTOMATICALLY stops working without user intervention.

If you want eyeballs, congrats it worked.  If you want IT guys that recommend the utility, well you just lost those.

**Comment by kleuter** [comment]
I removed this update dialog from the current version 1.1.11, it will never appear again.
