### ISSUE TITLE
Network error?

### ISSUE THREAD

**Issue by ckhatton** [crystalidea/macs-fan-control#99]
When I click "Install Update" or use the Windows installer, it reports a network failure.

![screen01](https://user-images.githubusercontent.com/5657372/44976231-85b6c580-af5c-11e8-8bc0-ac8a0fa52499.png)

![screen02](https://user-images.githubusercontent.com/5657372/44976238-8b141000-af5c-11e8-95b3-8c93005c872e.png)

Macs Fan Control 1.4.10
iMac10,1
CPU: Intel(R) Core(TM)2 Duo CPU E7600 @ 3.06GHz [100]
GPU: NVIDIA GeForce 9400  
Windows 7 x64

Fans:
ODD-min{1000}curr{1001}max{4350}mode{2,TO0p,37,47}
HDD-min{1100}curr{1123}max{6300}mode{2,TN0H,47,57}
CPU-min{1200}curr{1348}max{4000}mode{2,TC0H,32,42}

TempSensors:
TA0P () - 18.1797, 18.1797
TA0p (Ambient) - 23.375, 23.375
TC0C () - 129, 129
TC0D () - 129, 129
TC0H (CPU Heatsink) - 32.875, 32.875
TG0D () - 129, 129
TG0H () - 129, 129
TG0p () - 129, 129
TH0O () - 9, 9
TH1O () - 9, 9
TL0P () - 30.7188, 30.7188
TL0V () - 33.3594, 33.3594
TL0p (LCD proximity) - 44.625, 44.625
TL1V () - 35.207, 35.207
TL2V () - 35.4727, 35.4727
TLAV () - 34.6406, 34.6406
TLBV () - 35.4727, 35.4727
TLCV () - 33.3594, 33.3594
TN0D () - 129, 129
TN0H (MCP Heatsink) - 48, 48
TN0P () - 129, 129
TO0P () - 36, 36
TO0p (Optical Drive) - 37, 37
TS0V () - 25.6094, 25.6094
TS2V () - 31.9883, 31.9883
Tm0P () - 37.875, 37.875
Tm0p () - 37.875, 37.875
Tp1P () - 41.5, 41.5
Tp2H () - 47.125, 47.125
Tp3H (PSU Primary) - 41.5, 41.5
Tp3v () - 0, 0

Disk drives:
Samsung SSD 850 EVO 500GB - 36

:octocat:

**Comment by kleuter** [comment]
Please try again, looks like too many request these days due to the update

**Comment by kleuter** [comment]
Fixed on the server (due to ipv6 issues), thanks!
